Db Maintenance scripts for TheCombine
sillsdev/TheCombine pull request #1031
Opened 2021-02-18 20:12 UTC by jmgrady

Broaden the scope of the combine_backup role to include a number of maintenance scripts. This includes the following changes:

1. Rename the combine_backup role to combine_maintenance
2. Add the following maintenance scripts:
   - add an existing user to a project as an admin or general user
   - make an existing user a site admin
   - delete a project and its associated data
3. Add playbook to install the general admin user
4. Create a role to install a specific version of TheCombine - this is useful for a NUC or other target machine that is not maintained by the CI/CD processes
5. Create a role to install the general admin user

2021-02-23 15:14 UTC, imnasnainaec requested changes
> Reviewed 6 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1031)* status: 6 of 24 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUERq5j42-8SVe7bfzu:-MUERq5j42-8SVe7bfzv:bccguuy) (no related file):*
@jmgrady You say you "Rename the combine_backup role to combine_maintenance" but they are duplicated, not renamed, as all the `combine_backup` stuff is still there.

---
___
*[README.md, line 62 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUELk-X5ZBFu9ce60JT:-MUELk-X5ZBFu9ce60JU:boc1cqb) ([raw file](https://github.com/sillsdev/thecombine/blob/5ae1701b5aafbca60227eb2ef822af3235d73949/README.md#L62)):*
<details><summary><i alt="summary">Quoted 22 lines of code…</i></summary>

> ```
> 1. [Getting Started with Development](#getting-started-with-development)
> 2. [Available Scripts](#available-scripts)
>    1. [Running in Development](#running-in-development)
>    2. [Running the Automated Tests](#running-the-automated-tests)
>    3. [Generate License Report](#generate-license-report)
>    4. [Set Project Version](#set-project-version)
> 3. [Maintenance Scripts for TheCombine](#maintenance-scripts-for-thecombine)
>    1. [Environments](#environments)
>    2. [Development Environment Scripts](#development-environment-scripts)
>    3. [Local Docker Container Scripts](#local-docker-container-scripts)
>    4. [Production Environment Scripts](#production-environment-scripts)
> 4. [Docker](#docker)
>    1. [Installing Docker](#installing-docker)
>    2. [Build and Run](#build-and-run)
> 5. [Python](#python)
>    1. [Windows Python Installation](#windows-python-installation)
>    2. [Linux Python Installation](#linux-python-installation)
>    3. [macOS Python Installation](#macos-python-installation)
>    4. [Python Packages](#python-packages)
> 6. [User Guide](#user-guide)
> 7. [Production](#production)
> 8. [Learn More](#learn-more)
> ```
</details>

If we change all these numerals to 1, markdown will increment them appropriately, and anybody making future additions or subtractions won't have to think about fixing the numbering.
___
*[README.md, line 251 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUEOggF4cPAKEO7Zpyd:-MUEOggF4cPAKEO7Zpye:b7w07xt) ([raw file](https://github.com/sillsdev/thecombine/blob/5ae1701b5aafbca60227eb2ef822af3235d73949/README.md#L251)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
> ### `npm run fmt-backend`
> Automatically format the C# source files in the backend.
> ### `npm run lint`
> Runs ESLint on the codebase to detect code problems that should be fixed.
> ### `npm run fmt-frontend`
> Auto-format frontend code in the `src` folder.
> ### `npm run build`
> ...
> ### `npm run import-sem-doms`
> ```
</details>

These five commands should  \### -> \#### to match the restructure. And unless they are meant to be under the new `### Running the Automated Tests` heading, they need their own section heading that can be added to the new ToC.


<!-- Sent from Reviewable.io -->

2021-02-23 15:30 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1031)* status: 6 of 31 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUERq5j42-8SVe7bfzu:-MUEUu8vEkkU1CE1sefb:b-896fix) (no related file):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

@jmgrady You say you "Rename the combine_backup role to combine_maintenance" but they are duplicated, not renamed, as all the `combine_backup` stuff is still there.
</blockquote></details>

Done.

---
___
*[README.md, line 62 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUELk-X5ZBFu9ce60JT:-MUEUwxnEMlUjoW6iaz7:bov7bqj) ([raw file](https://github.com/sillsdev/thecombine/blob/5ae1701b5aafbca60227eb2ef822af3235d73949/README.md#L62)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> 1. [Getting Started with Development](#getting-started-with-development)
> 2. [Available Scripts](#available-scripts)
>    1. [Running in Development](#running-in-development)
>    2. [Running the Automated Tests](#running-the-automated-tests)
>    3. [Generate License Report](#generate-license-report)
>    4. [Set Project Version](#set-project-version)
> 3. [Maintenance Scripts for TheCombine](#maintenance-scripts-for-thecombine)
>    1. [Environments](#environments)
>    2. [Development Environment Scripts](#development-environment-scripts)
>    3. [Local Docker Container Scripts](#local-docker-container-scripts)
>    4. [Production Environment Scripts](#production-environment-scripts)
> 4. [Docker](#docker)
>    1. [Installing Docker](#installing-docker)
>    2. [Build and Run](#build-and-run)
> 5. [Python](#python)
>    1. [Windows Python Installation](#windows-python-installation)
>    2. [Linux Python Installation](#linux-python-installation)
>    3. [macOS Python Installation](#macos-python-installation)
>    4. [Python Packages](#python-packages)
> 6. [User Guide](#user-guide)
> 7. [Production](#production)
> 8. [Learn More](#learn-more)
> ```
If we change all these numerals to 1, markdown will increment them appropriately, and anybody making future additions or subtractions won't have to think about fixing the numbering.
</blockquote></details>

I agree.  However, I had that previously and John requested that the numbers increment in the document so that it is more readable to humans.  We should discuss with Jason to see if LSDev has a preference in general.
___
*[README.md, line 251 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUEOggF4cPAKEO7Zpyd:-MUEVsQ6-8SZINpIv1da:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/5ae1701b5aafbca60227eb2ef822af3235d73949/README.md#L251)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> ### `npm run fmt-backend`
> Automatically format the C# source files in the backend.
> ### `npm run lint`
> Runs ESLint on the codebase to detect code problems that should be fixed.
> ### `npm run fmt-frontend`
> Auto-format frontend code in the `src` folder.
> ### `npm run build`
> ...
> ### `npm run import-sem-doms`
> ```
These five commands should  \### -> \#### to match the restructure. And unless they are meant to be under the new `### Running the Automated Tests` heading, they need their own section heading that can be added to the new ToC.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-23 15:45 UTC, imnasnainaec requested changes
> Reviewed 2 of 22 files at r1, 2 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1031)* status: 10 of 31 files reviewed, 3 unresolved discussions (waiting on @jmgrady)

___
*[README.md, line 251 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUEOggF4cPAKEO7Zpyd:-MUEYw13AIbhCu01nmaB:bhb1gdg) ([raw file](https://github.com/sillsdev/thecombine/blob/5ae1701b5aafbca60227eb2ef822af3235d73949/README.md#L251)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`npm run build` and onward don't seem to fit under "Running the Automated Tests".
___
*[deploy/roles/combine_maintenance/templates/combine-backup.j2, line 49 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUEYBL20AuSeZYyB_F2:-MUEYBL20AuSeZYyB_F3:b-2zqj1u) ([raw file](https://github.com/sillsdev/thecombine/blob/02dfcaff253f2677bdbc45d6c3d50fa67e444327/deploy/roles/combine_maintenance/templates/combine-backup.j2#L49)):*
> ```
> step=1
> echo_verbose "${step}. ..."
> ```
`step=0` and `print_step`?
___
*[deploy/roles/combine_maintenance/templates/combine-restore.j2, line 56 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUEYYhI9gzV30IfZMQb:-MUEYYhI9gzV30IfZMQc:b-a0lrxf) ([raw file](https://github.com/sillsdev/thecombine/blob/02dfcaff253f2677bdbc45d6c3d50fa67e444327/deploy/roles/combine_maintenance/templates/combine-restore.j2#L56)):*
> ```django
>   shift
> done
> ```

Don't you need to set `step=0` here before the first `print_step`?
___
*[deploy/roles/combine_maintenance/templates/combine-restore.j2, line 161 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUEXvUW3dRFf17i3UCO:-MUEXvUW3dRFf17i3UCP:b-gsbynt) ([raw file](https://github.com/sillsdev/thecombine/blob/02dfcaff253f2677bdbc45d6c3d50fa67e444327/deploy/roles/combine_maintenance/templates/combine-restore.j2#L161)):*
> ```
> echo_verbose "10. ...
> ```
`print_step`?


<!-- Sent from Reviewable.io -->

2021-02-23 15:52 UTC, imnasnainaec requested changes
> Reviewed 1 of 22 files at r1, 1 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1031)* status: 12 of 31 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

___
*[deploy/roles/combine_maintenance/templates/combine-backup.j2, line 49 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUEYBL20AuSeZYyB_F2:-MUEZzl531Abc-1CQpe_:beb33li) ([raw file](https://github.com/sillsdev/thecombine/blob/02dfcaff253f2677bdbc45d6c3d50fa67e444327/deploy/roles/combine_maintenance/templates/combine-backup.j2#L49)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> step=1
> echo_verbose "${step}. ..."
> ```
`step=0` and `print_step`?
</blockquote></details>

... or rather, just `print_step` since `step` is defined in `combine-env.j2`?
___
*[deploy/roles/combine_maintenance/templates/combine-restore.j2, line 56 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUEYYhI9gzV30IfZMQb:-MUE_Rj80rqJFgkIoa9g:b6jn2er) ([raw file](https://github.com/sillsdev/thecombine/blob/02dfcaff253f2677bdbc45d6c3d50fa67e444327/deploy/roles/combine_maintenance/templates/combine-restore.j2#L56)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Don't you need to set `step=0` here before the first `print_step`?
</blockquote></details>

Never mind, I see it defined in `combine-env.j2`.


<!-- Sent from Reviewable.io -->

2021-02-23 19:15 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1031)* status: 12 of 31 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[README.md, line 251 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUEOggF4cPAKEO7Zpyd:-MUFHuGfCQqeSAKvN1gr:b-5j0euu) ([raw file](https://github.com/sillsdev/thecombine/blob/5ae1701b5aafbca60227eb2ef822af3235d73949/README.md#L251)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`npm run build` and onward don't seem to fit under "Running the Automated Tests".
</blockquote></details>

Done.
I moved `npm run build` and `npm run analyze` to the _Running in Development_ section and I created a new section titled _Import Semantic Domains_
___
*[deploy/roles/combine_maintenance/templates/combine-backup.j2, line 49 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUEYBL20AuSeZYyB_F2:-MUFIeMJ5j6vLxMmEGDz:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/02dfcaff253f2677bdbc45d6c3d50fa67e444327/deploy/roles/combine_maintenance/templates/combine-backup.j2#L49)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

... or rather, just `print_step` since `step` is defined in `combine-env.j2`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-24 00:57 UTC, imnasnainaec reviewed
> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1031)* status: 13 of 31 files reviewed, 3 unresolved discussions (waiting on @jmgrady)

___
*[deploy/roles/combine_maintenance/files/maint_utils.py, line 69 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUGXVk-4UWxgFbf2vmD:-MUGXVk-4UWxgFbf2vmE:bskknx0) ([raw file](https://github.com/sillsdev/thecombine/blob/297b14ca201d3c87a0be5d5742fba58298a73fc7/deploy/roles/combine_maintenance/files/maint_utils.py#L69)):*
Does this one not need 
> ```
> 
> if __name__ == "__main__":
>     main()
> ```
at the end?
___
*[deploy/roles/combine_maintenance/templates/combine-backup.j2, line 49 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUEYBL20AuSeZYyB_F2:-MUGWDtu7BYXtizoehJr:b-suzn1a) ([raw file](https://github.com/sillsdev/thecombine/blob/02dfcaff253f2677bdbc45d6c3d50fa67e444327/deploy/roles/combine_maintenance/templates/combine-backup.j2#L49)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`step=1` is still defined here. Is that not superfluous?
___
*[deploy/roles/combine_maintenance/templates/combine-restore.j2, line 136 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUGVWdMAS4MlCznLGxj:-MUGVWdMAS4MlCznLGxk:bycexxy) ([raw file](https://github.com/sillsdev/thecombine/blob/297b14ca201d3c87a0be5d5742fba58298a73fc7/deploy/roles/combine_maintenance/templates/combine-restore.j2#L136)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> print_step "Start up just the backend and the database."
> /usr/local/bin/docker-compose up --detach database backend
> 
> 
> ```
</details>

I see docker login has been removed--no longer necessary, I assume.
There is a double `Enter` between this step and the next.
___
*[deploy/roles/create_admin_user/tasks/main.yml, line 11 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUGWugZ-GxqxEvmI2SA:-MUGWug_BLkP2CaoJ9bZ:b-r8bn2n) ([raw file](https://github.com/sillsdev/thecombine/blob/297b14ca201d3c87a0be5d5742fba58298a73fc7/deploy/roles/create_admin_user/tasks/main.yml#L11)):*
> ```
>     "docker-compose run -e COMBINE_ADMIN_USERNAME={{ combine_admin_username }} \
>     -e COMBINE_ADMIN_PASSWORD=\"{{ combine_admin_password }}\" \
>     -e COMBINE_ADMIN_EMAIL=\"{{ combine_admin_email }}\" backend"
> ```
Why are there quotes around the password and email, but not the username?


<!-- Sent from Reviewable.io -->

2021-02-24 01:08 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1031)* status: 13 of 31 files reviewed, 3 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

___
*[deploy/roles/combine_maintenance/files/maint_utils.py, line 69 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUGXVk-4UWxgFbf2vmD:-MUGY4vN-O9YA91fg8OO:bf4gyo9) ([raw file](https://github.com/sillsdev/thecombine/blob/297b14ca201d3c87a0be5d5742fba58298a73fc7/deploy/roles/combine_maintenance/files/maint_utils.py#L69)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Does this one not need 
> ```
> 
> if __name__ == "__main__":
>     main()
> ```
at the end?
</blockquote></details>

No, it does not.  It does not have its own function - it is a collection of utility functions that can be included in the other python scripts.
___
*[deploy/roles/combine_maintenance/templates/combine-backup.j2, line 49 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUEYBL20AuSeZYyB_F2:-MUGYseP3M8AlOwfG2yj:b-3xod1d) ([raw file](https://github.com/sillsdev/thecombine/blob/02dfcaff253f2677bdbc45d6c3d50fa67e444327/deploy/roles/combine_maintenance/templates/combine-backup.j2#L49)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`step=1` is still defined here. Is that not superfluous?
</blockquote></details>

Done.
I hate it when I do stuff like that!  I need to find a way to encapsulate that in `combine-env`!
___
*[deploy/roles/combine_maintenance/templates/combine-restore.j2, line 136 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUGVWdMAS4MlCznLGxj:-MUGZ4fMDQqkrp0ck4Ux:b3gngfg) ([raw file](https://github.com/sillsdev/thecombine/blob/297b14ca201d3c87a0be5d5742fba58298a73fc7/deploy/roles/combine_maintenance/templates/combine-restore.j2#L136)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> print_step "Start up just the backend and the database."
> /usr/local/bin/docker-compose up --detach database backend
> 
> 
> ```
I see docker login has been removed--no longer necessary, I assume.
There is a double `Enter` between this step and the next.
</blockquote></details>

Correct.  It is not pulling the images (the backup/restore should stick to that and not update the software).
Fixed the double `Enter`
___
*[deploy/roles/create_admin_user/tasks/main.yml, line 11 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUGWugZ-GxqxEvmI2SA:-MUGZbC19-Wt9oUZkA0U:bw9gglj) ([raw file](https://github.com/sillsdev/thecombine/blob/297b14ca201d3c87a0be5d5742fba58298a73fc7/deploy/roles/create_admin_user/tasks/main.yml#L11)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>     "docker-compose run -e COMBINE_ADMIN_USERNAME={{ combine_admin_username }} \
>     -e COMBINE_ADMIN_PASSWORD=\"{{ combine_admin_password }}\" \
>     -e COMBINE_ADMIN_EMAIL=\"{{ combine_admin_email }}\" backend"
> ```
Why are there quotes around the password and email, but not the username?
</blockquote></details>

Because the username is not expected to contain characters that would be misinterpreted by the shell, e.g. `(*=` etc.  There would be no harm in add the quotes though so  I will add them.


<!-- Sent from Reviewable.io -->

2021-02-24 11:35 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1031)* status: 13 of 31 files reviewed, 3 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

___
*[deploy/roles/combine_maintenance/files/maint_utils.py, line 69 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUGXVk-4UWxgFbf2vmD:-MUImxEr8AjH-ugioDua:b-so3g45) ([raw file](https://github.com/sillsdev/thecombine/blob/297b14ca201d3c87a0be5d5742fba58298a73fc7/deploy/roles/combine_maintenance/files/maint_utils.py#L69)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

No, it does not.  It does not have its own function - it is a collection of utility functions that can be included in the other python scripts.
</blockquote></details>

I just changed the Ansible role so that when `maint_utils.py` is installed, the `executable` bit is not set.  It might help to explain some thing about the change to the role since the solution was not obvious at first.  The Python scripts are installed by the following task
```
- name: install additional maintenance scripts
  copy:
    src: "{{ item.name }}"
    dest: "{{ combine_app_dir }}/bin/{{ item.name }}"
    owner: "{{ combine_user }}"
    group: "{{ combine_group }}"
    mode: 0{{ item.mode }}
  with_items:
    - name: rm_project.py
      mode: 755
    - name: add_user_to_proj.py
      mode: 755
    - name: make_user_admin.py
      mode: 755
    - name: maint_utils.py
      mode: 644
```
The reason that the `0` to indicate an octal value is not part of the mode definition in the list is because when we specify to set the `mode` to `{{ item.mode }}` Ansible complains that values that start with a Jinja2 template variable but be in quotes but when we do that, we get an error that the `mode` is being set to a string value instead of an octal value.  By starting the `mode` value with `0`, we indicate the value is an octal value and can then use the Jinja2 template variable to have the actual octal value.


<!-- Sent from Reviewable.io -->

2021-02-24 11:44 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1031)* status: 13 of 31 files reviewed, 3 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

___
*[deploy/roles/combine_maintenance/files/maint_utils.py, line 69 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUGXVk-4UWxgFbf2vmD:-MUIpirL1Z8jpQMd7h8g:ban5wm3) ([raw file](https://github.com/sillsdev/thecombine/blob/297b14ca201d3c87a0be5d5742fba58298a73fc7/deploy/roles/combine_maintenance/files/maint_utils.py#L69)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

I just changed the Ansible role so that when `maint_utils.py` is installed, the `executable` bit is not set.  It might help to explain some thing about the change to the role since the solution was not obvious at first.  The Python scripts are installed by the following task
```
- name: install additional maintenance scripts
  copy:
    src: "{{ item.name }}"
    dest: "{{ combine_app_dir }}/bin/{{ item.name }}"
    owner: "{{ combine_user }}"
    group: "{{ combine_group }}"
    mode: 0{{ item.mode }}
  with_items:
    - name: rm_project.py
      mode: 755
    - name: add_user_to_proj.py
      mode: 755
    - name: make_user_admin.py
      mode: 755
    - name: maint_utils.py
      mode: 644
```
The reason that the `0` to indicate an octal value is not part of the mode definition in the list is because when we specify to set the `mode` to `{{ item.mode }}` Ansible complains that values that start with a Jinja2 template variable but be in quotes but when we do that, we get an error that the `mode` is being set to a string value instead of an octal value.  By starting the `mode` value with `0`, we indicate the value is an octal value and can then use the Jinja2 template variable to have the actual octal value.
</blockquote></details>

Ignore the comment above except for the first sentence: _I just changed the Ansible role so that when maint_utils.py is installed, the executable bit is not set._

I had misread a previous error message and found that:
```
    ...
    mode: "{{ item.mode }}"
   ...
  with_items:
    - name: rm_project.py
      mode: "0755"
    ...
```
also works and is more readable.


<!-- Sent from Reviewable.io -->

2021-02-24 13:18 UTC, imnasnainaec reviewed
> Reviewed 1 of 22 files at r1, 1 of 9 files at r3, 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1031)* status: 16 of 31 files reviewed, 4 unresolved discussions (waiting on @jmgrady)

___
*[deploy/roles/combine_install/tasks/main.yml, line 8 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUJA1TP57fbqjgITaMf:-MUJA1TP57fbqjgITaMg:bnqpvwf) ([raw file](https://github.com/sillsdev/thecombine/blob/6e83f8b6e17267d69ad5c993eec9620e8a3d7e9e/deploy/roles/combine_install/tasks/main.yml#L8)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> # Starts the Combine on a new machine through the following
> # tasks:
> #  - create .env file to specify the image tag for the docker containers
> #  - pulls the docker images
> #  - creates the 'admin' user for TheCombine
> #  - starts TheCombine application
> ```
</details>

This task list doesn't appear to match up with the tasks below.
___
*[deploy/roles/combine_maintenance/files/maint_utils.py, line 55 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUJAhv12Wkw3nPaXxb1:-MUJAhv12Wkw3nPaXxb2:b24y7qd) ([raw file](https://github.com/sillsdev/thecombine/blob/6e83f8b6e17267d69ad5c993eec9620e8a3d7e9e/deploy/roles/combine_maintenance/files/maint_utils.py#L55)):*
> ```Python
>     """Look up the MongoDB ObjectId for the project from the Project Name."""
>     results = db_cmd(f'db.ProjectsCollection.findOne({{ name: "{project_name}"}},{{ name: 1}})')
>     if results is not None:
> ```

Why do we not check `and "_id" in results` here but we do below?
___
*[deploy/roles/create_admin_user/tasks/main.yml, line 14 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUJ9Fl8-lsSKbJwIHaL:-MUJ9Fl8-lsSKbJwIHaM:bt4stjb) ([raw file](https://github.com/sillsdev/thecombine/blob/6e83f8b6e17267d69ad5c993eec9620e8a3d7e9e/deploy/roles/create_admin_user/tasks/main.yml#L14)):*
> ```YAML
>   args:
>     chdir: "{{ combine_app_dir }}"
> ```

I see no command to shut down the backend before relaunching the containers, but I guess that's not necessary.
___
*[docs/deploy/README.md, line 111 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUJ8t3-DxhCimyDnVhT:-MUJ8t3-DxhCimyDnVhU:bejcfou) ([raw file](https://github.com/sillsdev/thecombine/blob/6e83f8b6e17267d69ad5c993eec9620e8a3d7e9e/docs/deploy/README.md#L111)):*
> ```
>   group in the inventory file, e.g. `qa`
> ```
.


<!-- Sent from Reviewable.io -->

2021-02-24 14:10 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1031)* status: 16 of 31 files reviewed, 3 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

___
*[deploy/roles/combine_install/tasks/main.yml, line 8 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUJA1TP57fbqjgITaMf:-MUJGn5j8sJRTFRnU0Yi:b-dcp7in) ([raw file](https://github.com/sillsdev/thecombine/blob/6e83f8b6e17267d69ad5c993eec9620e8a3d7e9e/deploy/roles/combine_install/tasks/main.yml#L8)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> # Starts the Combine on a new machine through the following
> # tasks:
> #  - create .env file to specify the image tag for the docker containers
> #  - pulls the docker images
> #  - creates the 'admin' user for TheCombine
> #  - starts TheCombine application
> ```
This task list doesn't appear to match up with the tasks below.
</blockquote></details>

You are correct.  That list is what `playbook_install.yml` does.  This role only does the first two items.  I have fixed the comment and added a similar description to the `create_admin_user` role.
___
*[deploy/roles/combine_maintenance/files/maint_utils.py, line 55 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUJAhv12Wkw3nPaXxb1:-MUJIssv7q4qq98vnSpR:b-17pcxo) ([raw file](https://github.com/sillsdev/thecombine/blob/6e83f8b6e17267d69ad5c993eec9620e8a3d7e9e/deploy/roles/combine_maintenance/files/maint_utils.py#L55)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Why do we not check `and "_id" in results` here but we do below?
</blockquote></details>

The thinking was that in the `get_user_id` function, if the user is specified by email address, then there will be no `_id` field in the results.  In fact, there will be no results so that is effectively dead code.  I can probably remove the test for `_id` in results since there should not be any documents in the UsersCollection with an `_id`.

I have just verified that if I specify the user with the email address, then the `results` from the first look up is `None` - the check for `_id` in the results can be removed.
___
*[deploy/roles/create_admin_user/tasks/main.yml, line 14 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUJ9Fl8-lsSKbJwIHaL:-MUJKuhNBY5_mts76ZVa:b-m7kd0a) ([raw file](https://github.com/sillsdev/thecombine/blob/6e83f8b6e17267d69ad5c993eec9620e8a3d7e9e/deploy/roles/create_admin_user/tasks/main.yml#L14)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I see no command to shut down the backend before relaunching the containers, but I guess that's not necessary.
</blockquote></details>

The way the backend is written, if `COMBINE_ADMIN_USERNAME` is defined, the backend is called as `dotnet BackendFramework.dll create-admin-username=$COMBINE_ADMIN_USERNAME` (from `./Backend/launch.sh`).  When it is called this way, the admin user is created and the backend exits (after which, the `docker-compose run` command will exit.  I believe that the reason for doing this is so that the backend is not running in production mode with the admin password in memory in an environment variable.


<!-- Sent from Reviewable.io -->

2021-02-24 14:23 UTC, imnasnainaec reviewed
> Reviewed 1 of 22 files at r1, 1 of 9 files at r3, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1031)* status: 21 of 31 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

___
*[deploy/roles/combine_maintenance/files/make_user_admin.py, line 38 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUJGMaj2PPzMl3lEiZA:-MUJGMaj2PPzMl3lEiZB:b8mhh89) ([raw file](https://github.com/sillsdev/thecombine/blob/6e83f8b6e17267d69ad5c993eec9620e8a3d7e9e/deploy/roles/combine_maintenance/files/make_user_admin.py#L38)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>             result = db_cmd(
>                 f'db.UsersCollection.updateOne({{ _id : ObjectId("{user_id}")}},'
>                 "{ $set: { isAdmin : true }})"
>             )
>             if result is not None and args.verbose and result["acknowledged"]:
>                 print(f"{user} is a Site Admin.")
> ```
</details>

Isn't `result` a `subprocess.CompletedProcess`? I don't see anything about `"acknowledged"` in the docs: https://docs.python.org/3/library/subprocess.html#subprocess.CompletedProcess


<!-- Sent from Reviewable.io -->

2021-02-24 15:14 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1031)* status: 21 of 31 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

___
*[deploy/roles/combine_maintenance/files/make_user_admin.py, line 38 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUJGMaj2PPzMl3lEiZA:-MUJZxLNC6lWjrMhZUsb:blyt0g3) ([raw file](https://github.com/sillsdev/thecombine/blob/6e83f8b6e17267d69ad5c993eec9620e8a3d7e9e/deploy/roles/combine_maintenance/files/make_user_admin.py#L38)):*
`result` is a JSON structure.  `db_cmd` calls the subprocess but then:
 ```
    result_str = object_id_to_str(db_results.stdout)
    if result_str:
        result_dict = json.loads(result_str)
        return result_dict
```
`acknowledged` is set to true in the results of a successful update:
```
> db.UsersCollection.updateOne({ _id: ObjectId("5efe57d4c92ae778d4747030")},{ $set: { isAdmin : true }})
{ "acknowledged" : true, "matchedCount" : 1, "modifiedCount" : 1 }
> 
```


<!-- Sent from Reviewable.io -->

2021-02-24 16:04 UTC, imnasnainaec reviewed
> Reviewed 1 of 22 files at r1, 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1031)* status: 23 of 31 files reviewed, all discussions resolved (waiting on @jmgrady)



<!-- Sent from Reviewable.io -->

2021-02-24 16:23 UTC, imnasnainaec reviewed
> Reviewed 1 of 4 files at r2, 2 of 9 files at r3, 2 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1031)* status: 28 of 31 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[deploy/playbook_install.yml, line 30 at r7](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUJqSsF2uRw90ytJJPw:-MUJqSsG8xGBeWE6kxwV:b-2d08uh) ([raw file](https://github.com/sillsdev/thecombine/blob/a32ce4c79f64c73fbd10deb17e6789fe2edff414/deploy/playbook_install.yml#L30)):*
> ```
>     #   -e "ansible_credentials=_test_aws.yml"
>     - "vars/{{ aws_credentials | default('aws.yml',true) }}"
> ```
`ansible_credentials` or `aws_credentials`?


<!-- Sent from Reviewable.io -->

2021-02-24 16:51 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1031)* status: 27 of 31 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[deploy/playbook_install.yml, line 30 at r7](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUJqSsF2uRw90ytJJPw:-MUJwd-Q8mbmhd6JRlgJ:b-xot2ly) ([raw file](https://github.com/sillsdev/thecombine/blob/a32ce4c79f64c73fbd10deb17e6789fe2edff414/deploy/playbook_install.yml#L30)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>     #   -e "ansible_credentials=_test_aws.yml"
>     - "vars/{{ aws_credentials | default('aws.yml',true) }}"
> ```
`ansible_credentials` or `aws_credentials`?
</blockquote></details>

Should be aws_credentials in the comment - here and in `playbook_target_setup.yml`.  Copy & paste is a good way to proliferate errors.


<!-- Sent from Reviewable.io -->

2021-02-24 17:45 UTC, imnasnainaec reviewed
> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1031)* status: 29 of 31 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[deploy/roles/combine_maintenance/files/add_user_to_proj.py, line 13 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUK7m1r3O3T2jE1ND0Y:-MUK7m1r3O3T2jE1ND0Z:bb600af) ([raw file](https://github.com/sillsdev/thecombine/blob/31280f378cfcfafb7880fa25388af5aa8409f5d6/deploy/roles/combine_maintenance/files/add_user_to_proj.py#L13)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
> Assumptions:
>   - The Javascript is run with the following variables set:
>       - user: user's username or e-mail address
>       - projName: name of the project to which the user is
>         to be added
>       - isAdmin: set to true/false to determine the user permissions.
>         If set to "True", the permissions are set to [5,4,3,2,1], otherwise
>         they are set to [3,2,1]
> ```
</details>

Are these assumptions still true? It looks like they have been replaced with python arguments. (Same question for `rm_project.py`.)


<!-- Sent from Reviewable.io -->

2021-02-24 19:08 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1031)* status: 29 of 31 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[deploy/roles/combine_maintenance/files/add_user_to_proj.py, line 13 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUK7m1r3O3T2jE1ND0Y:-MUKQBjlB80hUMPw6XXI:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/31280f378cfcfafb7880fa25388af5aa8409f5d6/deploy/roles/combine_maintenance/files/add_user_to_proj.py#L13)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> Assumptions:
>   - The Javascript is run with the following variables set:
>       - user: user's username or e-mail address
>       - projName: name of the project to which the user is
>         to be added
>       - isAdmin: set to true/false to determine the user permissions.
>         If set to "True", the permissions are set to [5,4,3,2,1], otherwise
>         they are set to [3,2,1]
> ```
Are these assumptions still true? It looks like they have been replaced with python arguments. (Same question for `rm_project.py`.)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-24 19:52 UTC, imnasnainaec reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1031)* status: 29 of 31 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

___
*[deploy/roles/combine_maintenance/files/add_user_to_proj.py, line 104 at r9](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUKaKTI3ysDExdyJNKn:-MUKaKTI3ysDExdyJNKo:bfi1bnm) ([raw file](https://github.com/sillsdev/thecombine/blob/a8dbc7b0ddaaf53b90262c0fa61a8772ef95b72c/deploy/roles/combine_maintenance/files/add_user_to_proj.py#L104)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>         if insert_result is not None:
>             #      b. add the new role to the user's document in the UsersCollection
>             user_role_id = insert_result["insertedId"]
>             select_user = f'{{ _id: ObjectId("{user_id}")}}'
>             update_user = f'{{ $set : {{"projectRoles.{proj_id}" : "{user_role_id}" }}}}'
>             add_role_result = db_cmd(f"db.UsersCollection.updateOne({select_user}, {update_user})")
>             if add_role_result is None:
>                 print(f"Could not add {args.user} to {args.project}.")
>                 sys.exit(3)
> ```
</details>

Could this outer if benefit from a failure case similar to the inner if?
___
*[deploy/roles/combine_maintenance/files/rm_project.py, line 78 at r9](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUKZq1HAb15sFDdUiOl:-MUKZq1HAb15sFDdUiOm:bk87tza) ([raw file](https://github.com/sillsdev/thecombine/blob/a8dbc7b0ddaaf53b90262c0fa61a8772ef95b72c/deploy/roles/combine_maintenance/files/rm_project.py#L78)):*
> ```
> run_docker_cmd("backend", ["rm", "-rf", f"/home/app/.CombineFiles/{project_id}"])
> ```
Since this could delete the whole `.CombineFiles` folder if `project_id=""`, perhaps the above check `if project_id is not None` should have a check for the empty string added to it, just in case.


<!-- Sent from Reviewable.io -->

2021-02-24 20:20 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1031)* status: 29 of 31 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[deploy/roles/combine_maintenance/files/add_user_to_proj.py, line 104 at r9](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUKaKTI3ysDExdyJNKn:-MUKdq4x5K71zfBavM4J:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/a8dbc7b0ddaaf53b90262c0fa61a8772ef95b72c/deploy/roles/combine_maintenance/files/add_user_to_proj.py#L104)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>         if insert_result is not None:
>             #      b. add the new role to the user's document in the UsersCollection
>             user_role_id = insert_result["insertedId"]
>             select_user = f'{{ _id: ObjectId("{user_id}")}}'
>             update_user = f'{{ $set : {{"projectRoles.{proj_id}" : "{user_role_id}" }}}}'
>             add_role_result = db_cmd(f"db.UsersCollection.updateOne({select_user}, {update_user})")
>             if add_role_result is None:
>                 print(f"Could not add {args.user} to {args.project}.")
>                 sys.exit(3)
> ```
Could this outer if benefit from a failure case similar to the inner if?
</blockquote></details>

Done.
___
*[deploy/roles/combine_maintenance/files/rm_project.py, line 78 at r9](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUKZq1HAb15sFDdUiOl:-MUKexK49T3kgL3A2MAt:bj9hv3d) ([raw file](https://github.com/sillsdev/thecombine/blob/a8dbc7b0ddaaf53b90262c0fa61a8772ef95b72c/deploy/roles/combine_maintenance/files/rm_project.py#L78)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> run_docker_cmd("backend", ["rm", "-rf", f"/home/app/.CombineFiles/{project_id}"])
> ```
Since this could delete the whole `.CombineFiles` folder if `project_id=""`, perhaps the above check `if project_id is not None` should have a check for the empty string added to it, just in case.
</blockquote></details>

I don't think that is possible.  The `project_id` is set to the return value of `get_project_id()` which will be an `_id` field from the database, or `None` or `get_project_id()` will call `sys.exit()`.  Even so, I can change the test to `if project_id:`.  That should be false if the `project_id` is `None` or empty.


<!-- Sent from Reviewable.io -->

2021-02-24 20:27 UTC, imnasnainaec reviewed
> Reviewed 1 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1031)* status: 30 of 31 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[deploy/roles/combine_maintenance/files/add_user_to_proj.py, line 12 at r10](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUKiE3OAVyqqV25Z872:-MUKiE3OAVyqqV25Z873:b9mtktp) ([raw file](https://github.com/sillsdev/thecombine/blob/3e538f61a35e0ddb5b5bda538a08b00485a58cb1/deploy/roles/combine_maintenance/files/add_user_to_proj.py#L12)):*
> ```
>  2. Check to see if the user is already in the project.  If he/she is
>     already a member and the --admin argument is used, set the permissions to
>     [5,4,3,2,1], otherwise do nothing.
> ```
I guess this script isn't intended to be used for downgrading a user from admin.


<!-- Sent from Reviewable.io -->

2021-02-24 20:34 UTC, imnasnainaec approved these changes
> Reviewed 1 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1031)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[deploy/roles/combine_maintenance/files/add_user_to_proj.py, line 12 at r10](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUKiE3OAVyqqV25Z872:-MUKjmWxDG2VjCbXnrs2:b-c3tixn) ([raw file](https://github.com/sillsdev/thecombine/blob/3e538f61a35e0ddb5b5bda538a08b00485a58cb1/deploy/roles/combine_maintenance/files/add_user_to_proj.py#L12)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>  2. Check to see if the user is already in the project.  If he/she is
>     already a member and the --admin argument is used, set the permissions to
>     [5,4,3,2,1], otherwise do nothing.
> ```
I guess this script isn't intended to be used for downgrading a user from admin.
</blockquote></details>

And we wouldn't want to accidentally remove an admin privilege, so it's good as is.


<!-- Sent from Reviewable.io -->

2021-02-24 20:40 UTC, merged

2021-02-26 13:42 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/add_user_to_proj.py, line 29 at r10](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUTZo9h5LP4P2gIu83l:-MUTZo9h5LP4P2gIu83m:btymkm7) ([raw file](https://github.com/sillsdev/thecombine/blob/3e538f61a35e0ddb5b5bda538a08b00485a58cb1/deploy/roles/combine_maintenance/files/add_user_to_proj.py#L29)):*
> ```Python
>     """Parse the command line arguments."""
>     parser = argparse.ArgumentParser(
>         description="""Add a user to a project on TheCombine. """
> ```

For consistency, we should use single quoted strings here, e.g. `"Add a user to a project on TheCombine. "`


<!-- Sent from Reviewable.io -->

2021-02-26 13:48 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/add_user_to_proj.py, line 91 at r10](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUT_cjC7GnIt2ZXNBCW:-MUT_cjC7GnIt2ZXNBCX:bfo44pz) ([raw file](https://github.com/sillsdev/thecombine/blob/3e538f61a35e0ddb5b5bda538a08b00485a58cb1/deploy/roles/combine_maintenance/files/add_user_to_proj.py#L91)):*
> ```Python
>         #      a. create a document in the UserRolesCollection,
>         if args.admin:
>             user_permissions = [5, 4, 3, 2, 1]
> ```

I don't think this is strictly necessary, but we could make this more readable if we defined a  Python`enum` that mirrored `UserRole.Permission` in the backend.


```py
@enum.unique
class Permission(enum.Enum):
    WordEntry = 1
    Unused = 2
    ...
```

That way if we ever were to change the permissions it we could do so in a central location rather than having to hunt down the magic integers. It would also run nicely to see something like:

```py
if args.admin:
    user_permissions = [Permission.DeleteEditSettingsAndUsers, Permission.ImportExport, ....]
```


<!-- Sent from Reviewable.io -->

2021-02-26 13:51 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/add_user_to_proj.py, line 109 at r10](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUTaTUzEPCVHkxzbl8a:-MUTaTUzEPCVHkxzbl8b:b1iiuf6) ([raw file](https://github.com/sillsdev/thecombine/blob/3e538f61a35e0ddb5b5bda538a08b00485a58cb1/deploy/roles/combine_maintenance/files/add_user_to_proj.py#L109)):*
> ```Python
>         else:
>             print(f"Could not create role for {args.user} in {args.project}.", file=sys.stderr)
>             sys.exit(4)
> ```

There are 5 different exit codes this script can return. It could make it easier for a new person to quickly see what these mean if we defined an `IntEnum` at the top of the script.

``py
@enum.unique
class ExitCode(enum.IntEnum):
    Success = 0
    CannotFindUser = 1
    ...
```


```py
...
sys.exit(ExitCode.Success)
```


<!-- Sent from Reviewable.io -->

2021-02-26 13:52 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/add_user_to_proj.py, line 109 at r10](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUTaTUzEPCVHkxzbl8a:-MUTavZB0OMyImVhwkcn:b-1akvkp) ([raw file](https://github.com/sillsdev/thecombine/blob/3e538f61a35e0ddb5b5bda538a08b00485a58cb1/deploy/roles/combine_maintenance/files/add_user_to_proj.py#L109)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

There are 5 different exit codes this script can return. It could make it easier for a new person to quickly see what these mean if we defined an `IntEnum` at the top of the script.

``py
@enum.unique
class ExitCode(enum.IntEnum):
    Success = 0
    CannotFindUser = 1
    ...
```


```py
...
sys.exit(ExitCode.Success)
```
</blockquote></details>

(Properly formatted).

```py
@enum.unique
class ExitCode(enum.IntEnum):
    Success = 0
    CannotFindUser = 1
    ...
```

```py
...
sys.exit(ExitCode.Success)
```


<!-- Sent from Reviewable.io -->

2021-02-26 13:53 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/add_user_to_proj.py, line 30 at r10](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUTbBbD8nCX2DCQcNa3:-MUTbBbEBnk57ZoAKyTj:b-m3gj5q) ([raw file](https://github.com/sillsdev/thecombine/blob/3e538f61a35e0ddb5b5bda538a08b00485a58cb1/deploy/roles/combine_maintenance/files/add_user_to_proj.py#L30)):*
> ```Python
>     parser = argparse.ArgumentParser(
>         description="""Add a user to a project on TheCombine. """
>         """The user can be specified by his/her username or """
> ```

Could simplify this sentence to `"The user can be specified by username or email address"`


<!-- Sent from Reviewable.io -->

2021-02-26 14:03 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/make_user_admin.py, line 12 at r10](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUTdZOo33U-6p3xvJWb:-MUTdZOo33U-6p3xvJWc:be9qh6o) ([raw file](https://github.com/sillsdev/thecombine/blob/3e538f61a35e0ddb5b5bda538a08b00485a58cb1/deploy/roles/combine_maintenance/files/make_user_admin.py#L12)):*
> ```Python
>     """Parse the command line arguments."""
>     parser = argparse.ArgumentParser(
>         description="""Make an existing user a site administrator """
> ```

Should use single quotes here for consistency. Python automatically concatenates normal `""` strings that are adjacent within `(  )`


<!-- Sent from Reviewable.io -->

2021-02-26 14:04 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/rm_project.py, line 32 at r10](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUTduz97c7U6xHPw2OH:-MUTduz97c7U6xHPw2OI:b-5olllv) ([raw file](https://github.com/sillsdev/thecombine/blob/3e538f61a35e0ddb5b5bda538a08b00485a58cb1/deploy/roles/combine_maintenance/files/rm_project.py#L32)):*
> ```Python
>     # Parse user command line arguments
>     parser = argparse.ArgumentParser(
>         description="""Remove a project from the Combine server. """
> ```

Use single quotes.


<!-- Sent from Reviewable.io -->

2021-02-26 14:04 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/rm_project.py, line 30 at r10](https://reviewable.io/reviews/sillsdev/thecombine/1031#-MUTdyqJ25R0n1qpBpUF:-MUTdyqJ25R0n1qpBpUG:bym4gzv) ([raw file](https://github.com/sillsdev/thecombine/blob/3e538f61a35e0ddb5b5bda538a08b00485a58cb1/deploy/roles/combine_maintenance/files/rm_project.py#L30)):*
> ```Python
> def parse_args() -> argparse.Namespace:
>     """Define command line arguments for parser."""
>     # Parse user command line arguments
> ```

This comment could probably be removed.


<!-- Sent from Reviewable.io -->