Backup restore for development
sillsdev/TheCombine pull request #1084
Opened 2021-03-18 21:11 UTC by jmgrady

Port the backup and restore scripts to Python in order to be usable in development environments:
 - removes Jinja2 templating of the scripts
 - uses a cross-platform scripting language
Note that a Jinja2 template is used to generate the configuration file for the scripts.  The configuration file is a JSON file.

Closes #860

2021-03-19 15:25 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_backup.py, line 27 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWA4a6HApfd9sYmc-FA:-MWA4a6HApfd9sYmc-FB:b-83jvp3) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_backup.py#L27)):*
> ```Python
>         "--verbose", action="store_true", help="Print intermediate values to aid in debugging"
>     )
>     default_config = Path(os.path.dirname(sys.argv[0])) / "backup_conf.json"
> ```

I think we could simplify this using `Path(..).parent` so that we don't have to mix in `os.path.dirname`. I usually prefer using purely `pathlib` functionality rather than `os.path`, which is as older API.


<!-- Sent from Reviewable.io -->

2021-03-19 15:27 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_backup.py, line 28 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWA4sVF7STjxe54fV32:-MWA4sVF7STjxe54fV33:br5lf3x) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_backup.py#L28)):*
> ```Python
>     )
>     default_config = Path(os.path.dirname(sys.argv[0])) / "backup_conf.json"
>     parser.add_argument("--config", help="backup configuration file.", default=default_config)
> ```

`argparse` should allow you to avoid ever having to access `sys.argv` directly. You could add a positional argument here (so `argparse` will validate automatically that one is passed in): https://docs.python.org/3/library/argparse.html#example

Something like:

```py
parser.add_argument('config', type=Path)
```


<!-- Sent from Reviewable.io -->

2021-03-19 15:32 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_backup.py, line 63 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWA5mFC3nQFmhzVC_KK:-MWA5mFC3nQFmhzVC_KL:bdljnk5) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_backup.py#L63)):*
> ```Python
>     args = parse_args()
> 
>     config: Dict[str, str] = json.load(open(args.config))
> ```

Calling `open()` without a `.close()` will leak the file handle (not a huge deal in Python as it will close when process executes, but is a minor "bug".

Since we have a `Path` object, I think the best way to do this is:

```py
json.loads(args.config.read_text())
```

`read_text()` will automatically open and close the file, so no risk of leaks.

https://docs.python.org/3/library/pathlib.html#pathlib.Path.read_text


<!-- Sent from Reviewable.io -->

2021-03-19 15:37 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_backup.py, line 170 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWA6qJW1TrY37Wa7jaz:-MWA6qJW1TrY37Wa7jb-:b-u8pl9q) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_backup.py#L170)):*
> ```Python
>     os.chdir(backup_dir)
> 
>     tar = tarfile.open(backup_file, "x:gz")
> ```

This can be made cleaner using a context manager (`with`)

```
with tarfile.open(backup_file, "x:gz") as tar:
    ...
```

Context managers automatically close the files they open when the block is exited.

https://docs.python.org/3/library/tarfile.html#examples


<!-- Sent from Reviewable.io -->

2021-03-19 15:39 UTC, johnthagen commented
___
*[tox.ini, line 27 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWA7vrj7Rm6YIWITXja:-MWA7vrj7Rm6YIWITXjb:bwlv403) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/tox.ini#L27)):*
> ```INI
>     -r{toxinidir}/dev-requirements.txt
> commands =
>     mypy certmgr/scripts deploy scripts --exclude 'scripts/(add_user_to_proj|combine_backup|combine_restore|maint_utils|make_user_admin|rm_project|script_step).py$'
> ```

If we can manage to make these scripts work independent of the current working directory (like with `Path(__file__).resolve()`) then we may be able to avoid needing to copy, exclude, .gitignore all of them.


<!-- Sent from Reviewable.io -->

2021-03-19 15:42 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_backup.py, line 135 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWA8RPVDAbopmQdhBvd:-MWA8RPVDAbopmQdhBve:b1werx4) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_backup.py#L135)):*
> ```Python
>         False,
>     )
>     if check_backup_results.returncode != 0:
> ```

Can this branch ever be true? `run_cmd` defaults to `check_results=True` so wouldn't that already abort for non-`0` exits?


<!-- Sent from Reviewable.io -->

2021-03-19 15:44 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/script_step.py, line 13 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWA8taM0ZQ9kPVAFUaN:-MWA8taM0ZQ9kPVAFUaO:b-hn2kgd) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/script_step.py#L13)):*
> ```Python
>     def print(self, verbose: bool, descr: str) -> None:
>         """Print the step number with its description and bump the step number."""
>         if verbose:
> ```

Not required, but you could consider leveraging the built in `logging` module.

It has support for controlling verbosity/where logs are output to built in. Might be worth just taking a look. We might be able to avoid passing `verbose` around everywhere if we simple configure the logging level once at the beginning of these scripts.

https://docs.python.org/3/library/logging.html


<!-- Sent from Reviewable.io -->

2021-03-19 15:46 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_backup.py, line 171 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWA9OfY-WgnqhDwrcvq:-MWA9OfY-WgnqhDwrcvr:b-4j150j) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_backup.py#L171)):*
> ```Python
> 
>     tar = tarfile.open(backup_file, "x:gz")
>     for name in [config["backend_files_subdir"], config["db_files_subdir"]]:
> ```

Not a big deal, but I think the general practice in Python is to use `tuple`s for this kind of anonymous temporary iterable. They are immutable which is expressing the kind of thing you are doing here.

```py
for name in (config["backend_files_subdir"], config["db_files_subdir"]):
```


<!-- Sent from Reviewable.io -->

2021-03-19 15:50 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/script_step.py, line 11 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWAA1EKEYdO8tjpKmub:-MWAA1EKEYdO8tjpKmuc:b-bhqtbo) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/script_step.py#L11)):*
> ```Python
>         self.step_num = 1
> 
>     def print(self, verbose: bool, descr: str) -> None:
> ```

Not a big deal, but I'd generally expect the `verbose` argument to come after the `desc` argument, which is more of the meat of the function. That would also let you, if you wanted, provide a default to `verbose`.

```py
step.print("Hello!", verbose=True)
```

vs

```py
step.print(False, "Hello!")
```


<!-- Sent from Reviewable.io -->

2021-03-19 15:50 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_restore.py, line 28 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWAAYN31e43hmUHFA5_:-MWAAYN31e43hmUHFA5a:b-tqb74y) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_restore.py#L28)):*
> ```Python
>     )
>     parser.add_argument(
>         "--clean", action="store_true", help="Cleanout Backend files before restoring from backup"
> ```

Cleanout -> clean out


<!-- Sent from Reviewable.io -->

2021-03-19 15:51 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_restore.py, line 36 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWAAhEJ1Wgr1PKh2y3u:-MWAAhEJ1Wgr1PKh2y3v:bkj7vyl) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_restore.py#L36)):*
> ```Python
> 
> 
> def rm_backup_files(path_list: List[Path]) -> None:
> ```

Is this function copied verbatim from `combine_backup.py`? Could it be defined once in a singular place?


<!-- Sent from Reviewable.io -->

2021-03-19 15:52 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_restore.py, line 46 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWAAtbi0fDS1YnSfsHY:-MWAAtbi0fDS1YnSfsHZ:b-trj55u) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_restore.py#L46)):*
> ```Python
> 
> 
> def run_cmd(cmd: List[str], check_results: bool = True) -> subprocess.CompletedProcess:
> ```

This function also looks identical to one in `combine_backup.py`. Can we share a common implementation?


<!-- Sent from Reviewable.io -->

2021-03-19 15:53 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_restore.py, line 76 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWAB4OJEzanC0VjULN8:-MWAB4OJEzanC0VjULN9:b-hjnuwr) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_restore.py#L76)):*
> ```Python
>     args = parse_args()
> 
>     config: Dict[str, str] = json.load(open(args.config))
> ```

See comment in `combine_backup.py` about how to improve this line.


<!-- Sent from Reviewable.io -->

2021-03-19 15:53 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_restore.py, line 81 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWABBg0Eo7GQIbDtGk4:-MWABBg0Eo7GQIbDtGk5:b4iugzk) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_restore.py#L81)):*
> ```Python
>     step.print(args.verbose, "Prepare for the restore.")
> 
>     restore_file = "combine-backup.tar.gz"
> ```

This special string name is shared between `_restore` and `_backup`. Could it be defined once?


<!-- Sent from Reviewable.io -->

2021-03-19 15:54 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_restore.py, line 95 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWABOCQBxkcccIrhokI:-MWABOCQBxkcccIrhokJ:b-r0lya1) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_restore.py#L95)):*
> ```Python
> 
>     if not restore_dir.exists():
>         restore_dir.mkdir(0o755, True, True)
> ```

To make this more clear, I'd suggest using named arguments:

```py
.mkdir(0o755, parents=True, exist_ok=True)
```


<!-- Sent from Reviewable.io -->

2021-03-19 15:57 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_restore.py, line 120 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWABrFQ3_yK3wYyo_nH:-MWABrFQ3_yK3wYyo_nI:b-afbl0j) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_restore.py#L120)):*
> ```Python
>             )
>             .stdout.strip()
>             .split("\n")[1::]
> ```

Could this be `[1:]`? That is the common way to write a slice (omitting the colon for the `step` if not used).


<!-- Sent from Reviewable.io -->

2021-03-19 15:59 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_restore.py, line 171 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWACPXi2ZPlrULMQd4u:-MWACPXi2ZPlrULMQd4v:b-opt510) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_restore.py#L171)):*
> ```Python
>     step.print(args.verbose, "Unpack the backup.")
>     os.chdir(restore_dir)
>     tar = tarfile.open(restore_file, "r:gz")
> ```

See comment in `combine_backup.py`about how to use a context manager to simplify this code.


<!-- Sent from Reviewable.io -->

2021-03-19 16:00 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_restore.py, line 233 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWACpBw2wNPZvqB2XC1:-MWACpBxEljG33ye18Ub:bmlql31) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_restore.py#L233)):*
> ```Python
>         )
> 
>     be_container = run_cmd(
> ```

What does `be` in `be_container` mean?


<!-- Sent from Reviewable.io -->

2021-03-19 16:02 UTC, johnthagen commented
___
*[scripts/docker_setup.py, line 161 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWAD7BdDJnZ-YNmiUvK:-MWAD7BdDJnZ-YNmiUvL:bgwhq4k) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/scripts/docker_setup.py#L161)):*
> ```Python
> 
>     # Copy maintenance scripts from Ansible role to scripts directory
>     roles_dir = project_dir / "deploy" / "roles" / "combine_maintenance"
> ```

Per other comment, perhaps we can avoid needing to copy if we can make the scripts themselves independent of the current working directory.


<!-- Sent from Reviewable.io -->

2021-03-19 16:02 UTC, johnthagen requested changes
> Reviewed 10 of 13 files at r1, 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1084)* status: all files reviewed, 19 unresolved discussions (waiting on @jmgrady)



<!-- Sent from Reviewable.io -->

2021-03-19 16:06 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1084)* status: all files reviewed, 17 unresolved discussions (waiting on @jmgrady and @johnthagen)

___
*[tox.ini, line 27 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWA7vrj7Rm6YIWITXja:-MWAE9mV2hjwEPp8tM1V:b-a8md7c) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/tox.ini#L27)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

If we can manage to make these scripts work independent of the current working directory (like with `Path(__file__).resolve()`) then we may be able to avoid needing to copy, exclude, .gitignore all of them.
</blockquote></details>

Will do.  I think this is a better approach.
___
*[deploy/roles/combine_maintenance/files/combine_backup.py, line 27 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWA4a6HApfd9sYmc-FA:-MWA7yrGBQdYwWo9lmmQ:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_backup.py#L27)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I think we could simplify this using `Path(..).parent` so that we don't have to mix in `os.path.dirname`. I usually prefer using purely `pathlib` functionality rather than `os.path`, which is as older API.
</blockquote></details>

Done.
___
*[deploy/roles/combine_maintenance/files/combine_backup.py, line 28 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWA4sVF7STjxe54fV32:-MWA6kclEuf5aG_AdFbj:b-3jq3sa) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_backup.py#L28)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

`argparse` should allow you to avoid ever having to access `sys.argv` directly. You could add a positional argument here (so `argparse` will validate automatically that one is passed in): https://docs.python.org/3/library/argparse.html#example

Something like:

```py
parser.add_argument('config', type=Path)
```
</blockquote></details>

My intent was that the user would not need to type in the location of the configuration file but that the `--config` option would allow someone to override it.  This could be handy if someone (i.e. me) wants to have an alternate configuration for a different AWS location for testing.
___
*[deploy/roles/combine_maintenance/files/combine_backup.py, line 63 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWA5mFC3nQFmhzVC_KK:-MWA9LXBCSV6PVWuzOPH:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_backup.py#L63)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Calling `open()` without a `.close()` will leak the file handle (not a huge deal in Python as it will close when process executes, but is a minor "bug".

Since we have a `Path` object, I think the best way to do this is:

```py
json.loads(args.config.read_text())
```

`read_text()` will automatically open and close the file, so no risk of leaks.

https://docs.python.org/3/library/pathlib.html#pathlib.Path.read_text

</blockquote></details>

Done.
___
*[deploy/roles/combine_maintenance/files/combine_backup.py, line 135 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWA8RPVDAbopmQdhBvd:-MWA9S_Y9KvspT2DfvcE:b-7nwfd5) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_backup.py#L135)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Can this branch ever be true? `run_cmd` defaults to `check_results=True` so wouldn't that already abort for non-`0` exits?
</blockquote></details>

I needed to be able to determine if there is a database backup to copy first.  When there is no output from `mongodump`, for example, when the database is empty, the `dump` directory does not exist so the `docker cp ...` fails.  I added a parameter to pass in whether `subprocess` should check the results.  The default is `True` but in this case, I pass in `False` so that we can exit gracefully if the database was never created.  It's a real corner case but I ran into it!
___
*[deploy/roles/combine_maintenance/files/combine_backup.py, line 170 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWA6qJW1TrY37Wa7jaz:-MWAARpJ55tcKFEpjbH9:b-730zhj) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_backup.py#L170)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This can be made cleaner using a context manager (`with`)

```
with tarfile.open(backup_file, "x:gz") as tar:
    ...
```

Context managers automatically close the files they open when the block is exited.

https://docs.python.org/3/library/tarfile.html#examples
</blockquote></details>

I saw that in the example but could not figure out how to close the file!  I did not realize it was done automatically for me.  Thanks!
___
*[deploy/roles/combine_maintenance/files/script_step.py, line 11 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWAA1EKEYdO8tjpKmub:-MWADhxq-jpK2bGHRPqd:btd51a6) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/script_step.py#L11)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Not a big deal, but I'd generally expect the `verbose` argument to come after the `desc` argument, which is more of the meat of the function. That would also let you, if you wanted, provide a default to `verbose`.

```py
step.print("Hello!", verbose=True)
```

vs

```py
step.print(False, "Hello!")
```
</blockquote></details>

I agree.
___
*[deploy/roles/combine_maintenance/files/script_step.py, line 13 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWA8taM0ZQ9kPVAFUaN:-MWADt-6-a8QKNQVlhjZ:bhy9ot6) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/script_step.py#L13)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Not required, but you could consider leveraging the built in `logging` module.

It has support for controlling verbosity/where logs are output to built in. Might be worth just taking a look. We might be able to avoid passing `verbose` around everywhere if we simple configure the logging level once at the beginning of these scripts.

https://docs.python.org/3/library/logging.html
</blockquote></details>

Will do.
___
*[scripts/docker_setup.py, line 161 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWAD7BdDJnZ-YNmiUvK:-MWAE3XqCBnaWpdrVtCr:bhy9ot6) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/scripts/docker_setup.py#L161)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Per other comment, perhaps we can avoid needing to copy if we can make the scripts themselves independent of the current working directory.
</blockquote></details>

Will do.
___
*[deploy/roles/combine_maintenance/files/combine_restore.py, line 28 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWAAYN31e43hmUHFA5_:-MWABNGQ2dhmmRVM6oXu:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_restore.py#L28)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Cleanout -> clean out
</blockquote></details>

Done.
___
*[deploy/roles/combine_maintenance/files/combine_restore.py, line 36 at r2](https://reviewable.io/reviews/sillsdev/thecombine [...]

2021-03-19 16:13 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_backup.py, line 28 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWA4sVF7STjxe54fV32:-MWAFok7992JfgGKYi2w:bc07uj6) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_backup.py#L28)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

My intent was that the user would not need to type in the location of the configuration file but that the `--config` option would allow someone to override it.  This could be handy if someone (i.e. me) wants to have an alternate configuration for a different AWS location for testing.
</blockquote></details>

Yes, please disregard this comment. I didn't realize that you were accessing `argv[0]`.


<!-- Sent from Reviewable.io -->

2021-03-19 16:16 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_backup.py, line 135 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWA8RPVDAbopmQdhBvd:-MWAG3DB2lEBkYUNA8iF:baza82a) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_backup.py#L135)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

I needed to be able to determine if there is a database backup to copy first.  When there is no output from `mongodump`, for example, when the database is empty, the `dump` directory does not exist so the `docker cp ...` fails.  I added a parameter to pass in whether `subprocess` should check the results.  The default is `True` but in this case, I pass in `False` so that we can exit gracefully if the database was never created.  It's a real corner case but I ran into it!
</blockquote></details>

Ah, I missed the `False` being passed in.

One thing you can do to make certain arguments keyword only (to make some of these `bool` arguments stand out more at the call site is to:

```py
def run_cmd(cmd: List[str], *, check_results: bool = True)
```

Now you have to call it like: `run_cmd([], check_results=False)`

Not saying you need to here, but just for your awareness. I've begun using `*,` more in some of my functions that can then be a little more descriptive when used.


<!-- Sent from Reviewable.io -->

2021-03-19 16:29 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1084)* status: all files reviewed, 15 unresolved discussions (waiting on @jmgrady and @johnthagen)

___
*[deploy/roles/combine_maintenance/files/combine_backup.py, line 135 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWA8RPVDAbopmQdhBvd:-MWAIf4t2y3mjelVZ5ov:bnljs45) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_backup.py#L135)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Ah, I missed the `False` being passed in.

One thing you can do to make certain arguments keyword only (to make some of these `bool` arguments stand out more at the call site is to:

```py
def run_cmd(cmd: List[str], *, check_results: bool = True)
```

Now you have to call it like: `run_cmd([], check_results=False)`

Not saying you need to here, but just for your awareness. I've begun using `*,` more in some of my functions that can then be a little more descriptive when used.
</blockquote></details>

I like this much better.  I think it's more readable when I don't need to look at the function declaration to decipher its arguments.
Done.


<!-- Sent from Reviewable.io -->

2021-03-19 17:08 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_backup.py, line 63 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWA5mFC3nQFmhzVC_KK:-MWASMDR1xQ8SiqIGas-:brvkkvn) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_backup.py#L63)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It looks like you closed the file, but I would recommend we use `args.config.read_text()` instead, as it's a simpler way to do this with `Path` objects.


<!-- Sent from Reviewable.io -->

2021-03-19 17:09 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_restore.py, line 76 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWAB4OJEzanC0VjULN8:-MWASf29-YoA-4PgoADU:b-13vv3o) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_restore.py#L76)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Per similar comment in other file, could we use `args.config.read_text()` here instead to simplify this?


<!-- Sent from Reviewable.io -->

2021-03-19 17:11 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_restore.py, line 233 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWACpBw2wNPZvqB2XC1:-MWASu92-EmcmZwjXejk:b-ql8wi9) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_restore.py#L233)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

backend; `db_container` is database container.
</blockquote></details>

That wasn't super obvious to me, so perhaps we should use `backend_container` as the variable so it's immediately obvious. `db` is a common abbreviation, but I think `be` will be foreign to most.


<!-- Sent from Reviewable.io -->

2021-03-19 17:12 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_backup.py, line 27 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWA4a6HApfd9sYmc-FA:-MWATHSm-TN4fWAI2omk:b7gnj8d) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_backup.py#L27)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I didn't see any changes for this comment. Are they just not pushed yet?


<!-- Sent from Reviewable.io -->

2021-03-19 17:12 UTC, johnthagen reviewed
> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1084)* status: all files reviewed, 7 unresolved discussions (waiting on @jmgrady)



<!-- Sent from Reviewable.io -->

2021-03-19 18:16 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1084)* status: 15 of 17 files reviewed, 5 unresolved discussions (waiting on @jmgrady and @johnthagen)

___
*[deploy/roles/combine_maintenance/files/combine_backup.py, line 27 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWA4a6HApfd9sYmc-FA:-MWAfAeF0LWPQI4ss-AC:b77wjcj) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_backup.py#L27)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I didn't see any changes for this comment. Are they just not pushed yet?
</blockquote></details>

That's the other reason for making it so we don't need to copy the scripts.  I updated the copy.
___
*[deploy/roles/combine_maintenance/files/combine_backup.py, line 63 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWA5mFC3nQFmhzVC_KK:-MWAfNaC4bwLlOMUW4Sw:b-s0gkrv) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_backup.py#L63)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

It looks like you closed the file, but I would recommend we use `args.config.read_text()` instead, as it's a simpler way to do this with `Path` objects.
</blockquote></details>

Sorry.  I missed that.  That is much simpler.
___
*[deploy/roles/combine_maintenance/files/combine_restore.py, line 76 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWAB4OJEzanC0VjULN8:-MWAfwY0C7-76-8FHzR7:bgm9fp3) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_restore.py#L76)):*
> args.config.read_text()
Done.
___
*[deploy/roles/combine_maintenance/files/combine_restore.py, line 233 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWACpBw2wNPZvqB2XC1:-MWAgaIFC5j9hjk_kixO:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/combine_restore.py#L233)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

That wasn't super obvious to me, so perhaps we should use `backend_container` as the variable so it's immediately obvious. `db` is a common abbreviation, but I think `be` will be foreign to most.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-19 18:18 UTC, johnthagen reviewed
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1084)* status: all files reviewed, 3 unresolved discussions (waiting on @jmgrady)



<!-- Sent from Reviewable.io -->

2021-03-20 12:59 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_backup.py, line 43 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWEhToi3X91NLVjue99:-MWEhToi3X91NLVjue9A:b-p1r024) ([raw file](https://github.com/sillsdev/thecombine/blob/3334aa72d799f50c1f36828451470c3e6b321cf8/deploy/roles/combine_maintenance/files/combine_backup.py#L43)):*
Rather than generating a random name for yourself, Python can automatically generate a cross-platform, unique temporary directory for you (e.g. `/tmp/aha908ht9h`).

See: https://docs.python.org/3/library/tempfile.html#examples

```py
>>> with tempfile.TemporaryDirectory() as tmp_dir:
...     print('created temporary directory', tmp_dir)
```

What is cool is that when the context manager closes, the temporary directory that was created will be automatically deleted (cleaned up). This provides a very error-resistant way to work with temporary directories.


<!-- Sent from Reviewable.io -->

2021-03-20 13:00 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_backup.py, line 55 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWEi9DG5_UcSEO59bwH:-MWEi9DG5_UcSEO59bwI:b-1hhsfe) ([raw file](https://github.com/sillsdev/thecombine/blob/3334aa72d799f50c1f36828451470c3e6b321cf8/deploy/roles/combine_maintenance/files/combine_backup.py#L55)):*
> ```Python
> 
>     backup_dir.mkdir(0o755, parents=True)
> ```

Minor, but I'd probably remove some of these blank newlines so that common "paragraphs" are continguous.


<!-- Sent from Reviewable.io -->

2021-03-20 13:02 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_backup.py, line 162 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWEiQOJ5jQ0DfK6dQhz:-MWEiQOJ5jQ0DfK6dQi-:b9zcf2m) ([raw file](https://github.com/sillsdev/thecombine/blob/3334aa72d799f50c1f36828451470c3e6b321cf8/deploy/roles/combine_maintenance/files/combine_backup.py#L162)):*
> ```Python
>     # Change back to workdir so that we can delete the backup_dir
>     os.chdir(workdir)
>     shutil.rmtree(backup_dir)
> ```

Using the context manager approach described above, this line can be removed (context manager will automatically delete the temp dir).


<!-- Sent from Reviewable.io -->

2021-03-20 13:02 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_restore.py, line 56 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWEifK7-ZCOfTk87n1x:-MWEifK7-ZCOfTk87n1y:b-vfg6iw) ([raw file](https://github.com/sillsdev/thecombine/blob/3334aa72d799f50c1f36828451470c3e6b321cf8/deploy/roles/combine_maintenance/files/combine_restore.py#L56)):*
> ```Python
>     step.print("Prepare for the restore.", args.verbose)
> 
>     restore_dir = Path(tempfile.gettempdir()) / f"restore{os.getpid()}"
> ```

See comment in `combine_backup.py` about how to use a context manager for this.


<!-- Sent from Reviewable.io -->

2021-03-20 13:03 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_restore.py, line 42 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWEinz657uHQEl5tWz6:-MWEinz657uHQEl5tWz7:b-m61l9c) ([raw file](https://github.com/sillsdev/thecombine/blob/3334aa72d799f50c1f36828451470c3e6b321cf8/deploy/roles/combine_maintenance/files/combine_restore.py#L42)):*
> ```Python
>     if match is not None:
>         return match.group(1)
>     return obj_name
> ```

I like this change you made. I've learned more and more that it's important to remove nesting that isn't needed (reducing cognitive complexity).


<!-- Sent from Reviewable.io -->

2021-03-20 13:04 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_restore.py, line 236 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWEiyAuD8yIYekYHKfS:-MWEiyAvCHZIVFRzg5QK:b-e6kjk8) ([raw file](https://github.com/sillsdev/thecombine/blob/3334aa72d799f50c1f36828451470c3e6b321cf8/deploy/roles/combine_maintenance/files/combine_restore.py#L236)):*
> ```Python
>     step.print("Cleanup Restore files.", args.verbose)
>     os.chdir(workdir)
>     shutil.rmtree(restore_dir)
> ```

See comment in `combine_backup.py` about how this can be removed using a context manager.


<!-- Sent from Reviewable.io -->

2021-03-20 13:04 UTC, johnthagen commented
___
*[scripts/docker_setup.py, line 161 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWAD7BdDJnZ-YNmiUvK:-MWEjBhJ7_wk2AxfVeA7:btwz6bj) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/scripts/docker_setup.py#L161)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Will do.
</blockquote></details>

Can this be safely removed now?


<!-- Sent from Reviewable.io -->

2021-03-20 13:05 UTC, johnthagen reviewed
> Reviewed 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1084)* status: all files reviewed, 9 unresolved discussions (waiting on @jmgrady)



<!-- Sent from Reviewable.io -->

2021-03-20 13:41 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1084)* status: all files reviewed, 6 unresolved discussions (waiting on @jmgrady and @johnthagen)

___
*[tox.ini, line 27 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWA7vrj7Rm6YIWITXja:-MWEoKUGBWCguOX9PxGX:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/tox.ini#L27)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Will do.  I think this is a better approach.
</blockquote></details>

Done.
___
*[deploy/roles/combine_maintenance/files/combine_backup.py, line 43 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWEhToi3X91NLVjue99:-MWEoPBE1SJSKirqKasa:bi0kxs8) ([raw file](https://github.com/sillsdev/thecombine/blob/3334aa72d799f50c1f36828451470c3e6b321cf8/deploy/roles/combine_maintenance/files/combine_backup.py#L43)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Rather than generating a random name for yourself, Python can automatically generate a cross-platform, unique temporary directory for you (e.g. `/tmp/aha908ht9h`).

See: https://docs.python.org/3/library/tempfile.html#examples

```py
>>> with tempfile.TemporaryDirectory() as tmp_dir:
...     print('created temporary directory', tmp_dir)
```

What is cool is that when the context manager closes, the temporary directory that was created will be automatically deleted (cleaned up). This provides a very error-resistant way to work with temporary directories.
</blockquote></details>

Yes, this is exactly what I wanted.  I saw something like this for a temporary file but was not sure how I would do the same with a directory.  I guess I just did not read far enough.

Done.
___
*[deploy/roles/combine_maintenance/files/combine_backup.py, line 162 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWEiQOJ5jQ0DfK6dQhz:-MWEqs438HglMnAupPBu:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/3334aa72d799f50c1f36828451470c3e6b321cf8/deploy/roles/combine_maintenance/files/combine_backup.py#L162)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Using the context manager approach described above, this line can be removed (context manager will automatically delete the temp dir).
</blockquote></details>

Done.
___
*[scripts/docker_setup.py, line 161 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWAD7BdDJnZ-YNmiUvK:-MWEr7gnCFe_FWbhrTGy:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/scripts/docker_setup.py#L161)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Can this be safely removed now?
</blockquote></details>

Done.
___
*[deploy/roles/combine_maintenance/files/combine_restore.py, line 56 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWEifK7-ZCOfTk87n1x:-MWEr-7a5RI_3vOnAOUn:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/3334aa72d799f50c1f36828451470c3e6b321cf8/deploy/roles/combine_maintenance/files/combine_restore.py#L56)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

See comment in `combine_backup.py` about how to use a context manager for this.
</blockquote></details>

Done.
___
*[deploy/roles/combine_maintenance/files/combine_restore.py, line 236 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWEiyAuD8yIYekYHKfS:-MWEr13ODI_oIzOOhE89:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/3334aa72d799f50c1f36828451470c3e6b321cf8/deploy/roles/combine_maintenance/files/combine_restore.py#L236)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

See comment in `combine_backup.py` about how this can be removed using a context manager.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-20 14:03 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_backup.py, line 153 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWEwYqhCisSH_gfHfjB:-MWEwYqhCisSH_gfHfjC:bz2ruad) ([raw file](https://github.com/sillsdev/thecombine/blob/bb79ba5a35443cb4e31c2abde7ec5167011aed89/deploy/roles/combine_maintenance/files/combine_backup.py#L153)):*
> ```Python
>         step.print("Remove backup files.", args.verbose)
> 
>         # Change back to workdir so that we can delete the backup_dir
> ```

Is it possible to remove these line? Or should the comment be updated at least?


<!-- Sent from Reviewable.io -->

2021-03-20 14:03 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_backup.py, line 151 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWEwbUU8WhdZJmJBiIX:-MWEwbUU8WhdZJmJBiIY:bojmiw4) ([raw file](https://github.com/sillsdev/thecombine/blob/bb79ba5a35443cb4e31c2abde7ec5167011aed89/deploy/roles/combine_maintenance/files/combine_backup.py#L151)):*
> ```Python
>         )
> 
>         step.print("Remove backup files.", args.verbose)
> ```

Since this is done automatically now, do we still need the log print?


<!-- Sent from Reviewable.io -->

2021-03-20 14:04 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_restore.py, line 227 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWEwkcC7HA0UXt85683:-MWEwkcC7HA0UXt85684:bm1xsab) ([raw file](https://github.com/sillsdev/thecombine/blob/bb79ba5a35443cb4e31c2abde7ec5167011aed89/deploy/roles/combine_maintenance/files/combine_restore.py#L227)):*
> ```Python
>         )
> 
>         step.print("Cleanup Restore files.", args.verbose)
> ```

Since this is done automatically, do we still need this log print?


<!-- Sent from Reviewable.io -->

2021-03-20 14:04 UTC, johnthagen commented
___
*[scripts/docker_setup.py, line 161 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWAD7BdDJnZ-YNmiUvK:-MWEwrnM8u1VV5815FAn:bhdk1ev) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/scripts/docker_setup.py#L161)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Did this accidently not get pushed?


<!-- Sent from Reviewable.io -->

2021-03-20 14:05 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/script_step.py, line 13 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWA8taM0ZQ9kPVAFUaN:-MWEwzvx8Ci5TPXRrMds:b5jvlvq) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/script_step.py#L13)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Will do.
</blockquote></details>

Just double checking if you are planned to do this. I don't think it's required, but wanted to make sure something didn't accidently not get checked in here.


<!-- Sent from Reviewable.io -->

2021-03-20 14:05 UTC, johnthagen reviewed
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1084)* status: all files reviewed, 5 unresolved discussions (waiting on @jmgrady)



<!-- Sent from Reviewable.io -->

2021-03-20 14:54 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1084)* status: 12 of 16 files reviewed, 3 unresolved discussions (waiting on @jmgrady and @johnthagen)

___
*[deploy/roles/combine_maintenance/files/script_step.py, line 13 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWA8taM0ZQ9kPVAFUaN:-MWF5tpzBMUuU3YXxdT7:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/deploy/roles/combine_maintenance/files/script_step.py#L13)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Just double checking if you are planned to do this. I don't think it's required, but wanted to make sure something didn't accidently not get checked in here.
</blockquote></details>

Done.
___
*[scripts/docker_setup.py, line 161 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWAD7BdDJnZ-YNmiUvK:-MWF6m65E0hepVlSXM6w:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/c33822ff8b00e5b07837b4f6adcc04e22707c930/scripts/docker_setup.py#L161)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Did this accidently not get pushed?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-20 16:38 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_backup.py, line 151 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWEwbUU8WhdZJmJBiIX:-MWFV7DvEf_FPemMsIsb:bb6un1j) ([raw file](https://github.com/sillsdev/thecombine/blob/bb79ba5a35443cb4e31c2abde7ec5167011aed89/deploy/roles/combine_maintenance/files/combine_backup.py#L151)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Since this is done automatically now, do we still need the log print?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-03-20 16:39 UTC, johnthagen commented
___
*[deploy/roles/combine_maintenance/files/combine_backup.py, line 153 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWEwYqhCisSH_gfHfjB:-MWFVEBa88L4Uvfn-rIj:bjhuwqb) ([raw file](https://github.com/sillsdev/thecombine/blob/bb79ba5a35443cb4e31c2abde7ec5167011aed89/deploy/roles/combine_maintenance/files/combine_backup.py#L153)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Is it possible to remove these line? Or should the comment be updated at least?
</blockquote></details>

FYI, the temporary directory will be deleted regardless of the current working directory.


<!-- Sent from Reviewable.io -->

2021-03-20 16:40 UTC, johnthagen approved these changes
> Reviewed 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1084)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)



<!-- Sent from Reviewable.io -->

2021-03-22 00:01 UTC, johnthagen commented
___
*[tox.ini, line 34 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWMDa7-86a9aL6FLfkR:-MWMDa7-86a9aL6FLfkS:b-6zpnhi) ([raw file](https://github.com/sillsdev/thecombine/blob/5d616b71e11fc221e7dd9af5ca37fecbd333728d/tox.ini#L34)):*
> ```INI
>     -r{toxinidir}/dev-requirements.txt
> commands =
>     mypy --config-file setup-docker.cfg certmgr/scripts
> ```

To keep things a little simpler to invoke, I'd recommend moving this `mypy` command up into `type-check` testenv.

```ini
[testenv:type-check]
deps =
    -r{toxinidir}/dev-requirements.txt
commands =
    mypy deploy scripts
    mypy --config-file setup-docker.cfg certmgr/scripts
```


<!-- Sent from Reviewable.io -->

2021-03-22 00:04 UTC, johnthagen commented
___
*[setup-docker.cfg, line 6 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWMEJrm3pwzq5xz0i35:-MWMEJrm3pwzq5xz0i36:b-d9u3vw) ([raw file](https://github.com/sillsdev/thecombine/blob/5d616b71e11fc221e7dd9af5ca37fecbd333728d/setup-docker.cfg#L6)):*
> ```INI
> disallow_untyped_defs = True
> no_implicit_optional = True
> platform = "linux"
> ```

For the sake of simplicity, I wonder if there is much harm in just setting `platform = "linux"` in the normal `setup.cfg` and then we don't need to maintain two `.cfg.` files and remember which to use for certain invocations when we add more Python files.

Since all of this Python code needs to run on at least Linux (and possibly Linux + others), this seems like a pretty safe bet from a type-checking perspective.


<!-- Sent from Reviewable.io -->

2021-03-22 00:04 UTC, johnthagen reviewed
> Reviewed 4 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1084)* status: all files reviewed, 2 unresolved discussions (waiting on @jmgrady)



<!-- Sent from Reviewable.io -->

2021-03-22 00:18 UTC, johnthagen commented
___
*[setup-docker.cfg, line 6 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWMEJrm3pwzq5xz0i35:-MWMHTLcA9_NhjR8jIwT:bo4ocx8) ([raw file](https://github.com/sillsdev/thecombine/blob/5d616b71e11fc221e7dd9af5ca37fecbd333728d/setup-docker.cfg#L6)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

For the sake of simplicity, I wonder if there is much harm in just setting `platform = "linux"` in the normal `setup.cfg` and then we don't need to maintain two `.cfg.` files and remember which to use for certain invocations when we add more Python files.

Since all of this Python code needs to run on at least Linux (and possibly Linux + others), this seems like a pretty safe bet from a type-checking perspective.
</blockquote></details>

To say this more clearly, I can't see us ever writing a Python script that is Windows-only since the Combine is a cross-platform app and the benefit we can for using Python is it's cross-platform nature. So if we pin our type hinting at Linux + everything that is cross platform, that is basically everything that we could need.

I've used a few Linux-only Python modules before (like signals) but I can't remember using anything from the Python stdlib that was Windows-only.


<!-- Sent from Reviewable.io -->

2021-03-22 12:44 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1084)* status: all files reviewed, 2 unresolved discussions (waiting on @jmgrady and @johnthagen)

___
*[setup-docker.cfg, line 6 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWMEJrm3pwzq5xz0i35:-MWOubGf3DKdwqQtxNdZ:bnxjzm9) ([raw file](https://github.com/sillsdev/thecombine/blob/5d616b71e11fc221e7dd9af5ca37fecbd333728d/setup-docker.cfg#L6)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

To say this more clearly, I can't see us ever writing a Python script that is Windows-only since the Combine is a cross-platform app and the benefit we can for using Python is it's cross-platform nature. So if we pin our type hinting at Linux + everything that is cross platform, that is basically everything that we could need.

I've used a few Linux-only Python modules before (like signals) but I can't remember using anything from the Python stdlib that was Windows-only.
</blockquote></details>

It may be simpler, but I do not think it is prudent.  These scripts are being ported to Python so that they can run under Windows.  If there is any value in the type testing, it should cover all operating conditions.  Part of the issue is that TheCombine is NOT really cross-platform.  It is only deployed on Linux in two scenarios:
 1. a cloud-based server, and
 2. a standalone server.
Running TheCombine under Windows is a simulation environment and does not support all of the functions that are implemented (more from a network standpoint than because it is running under Windows, though).

Your suggestion for the type-check script simplifies it greatly and I will implement that.  I may also add a check in certmgr/scripts/entrypoint.py to raise an exception if `sys.platform != "linux"`.  This may obviate the need for the separate type-check configuration.
___
*[tox.ini, line 34 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWMDa7-86a9aL6FLfkR:-MWOx8Si2UOmxRuXR0x2:b-iscua8) ([raw file](https://github.com/sillsdev/thecombine/blob/5d616b71e11fc221e7dd9af5ca37fecbd333728d/tox.ini#L34)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

To keep things a little simpler to invoke, I'd recommend moving this `mypy` command up into `type-check` testenv.

```ini
[testenv:type-check]
deps =
    -r{toxinidir}/dev-requirements.txt
commands =
    mypy deploy scripts
    mypy --config-file setup-docker.cfg certmgr/scripts
```
</blockquote></details>

Will do.
I will first investigate my suggestion above - raise an exception if not linux.
___
*[deploy/roles/combine_maintenance/files/combine_backup.py, line 153 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWEwYqhCisSH_gfHfjB:-MWOxPk0DaLIaSnHcFuK:b-o9s6zi) ([raw file](https://github.com/sillsdev/thecombine/blob/bb79ba5a35443cb4e31c2abde7ec5167011aed89/deploy/roles/combine_maintenance/files/combine_backup.py#L153)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

FYI, the temporary directory will be deleted regardless of the current working directory.
</blockquote></details>

I am not sure that this last statement is true.  I saw some problems earlier where it seemed to be hitting a maximum recursion limit and it seemed to be when the `with` scope was exited.


<!-- Sent from Reviewable.io -->

2021-03-22 15:24 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1084)* status: 18 of 19 files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[tox.ini, line 34 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWMDa7-86a9aL6FLfkR:-MWPPwBp4nmtOpeaeakr:b-z67pic) ([raw file](https://github.com/sillsdev/thecombine/blob/5d616b71e11fc221e7dd9af5ca37fecbd333728d/tox.ini#L34)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Will do.
I will first investigate my suggestion above - raise an exception if not linux.
</blockquote></details>

Done.
(BTW, I have decided that raising an exception if not linux in the certmgr container would be a bad idea.  I believe that if I did that, then for any Windows user who wants/needs to maintain the Docker container, mypy would not find any type errors.)


<!-- Sent from Reviewable.io -->

2021-03-22 17:06 UTC, johnthagen commented
___
*[setup-docker.cfg, line 6 at r9](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWPthsl4naMlk2xwhw5:-MWPthsl4naMlk2xwhw6:bcxjqlj) ([raw file](https://github.com/sillsdev/thecombine/blob/11c9d21da5ab771b1368fa8772ff9f58128912f3/setup-docker.cfg#L6)):*
> ```INI
> disallow_untyped_defs = True
> no_implicit_optional = True
> platform = "linux"
> ```

Is there a weird character at the end of this line?


<!-- Sent from Reviewable.io -->

2021-03-22 17:06 UTC, johnthagen reviewed
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1084)* status: all files reviewed, 1 unresolved discussion (waiting on @jmgrady)



<!-- Sent from Reviewable.io -->

2021-03-22 17:32 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1084)* status: 13 of 21 files reviewed, 1 unresolved discussion (waiting on @jmgrady and @johnthagen)

___
*[setup-docker.cfg, line 6 at r9](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWPthsl4naMlk2xwhw5:-MWPzMGT8N6zJ-OVgW6F:b-7n6g08) ([raw file](https://github.com/sillsdev/thecombine/blob/11c9d21da5ab771b1368fa8772ff9f58128912f3/setup-docker.cfg#L6)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Is there a weird character at the end of this line?
</blockquote></details>

No, there is no weird character at the end of that line.  It is (was) missing the ending newline. ;-)
Done.


<!-- Sent from Reviewable.io -->

2021-03-22 23:10 UTC, johnthagen commented
___
*[tox.ini, line 27 at r10](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWRBRgN3gmpQ9I3_kaF:-MWRBRgN3gmpQ9I3_kaG:bocdc16) ([raw file](https://github.com/sillsdev/thecombine/blob/92f6cc76903b5646c03926abc52a9cae28b3c01d/tox.ini#L27)):*
> ```INI
>     -r{toxinidir}/dev-requirements.txt
> commands =
>     mypy deploy scripts
> ```

I played around and found a very simple solution that doesn't require multiple config files or invocations or any change to the actual script:


```py
        usr1_signal = signal.SIGUSR1  # type: ignore
        signal.signal(usr1_signal, handle_user_sig1)
        while True:
            # check for renewal after 12 hours or SIGUSR1 received
            # (12 hrs x 3600 sec/hr)
            got_sig = signal.sigtimedwait([usr1_signal], 12 * 3600)  # type: ignore
```

By using `# type: ignore` we can surgically suppress the two lines that have Linux-specific behavior. By doing this we don't need the extra `mypy` line in `tox.ini` or the extra `setup.cfg`. The rest of the modules and lines will all type check correctly on all platforms.

This is the solution I would recommend.


<!-- Sent from Reviewable.io -->

2021-03-22 23:10 UTC, johnthagen reviewed
> Reviewed 8 of 8 files at r10.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1084)* status: all files reviewed, 1 unresolved discussion (waiting on @jmgrady)



<!-- Sent from Reviewable.io -->

2021-03-23 11:45 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1084)* status: 19 of 20 files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[tox.ini, line 27 at r10](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWRBRgN3gmpQ9I3_kaF:-MWTsJ64502vs6W8NKOb:b-5ekwla) ([raw file](https://github.com/sillsdev/thecombine/blob/92f6cc76903b5646c03926abc52a9cae28b3c01d/tox.ini#L27)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I played around and found a very simple solution that doesn't require multiple config files or invocations or any change to the actual script:


```py
        usr1_signal = signal.SIGUSR1  # type: ignore
        signal.signal(usr1_signal, handle_user_sig1)
        while True:
            # check for renewal after 12 hours or SIGUSR1 received
            # (12 hrs x 3600 sec/hr)
            got_sig = signal.sigtimedwait([usr1_signal], 12 * 3600)  # type: ignore
```

By using `# type: ignore` we can surgically suppress the two lines that have Linux-specific behavior. By doing this we don't need the extra `mypy` line in `tox.ini` or the extra `setup.cfg`. The rest of the modules and lines will all type check correctly on all platforms.

This is the solution I would recommend.
</blockquote></details>

That was actually what I tried first but I do not like altering the source to override the tools.  I would prefer something to specify that the certmgr container is designed to only be run under Linux. (Not that I would object to a simple, cross-platform method of handling asynchronous events!).

However, I agree that it is also ugly to have to support two configuration files.  Your comment prompted me to do some digging and we can get rid of the second configuration file by defining the `type-check` in `tox.ini` as follows:
```
[testenv:type-check]
deps =
    -r{toxinidir}/dev-requirements.txt
commands =
    mypy deploy scripts
    mypy --platform linux certmgr/scripts
```
I prefer this approach - supporting two lines in `tox.ini` is straight-forward since they are adjacent to each other.

I have pushed this change to GitHub.


<!-- Sent from Reviewable.io -->

2021-03-26 16:48 UTC, imnasnainaec reviewed
> Reviewed 5 of 12 files at r11.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1084)* status: 17 of 22 files reviewed, 4 unresolved discussions (waiting on @jmgrady and @johnthagen)

___
*[README.md, line 492 at r11](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWjDLBo1Q2QfrCFGIQD:-MWjDLBo1Q2QfrCFGIQE:brx5h4p) ([raw file](https://github.com/sillsdev/thecombine/blob/3761703f2689ee9de28ff3f75bab6091496f1752/README.md#L492)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> #### Inspect Database
> To browse the database locally during development, open MongoDB Compass Community.
> 1. Under New Connection, enter `mongodb://localhost:27017`
> 2. Under Databases, select CombineDatabase
> ```
</details>

This doesn't fit under the /### now above it, so perhaps it should become it's own /### and added to the ToC.
___
*[deploy/roles/combine_maintenance/tasks/main.yml, line 12 at r11](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWjMjlq7I44isFYQ-ZL:-MWjMjlq7I44isFYQ-ZM:b-gn2z9l) ([raw file](https://github.com/sillsdev/thecombine/blob/3761703f2689ee9de28ff3f75bab6091496f1752/deploy/roles/combine_maintenance/tasks/main.yml#L12)):*
> ```YAML
>     state: present
> 
> - name: create folders for backups
> ```

`folders` -> `folder`
___
*[deploy/roles/combine_maintenance/templates/backup_conf.json.j2, line 2 at r11](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWjQTfc2KwNMpgTAL1u:-MWjQTfc2KwNMpgTAL1v:b-s5127q) ([raw file](https://github.com/sillsdev/thecombine/blob/3761703f2689ee9de28ff3f75bab6091496f1752/deploy/roles/combine_maintenance/templates/backup_conf.json.j2#L2)):*
> ```
>  "combine_app_dir": "{{ combine_app_dir }}",
> ```
The only use of this config in both the backup and restore scripts is `compose_file = Path(config["combine_app_dir"]) / "docker-compose.yml"`, so if there are no other foreseeable needs for this directory, the whole `compose_file` could be the config argument.
___
*[scripts/docker_setup.py, line 112 at r11](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWjLqZe1y4oqytllVaA:-MWjLqZe1y4oqytllVaB:b94jnk9) ([raw file](https://github.com/sillsdev/thecombine/blob/3761703f2689ee9de28ff3f75bab6091496f1752/scripts/docker_setup.py#L112)):*
> ```Python
>         "combine_app_dir": re.sub(r"\\", r"\\\\", str(project_dir)),
>         "backend_files_subdir": ".CombineFiles",
>         "mongo_files_subdir": "dump",
> ```

Is this subdir name "dump" related to the "/usr/bin/mongodump" elsewhere?


<!-- Sent from Reviewable.io -->

2021-03-26 16:56 UTC, imnasnainaec reviewed
> Reviewed 2 of 12 files at r11.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1084)* status: 19 of 22 files reviewed, 5 unresolved discussions (waiting on @jmgrady and @johnthagen)

___
*[deploy/roles/combine_maintenance/files/combine_restore.py, line 235 at r11](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWjScOR3sz773zIOaLV:-MWjScOS78E_eYtLSqkt:bhio52f) ([raw file](https://github.com/sillsdev/thecombine/blob/3761703f2689ee9de28ff3f75bab6091496f1752/deploy/roles/combine_maintenance/files/combine_restore.py#L235)):*
> ```
>     #        os.chdir(workdir)
> ```
Might as well delete.


<!-- Sent from Reviewable.io -->

2021-03-26 17:11 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1084)* status: 19 of 22 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec, @jmgrady, and @johnthagen)

___
*[README.md, line 492 at r11](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWjDLBo1Q2QfrCFGIQD:-MWjU8vjDWayO7Mv5Gni:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/3761703f2689ee9de28ff3f75bab6091496f1752/README.md#L492)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> #### Inspect Database
> To browse the database locally during development, open MongoDB Compass Community.
> 1. Under New Connection, enter `mongodb://localhost:27017`
> 2. Under Databases, select CombineDatabase
> ```
This doesn't fit under the /### now above it, so perhaps it should become it's own /### and added to the ToC.
</blockquote></details>

Done.
___
*[deploy/roles/combine_maintenance/tasks/main.yml, line 12 at r11](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWjMjlq7I44isFYQ-ZL:-MWjUcQ_2SwwKTqLDm2k:bv3xp1q) ([raw file](https://github.com/sillsdev/thecombine/blob/3761703f2689ee9de28ff3f75bab6091496f1752/deploy/roles/combine_maintenance/tasks/main.yml#L12)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`folders` -> `folder`
</blockquote></details>

Done.
Also changed "backups" to "scripts" since the backup files are not stored there and all of the maintenance scripts are stored there.
___
*[deploy/roles/combine_maintenance/templates/backup_conf.json.j2, line 2 at r11](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWjQTfc2KwNMpgTAL1u:-MWjV18x-VXqt4V-gGac:bh8vjnl) ([raw file](https://github.com/sillsdev/thecombine/blob/3761703f2689ee9de28ff3f75bab6091496f1752/deploy/roles/combine_maintenance/templates/backup_conf.json.j2#L2)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>  "combine_app_dir": "{{ combine_app_dir }}",
> ```
The only use of this config in both the backup and restore scripts is `compose_file = Path(config["combine_app_dir"]) / "docker-compose.yml"`, so if there are no other foreseeable needs for this directory, the whole `compose_file` could be the config argument.
</blockquote></details>

Will do.  Good suggestion.
___
*[scripts/docker_setup.py, line 112 at r11](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWjLqZe1y4oqytllVaA:-MWjVIoS9hKWnGDwdazO:b-d6iicn) ([raw file](https://github.com/sillsdev/thecombine/blob/3761703f2689ee9de28ff3f75bab6091496f1752/scripts/docker_setup.py#L112)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Is this subdir name "dump" related to the "/usr/bin/mongodump" elsewhere?
</blockquote></details>

dump is the default directory that mongodump uses.  I did not run `mongodump` with an output directory specified  since its lifespan does not extend past the end of the script.
___
*[deploy/roles/combine_maintenance/files/combine_restore.py, line 235 at r11](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWjScOR3sz773zIOaLV:-MWjUQ-gEKOVW5PaPjCk:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/3761703f2689ee9de28ff3f75bab6091496f1752/deploy/roles/combine_maintenance/files/combine_restore.py#L235)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>     #        os.chdir(workdir)
> ```
Might as well delete.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-26 17:39 UTC, imnasnainaec reviewed
> Reviewed 1 of 12 files at r11, 3 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1084)* status: 21 of 22 files reviewed, 1 unresolved discussion (waiting on @jmgrady and @johnthagen)



<!-- Sent from Reviewable.io -->

2021-03-26 17:41 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1084)* status: 19 of 22 files reviewed, all discussions resolved (waiting on @imnasnainaec and @johnthagen)

___
*[deploy/roles/combine_maintenance/templates/backup_conf.json.j2, line 2 at r11](https://reviewable.io/reviews/sillsdev/thecombine/1084#-MWjQTfc2KwNMpgTAL1u:-MWjcB1H3UHvyCJmUJxL:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/3761703f2689ee9de28ff3f75bab6091496f1752/deploy/roles/combine_maintenance/templates/backup_conf.json.j2#L2)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Will do.  Good suggestion.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-26 17:44 UTC, imnasnainaec approved these changes
> Reviewed 3 of 3 files at r13.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1084)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)



<!-- Sent from Reviewable.io -->

2021-03-26 17:49 UTC, merged