Move Merge Blacklist to the backend.
sillsdev/TheCombine pull request #1126
Opened 2021-04-23 21:17 UTC by imnasnainaec

Replacing https://github.com/sillsdev/TheCombine/tree/merge-blacklist-move-backend
Groundwork for moving all of duplicate finder to the backend.

2021-04-29 17:30 UTC, jasonleenaylor reviewed
> Reviewed 3 of 17 files at r1, 1 of 7 files at r2, 6 of 20 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1126)* status: 11 of 27 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec)

___
*[Backend/Controllers/MergeController.cs, line 71 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZTbq5HEnh5SaKrbckI:-MZTbq5HEnh5SaKrbckJ:b-px9l7p) ([raw file](https://github.com/sillsdev/thecombine/blob/b79a6022bea98a868030aa1a8b67eb30ead4f89c/Backend/Controllers/MergeController.cs#L71)):*
> ```
> HttpPut
> ```
So in REST verbage I'd expect this to be an HttpGet
___
*[Backend/Controllers/MergeController.cs, line 85 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZTcUN954ZXGKXIH8WN:-MZTcUN954ZXGKXIH8WO:b7jiswl) ([raw file](https://github.com/sillsdev/thecombine/blob/b79a6022bea98a868030aa1a8b67eb30ead4f89c/Backend/Controllers/MergeController.cs#L85)):*
> ```
> HttpPut("blacklist/check/{userid}
> ```
I'd also expect Get here


<!-- Sent from Reviewable.io -->

2021-04-29 17:40 UTC, imnasnainaec reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1126)* status: 11 of 27 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @jasonleenaylor)

___
*[Backend/Controllers/MergeController.cs, line 71 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZTbq5HEnh5SaKrbckI:-MZTh582CtEumA_E1a3V:b-oqlfhg) ([raw file](https://github.com/sillsdev/thecombine/blob/b79a6022bea98a868030aa1a8b67eb30ead4f89c/Backend/Controllers/MergeController.cs#L71)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> HttpPut
> ```
So in REST verbage I'd expect this to be an HttpGet
</blockquote></details>

I would too, but Get doesn't allow us to add a [FromBody] object (as discussed here: https://stackoverflow.com/questions/46404051/send-object-with-axios-get-request). I believe we use Put in a number of other places where Get would be a better fit if not for this issue.
___
*[Backend/Controllers/MergeController.cs, line 85 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZTcUN954ZXGKXIH8WN:-MZThyJ6BIZ-mTknWhUe:byjlfh8) ([raw file](https://github.com/sillsdev/thecombine/blob/b79a6022bea98a868030aa1a8b67eb30ead4f89c/Backend/Controllers/MergeController.cs#L85)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> HttpPut("blacklist/check/{userid}
> ```
I'd also expect Get here
</blockquote></details>

(see above)


<!-- Sent from Reviewable.io -->

2021-04-29 18:36 UTC, jasonleenaylor requested changes
> Reviewed 2 of 17 files at r1, 1 of 7 files at r2, 8 of 20 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1126)* status: 22 of 27 files reviewed, 4 unresolved discussions (waiting on @imnasnainaec and @jasonleenaylor)

___
*[Backend/Services/MergeService.cs, line 119 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZTnZmN9UGfHziPSJfy:-MZTnZmN9UGfHziPSJfz:bhr4zt1) ([raw file](https://github.com/sillsdev/thecombine/blob/b79a6022bea98a868030aa1a8b67eb30ead4f89c/Backend/Services/MergeService.cs#L119)):*
> ```
> /// <summary> Update merge blacklist for specified <see cref="Project"/> to current frontier. </summary>
> ```
This comment is clear to me today, but future me will need more detail. Adjust it to explain that we don't want to keep blacklist entries with words that have been removed from the frontier.
___
*[Backend.Tests/Models/MergeBlacklistEntryTests.cs, line 24 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZTtUGg-dHWKG2ABnJs:-MZTtUGg-dHWKG2ABnJt:b-bd1aco) ([raw file](https://github.com/sillsdev/thecombine/blob/b79a6022bea98a868030aa1a8b67eb30ead4f89c/Backend.Tests/Models/MergeBlacklistEntryTests.cs#L24)):*
> ```Smalltalk
>             entryA.Id = id;
>             Assert.IsFalse(entryA.Equals(entryB));
>             entryB = entryA.Clone();
> ```

Re-asserting the equality after each clone is unnecessary, the first assert proves that clones compare equal.
Also, this test has one assertion about the clone, but many about NotEquals. Perhapse split it into two tests, one TestCloneIsEqual and TestNotEquals (or something similar).


<!-- Sent from Reviewable.io -->

2021-04-29 19:18 UTC, imnasnainaec reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1126)* status: 20 of 27 files reviewed, 4 unresolved discussions (waiting on @imnasnainaec and @jasonleenaylor)

___
*[Backend/Services/MergeService.cs, line 119 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZTnZmN9UGfHziPSJfy:-MZU3D_p7I__I09RjBbq:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/b79a6022bea98a868030aa1a8b67eb30ead4f89c/Backend/Services/MergeService.cs#L119)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> /// <summary> Update merge blacklist for specified <see cref="Project"/> to current frontier. </summary>
> ```
This comment is clear to me today, but future me will need more detail. Adjust it to explain that we don't want to keep blacklist entries with words that have been removed from the frontier.
</blockquote></details>

Done.
___
*[Backend.Tests/Models/MergeBlacklistEntryTests.cs, line 24 at r4](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZTtUGg-dHWKG2ABnJs:-MZU3G88A9Mu0hy9EZoG:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/b79a6022bea98a868030aa1a8b67eb30ead4f89c/Backend.Tests/Models/MergeBlacklistEntryTests.cs#L24)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Re-asserting the equality after each clone is unnecessary, the first assert proves that clones compare equal.
Also, this test has one assertion about the clone, but many about NotEquals. Perhapse split it into two tests, one TestCloneIsEqual and TestNotEquals (or something similar).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-29 22:06 UTC, jasonleenaylor reviewed
> Reviewed 5 of 20 files at r3, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1126)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)



<!-- Sent from Reviewable.io -->

2021-04-30 11:34 UTC, johnthagen commented
___
*[Backend/Controllers/MergeController.cs, line 61 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXYiqBBOjp707JJQqf:-MZXYiqBBOjp707JJQqg:bx8wyhd) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend/Controllers/MergeController.cs#L61)):*
> ```Smalltalk
>             var userId = _permissionService.GetUserId(HttpContext);
>             var blacklistEntry = await _mergeService.AddToMergeBlacklist(projectId, userId, wordIds);
>             if (blacklistEntry is null)
> ```

This can never be true (proven by type system) so this `if` block should be removed.


<!-- Sent from Reviewable.io -->

2021-04-30 11:38 UTC, johnthagen commented
___
*[Backend/Controllers/MergeController.cs, line 33 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXZ3v--wd7GdcwqRAI:-MZXZ3v--wd7GdcwqRAJ:b-yvuh3c) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend/Controllers/MergeController.cs#L33)):*
> ```Smalltalk
>         public async Task<IActionResult> Put(string projectId, [FromBody] List<MergeWords> mergeWordsList)
>         {
>             if (!await _permissionService.HasProjectPermission(HttpContext, Permission.MergeAndCharSet))
> ```

Just a thought, but since all of the methods in this class require the same permission, we could consider making a common `const Permission _permission` for the entire `Controller` to codify that and reduce DRY?


<!-- Sent from Reviewable.io -->

2021-04-30 11:48 UTC, johnthagen commented
___
*[Backend/Repositories/MergeBlacklistRepository.cs, line 65 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXaw9h0237jF8UDVu7:-MZXaw9h0237jF8UDVu8:b-saah06) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend/Repositories/MergeBlacklistRepository.cs#L65)):*
> ```Smalltalk
>         }
> 
>         /// <summary> Removes specified <see cref="MergeBlacklist"/> for specified <see cref="Project"/>. </summary>
> ```

Typo: `MergeBlackList`


<!-- Sent from Reviewable.io -->

2021-04-30 11:48 UTC, johnthagen commented
___
*[Backend/Repositories/MergeBlacklistRepository.cs, line 77 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXazrp3y3NZyZ3GVGd:-MZXazrp3y3NZyZ3GVGe:b-saah06) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend/Repositories/MergeBlacklistRepository.cs#L77)):*
> ```Smalltalk
>         }
> 
>         /// <summary> Updates specified <see cref="MergeBlacklist"/>. </summary>
> ```

Typo: `MergeBlackList`


<!-- Sent from Reviewable.io -->

2021-04-30 11:50 UTC, johnthagen commented
___
*[Backend/Repositories/MergeBlacklistRepository.cs, line 65 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXaw9h0237jF8UDVu7:-MZXbJch9F-6Bg2nUlKW:b-1yta19) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend/Repositories/MergeBlacklistRepository.cs#L65)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Typo: `MergeBlackList`
</blockquote></details>

Actually, it's `MergeBlacklistEntry` I believe.


<!-- Sent from Reviewable.io -->

2021-04-30 11:50 UTC, johnthagen commented
___
*[Backend/Repositories/MergeBlacklistRepository.cs, line 77 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXazrp3y3NZyZ3GVGd:-MZXbONW4PTJwJ_hVqWN:b-1yta19) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend/Repositories/MergeBlacklistRepository.cs#L77)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Typo: `MergeBlackList`
</blockquote></details>

Actually, it's `MergeBlacklistEntry` I believe.


<!-- Sent from Reviewable.io -->

2021-04-30 11:51 UTC, johnthagen commented
___
*[Backend/Repositories/MergeBlacklistRepository.cs, line 24 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXbUPT1M8chGmrvkS3:-MZXbUPT1M8chGmrvkS4:b-9pxn0k) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend/Repositories/MergeBlacklistRepository.cs#L24)):*
> ```Smalltalk
>         public async Task<List<MergeBlacklistEntry>> GetAll(string projectId, string? userId = null)
>         {
>             var listFind = (userId is null) ?
> ```

Can remove redundant parathentheses around `(userId is null)`


<!-- Sent from Reviewable.io -->

2021-04-30 11:54 UTC, johnthagen commented
___
*[Backend/Services/MergeService.cs, line 91 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXcJs74oiZZZUiZKJh:-MZXcJs74oiZZZUiZKJi:bf2zg5i) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend/Services/MergeService.cs#L91)):*
> ```Smalltalk
>             foreach (var entry in blacklist)
>             {
>                 if (entry.WordIds.All(id => wordIds.Contains(id)))
> ```

This can be simplified to `if (entry.WordIds.All(wordIds.Contains))`


<!-- Sent from Reviewable.io -->

2021-04-30 11:54 UTC, johnthagen commented
___
*[Backend/Services/MergeService.cs, line 87 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXcPuZ78dlfzgs36Du:-MZXcPuZ78dlfzgs36Dv:b-jz9bta) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend/Services/MergeService.cs#L87)):*
> ```Smalltalk
>                 throw new InvalidBlacklistEntryError("Cannot blacklist a list of fewer than 2 wordIds.");
>             }
>             // When we switch from individual to common blacklist, the userId argement here should be removed.
> ```

Typo: `argument`


<!-- Sent from Reviewable.io -->

2021-04-30 11:57 UTC, johnthagen commented
___
*[Backend/Services/MergeService.cs, line 79 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXc_FYC2k1OPQu91hE:-MZXc_FYC2k1OPQu91hF:b-73yolo) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend/Services/MergeService.cs#L79)):*
> ```Smalltalk
> 
>         /// <summary> Adds a List of wordIds to MergeBlacklist of specified <see cref="Project"/>. </summary>
>         /// <returns> The <see cref="MergeBlacklistEntry"/> created. </returns>
> ```

We should probably add a `/// <exception cref=""></exception>` and document when this function raises. I'm on the fence because it is immediately at the top of the function, but I do think this would be proper. That way if a user uses the Quick Doc feature of their IDE, they can see the way exceptions can be thrown, which is part of the API.


<!-- Sent from Reviewable.io -->

2021-04-30 11:57 UTC, johnthagen commented
___
*[Backend/Services/MergeService.cs, line 101 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXd2Ya2gxPcm2-jGOF:-MZXd2Ya2gxPcm2-jGOG:b2leq48) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend/Services/MergeService.cs#L101)):*
> ```Smalltalk
> 
>         /// <summary> Check if List of wordIds is in MergeBlacklist for specified <see cref="Project"/>. </summary>
>         /// <returns> A bool, true if in the blacklist. </returns>
> ```

Document when exception is thrown?


<!-- Sent from Reviewable.io -->

2021-04-30 11:58 UTC, johnthagen commented
___
*[Backend/Services/MergeService.cs, line 111 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXd8XX5GKtZhRHTjtg:-MZXd8XX5GKtZhRHTjth:bhjlsca) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend/Services/MergeService.cs#L111)):*
> ```Smalltalk
>             foreach (var entry in blacklist)
>             {
>                 if (wordIds.All(id => entry.WordIds.Contains(id)))
> ```

Can be simplified to: `if (entry.WordIds.All(wordIds.Contains))`


<!-- Sent from Reviewable.io -->

2021-04-30 11:58 UTC, johnthagen commented
___
*[Backend/Services/MergeService.cs, line 128 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXdFOX-DJg7Hgbhhz-:-MZXdFOX-DJg7Hgbhhz0:bhg7inf) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend/Services/MergeService.cs#L128)):*
> ```Smalltalk
>         {
>             var oldBlacklist = await _mergeBlacklistRepo.GetAll(projectId);
>             if (oldBlacklist is null || oldBlacklist.Count == 0)
> ```

`oldBlacklist` cannot be `null`, enforced by type system. `oldBlacklist is null` check should be removed.


<!-- Sent from Reviewable.io -->

2021-04-30 12:00 UTC, johnthagen commented
___
*[Backend/Services/MergeService.cs, line 137 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXdXYfESzDug2Cuimq:-MZXdXYfESzDug2Cuimr:b-rcezt5) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend/Services/MergeService.cs#L137)):*
> ```Smalltalk
>             {
>                 var newIds = new List<string>(entry.WordIds.Where(id => frontierWordIds.Contains(id)));
>                 if (newIds.Count < entry.WordIds.Count)
> ```

Can invert this `if` to reduce nesting.

```cs
                if (newIds.Count >= entry.WordIds.Count)
                {
                    continue;
                }

                updateCount++;
                if (newIds.Count > 1)
                {
                    entry.WordIds = newIds;
                    await _mergeBlacklistRepo.Update(entry);
                }
                else
                {
                    await _mergeBlacklistRepo.Delete(projectId, entry.Id);
                }
```


<!-- Sent from Reviewable.io -->

2021-04-30 12:03 UTC, johnthagen commented
___
*[Backend.Tests/Controllers/LiftControllerTests.cs, line 33 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXeIcl5iIoodYpv2Ds:-MZXeIcl5iIoodYpv2Dt:bo45x0k) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend.Tests/Controllers/LiftControllerTests.cs#L33)):*
> ```Smalltalk
>         private ILogger<LiftController> _logger = null!;
>         private string _projId = null!;
>         private const string _projName = "LiftControllerTests";
> ```

Based on our naming conventions, a `const` should be named: `ProjName`


<!-- Sent from Reviewable.io -->

2021-04-30 12:06 UTC, johnthagen commented
___
*[Backend.Tests/Controllers/MergeControllerTests.cs, line 65 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXea7Z6Gu2PIgVOxZg:-MZXea7Z6Gu2PIgVOxZh:b-88u8uy) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend.Tests/Controllers/MergeControllerTests.cs#L65)):*
> ```Smalltalk
>         {
>             _ = _mergeBlacklistRepo.DeleteAll(_projId).Result;
>             var _userId = "1234567890";
> ```

Convert this to a `const`: `const string userId = "1234567890";`


<!-- Sent from Reviewable.io -->

2021-04-30 12:07 UTC, johnthagen commented
___
*[Backend.Tests/Controllers/MergeControllerTests.cs, line 73 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXf2sv7zg3hyy4dnKG:-MZXf2sv7zg3hyy4dnKH:b-drdcow) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend.Tests/Controllers/MergeControllerTests.cs#L73)):*
> ```Smalltalk
>             _ = _mergeService.AddToMergeBlacklist(_projId, _userId, wordIdsC);
> 
>             var isB = ((ObjectResult)(_mergeController.BlacklistCheck(_projId, wordIdsB).Result)).Value;
> ```

All of these lines have redundant parentheses that could be removed

```cs
var isB = ((ObjectResult)_mergeController.BlacklistCheck(_projId, wordIdsB).Result).Value;
```


<!-- Sent from Reviewable.io -->

2021-04-30 12:07 UTC, johnthagen commented
___
*[Backend.Tests/Controllers/MergeControllerTests.cs, line 65 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXea7Z6Gu2PIgVOxZg:-MZXfL9N1V-hnBET_2n_:b-d4537a) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend.Tests/Controllers/MergeControllerTests.cs#L65)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Convert this to a `const`: `const string userId = "1234567890";`
</blockquote></details>

Since it's also reused in another test, perhaps make it a `class`-scoped `const`.


<!-- Sent from Reviewable.io -->

2021-04-30 12:09 UTC, johnthagen commented
___
*[Backend.Tests/Controllers/MergeControllerTests.cs, line 39 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXfZtfCrVddQvtZWBb:-MZXfZtfCrVddQvtZWBc:b-bb1t2d) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend.Tests/Controllers/MergeControllerTests.cs#L39)):*
> ```Smalltalk
>         public void BlacklistAdd()
>         {
>             _ = _mergeBlacklistRepo.DeleteAll(_projId).Result;
> ```

Why do all of these tests start with `DeleteAll()`? Should this be moved to `Setup` or whatever NUnit method is called before each test?


<!-- Sent from Reviewable.io -->

2021-04-30 12:12 UTC, johnthagen commented
___
*[Backend.Tests/Controllers/MergeControllerTests.cs, line 122 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXgMPg8v4Pg61JNMM4:-MZXgMPg8v4Pg61JNMM5:b-nrwf2i) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend.Tests/Controllers/MergeControllerTests.cs#L122)):*
> ```Smalltalk
>         }
>     }
> }
> ```

Would there be any value to testing `MergeController.Put()`?


<!-- Sent from Reviewable.io -->

2021-04-30 12:12 UTC, johnthagen commented
___
*[Backend.Tests/Controllers/MergeControllerTests.cs, line 122 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXgMPg8v4Pg61JNMM4:-MZXgUo95RDE2kuxVvuI:bgfmc2g) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend.Tests/Controllers/MergeControllerTests.cs#L122)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Would there be any value to testing `MergeController.Put()`?
</blockquote></details>

Meant to mark this is discussion, not blocking.


<!-- Sent from Reviewable.io -->

2021-04-30 12:26 UTC, johnthagen commented
___
*[Backend.Tests/Models/MergeBlacklistEntryTests.cs, line 12 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXjeH-8dI3rl8FOd0d:-MZXjeH-8dI3rl8FOd0e:b-4n1gon) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend.Tests/Models/MergeBlacklistEntryTests.cs#L12)):*
> ```Smalltalk
>         private const string projId = "ProjId";
>         private const string userId = "UserId";
>         private List<string> wordIds = new List<string> { "word1", "word2" };
> ```

Can be `readonly`:

```cs
private readonly List<string> _wordIds = new List<string> { "word1", "word2" };
```


<!-- Sent from Reviewable.io -->

2021-04-30 12:27 UTC, johnthagen commented
___
*[Backend.Tests/Models/MergeBlacklistEntryTests.cs, line 13 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXjnvq3yJyCHVKqBuT:-MZXjnvq3yJyCHVKqBuU:bspqkkc) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend.Tests/Models/MergeBlacklistEntryTests.cs#L13)):*
> ```Smalltalk
>         private const string userId = "UserId";
>         private List<string> wordIds = new List<string> { "word1", "word2" };
>         private List<string> idsRevd = new List<string> { "word2", "word1" };
> ```

Can be `readonly`:

```cs
private readonly List<string> _idsRevd = new List<string> { "word2", "word1" };
```


<!-- Sent from Reviewable.io -->

2021-04-30 12:28 UTC, johnthagen commented
___
*[Backend.Tests/Models/MergeBlacklistEntryTests.cs, line 11 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXjsf86DwgonzSVBxx:-MZXjsf86DwgonzSVBxy:b-uwvcrg) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend.Tests/Models/MergeBlacklistEntryTests.cs#L11)):*
> ```Smalltalk
>         private const string id = "EntryId";
>         private const string projId = "ProjId";
>         private const string userId = "UserId";
> ```

Per our naming conventions, these should be renamed:

```cs
        private const string Id = "EntryId";
        private const string ProjId = "ProjId";
        private const string UserId = "UserId";
```


<!-- Sent from Reviewable.io -->

2021-04-30 12:32 UTC, johnthagen commented
___
*[Backend.Tests/Services/MergeServiceTests.cs, line 19 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXkxqyCX13Epvsr_Dv:-MZXkxqyCX13Epvsr_Dw:bmuhp9z) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend.Tests/Services/MergeServiceTests.cs#L19)):*
> ```Smalltalk
> 
>         private string _projId = Guid.NewGuid().ToString();
>         private string _userId = Guid.NewGuid().ToString();
> ```

These two can be set as `readonly`.


<!-- Sent from Reviewable.io -->

2021-04-30 12:32 UTC, johnthagen commented
___
*[Backend.Tests/Services/MergeServiceTests.cs, line 10 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXl3Mh4kxOvNtWMHVQ:-MZXl3Mh4kxOvNtWMHVR:b-rez8of) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend.Tests/Services/MergeServiceTests.cs#L10)):*
> ```Smalltalk
> using NUnit.Framework;
> 
> namespace Backend.Tests.Servicess
> ```

Typo: `Services`


<!-- Sent from Reviewable.io -->

2021-04-30 12:36 UTC, johnthagen commented
___
*[src/backend/index.tsx, line 229 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXlnNqE0La3jH-Ux97:-MZXlnNqE0La3jH-Ux98:bg93bch) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/src/backend/index.tsx#L229)):*
> ```XML
> /** Checks if list of wordIds is in current project's merge blacklist. */
> export async function blacklistCheck(wordIds: string[]): Promise<boolean> {
>   /** Until we have an interface to view/clear the blacklist, each user automatically has their own. */
> ```

Should wrap this line at 80 characters.


<!-- Sent from Reviewable.io -->

2021-04-30 12:39 UTC, johnthagen commented
___
*[src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx, line 286 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXmJ8LCe9TEX1PzMbs:-MZXmJ8LCe9TEX1PzMbt:bj2hqfj) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx#L286)):*
> ```XML
> 
>     // Add to blacklist; no need to await.
>     backend.blacklistAdd(Object.keys(mergeTree.data.words));
> ```

Are we sure we shouldn't add `await` here? Rider gives a warning for a missing `await`.

Wouldn't maximizing `async` behavior maximize performance?


<!-- Sent from Reviewable.io -->

2021-04-30 12:39 UTC, johnthagen requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1126)* status: all files reviewed, 24 unresolved discussions (waiting on @imnasnainaec)



<!-- Sent from Reviewable.io -->

2021-04-30 13:17 UTC, johnthagen commented
___
*[Backend/Models/MergeBlacklistEntry.cs, line 9 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXurnD2vWNgxZf-8SD:-MZXurnEEKnmykR1SaS0:b-via8ye) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend/Models/MergeBlacklistEntry.cs#L9)):*
> ```Smalltalk
> namespace BackendFramework.Models
> {
>     /// <summary> A List of wordIds to avoid in future merges. </summary>
> ```

I'm not sure where to put this documentation, probably here, but maybe in the `MergeBlacklistRepository`, but could we write a paragraph at a high level about how blacklisting is supposed to work, what it does, how it's stored per user, etc? I think having some high level documentation about the purpose of this would make it more discoverable by future developers.


<!-- Sent from Reviewable.io -->

2021-04-30 14:16 UTC, imnasnainaec reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1126)* status: 17 of 37 files reviewed, 20 unresolved discussions (waiting on @imnasnainaec, @jasonleenaylor, and @johnthagen)

___
*[Backend/Controllers/MergeController.cs, line 33 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXZ3v--wd7GdcwqRAI:-MZXvQC2ErVJjM9F_t0l:b2yvvwu) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend/Controllers/MergeController.cs#L33)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Just a thought, but since all of the methods in this class require the same permission, we could consider making a common `const Permission _permission` for the entire `Controller` to codify that and reduce DRY?
</blockquote></details>

I'm not sure we won't be allowing project owners additional merge capabilities at some point.
___
*[Backend/Controllers/MergeController.cs, line 61 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXYiqBBOjp707JJQqf:-MZY7Zt00tn1SUkXhC_s:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend/Controllers/MergeController.cs#L61)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This can never be true (proven by type system) so this `if` block should be removed.
</blockquote></details>

*[Backend/Repositories/MergeBlacklistRepository.cs, line 24 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXbUPT1M8chGmrvkS3:-MZY7awN0Q8sMBBYv-TX:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend/Repositories/MergeBlacklistRepository.cs#L24)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Can remove redundant parathentheses around `(userId is null)`
</blockquote></details>

*[Backend/Repositories/MergeBlacklistRepository.cs, line 65 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXaw9h0237jF8UDVu7:-MZY6yOzBeDzPLFLCfB4:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend/Repositories/MergeBlacklistRepository.cs#L65)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Actually, it's `MergeBlacklistEntry` I believe.
</blockquote></details>

*[Backend/Repositories/MergeBlacklistRepository.cs, line 77 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXazrp3y3NZyZ3GVGd:-MZY6zU_8Gq_dGY4WWtD:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend/Repositories/MergeBlacklistRepository.cs#L77)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Actually, it's `MergeBlacklistEntry` I believe.
</blockquote></details>

*[Backend/Services/MergeService.cs, line 87 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXcPuZ78dlfzgs36Du:-MZY7cYl3Z1MvAZMfPOw:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend/Services/MergeService.cs#L87)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Typo: `argument`
</blockquote></details>

*[Backend/Services/MergeService.cs, line 91 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXcJs74oiZZZUiZKJh:-MZY70JkEkhGTSpzv8n1:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend/Services/MergeService.cs#L91)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This can be simplified to `if (entry.WordIds.All(wordIds.Contains))`
</blockquote></details>

*[Backend/Services/MergeService.cs, line 111 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXd8XX5GKtZhRHTjtg:-MZY73GnDERPC2CqPOYC:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend/Services/MergeService.cs#L111)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Can be simplified to: `if (entry.WordIds.All(wordIds.Contains))`
</blockquote></details>

*[Backend/Services/MergeService.cs, line 128 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXdFOX-DJg7Hgbhhz-:-MZY75QkAhh93-8q6kGE:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend/Services/MergeService.cs#L128)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

`oldBlacklist` cannot be `null`, enforced by type system. `oldBlacklist is null` check should be removed.
</blockquote></details>

*[Backend.Tests/Controllers/LiftControllerTests.cs, line 33 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXeIcl5iIoodYpv2Ds:-MZY78NBDuKgEGdfbJDE:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend.Tests/Controllers/LiftControllerTests.cs#L33)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Based on our naming conventions, a `const` should be named: `ProjName`
</blockquote></details>

*[Backend.Tests/Controllers/MergeControllerTests.cs, line 65 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXea7Z6Gu2PIgVOxZg:-MZY7CzJ5sU6rX_cQEYI:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend.Tests/Controllers/MergeControllerTests.cs#L65)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Since it's also reused in another test, perhaps make it a `class`-scoped `const`.
</blockquote></details>

*[Backend.Tests/Models/MergeBlacklistEntryTests.cs, line 11 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXjsf86DwgonzSVBxx:-MZY7l9f2iGKcTQUbArx:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend.Tests/Models/MergeBlacklistEntryTests.cs#L11)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Per our naming conventions, these should be renamed:

```cs
        private const string Id = "EntryId";
        private const string ProjId = "ProjId";
        private const string UserId = "UserId";
```
</blockquote></details>

*[Backend.Tests/Models/MergeBlacklistEntryTests.cs, line 12 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXjeH-8dI3rl8FOd0d:-MZY7HvlCXG_PQ0vdlQl:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend.Tests/Models/MergeBlacklistEntryTests.cs#L12)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Can be `readonly`:

```cs
private readonly List<string> _wordIds = new List<string> { "word1", "word2" };
```
</blockquote></details>

*[Backend.Tests/Models/MergeBlacklistEntryTests.cs, line 13 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXjnvq3yJyCHVKqBuT:-MZY7ILe4mCHkyBE3GOj:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend.Tests/Models/MergeBlacklistEntryTests.cs#L13)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Can be `readonly`:

```cs
private readonly List<string> _idsRevd = new List<string> { "word2", "word1" };
```
</blockquote></details>

*[Backend.Tests/Services/MergeServiceTests.cs, line 10 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXl3Mh4kxOvNtWMHVQ:-MZY7mIs5lGb6K1zTApx:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend.Tests/Services/MergeServiceTests.cs#L10)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Typo: `Services`
</blockquote></details>

*[Backend.Tests/Services/MergeServiceTests.cs, line 19 at r5](https://reviewable.io/reviews/sillsdev/thec [...]

2021-04-30 14:21 UTC, johnthagen commented
___
*[Backend/Startup.cs, line 107 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZY8bSe55MOSAjEVhp4:-MZY8bSe55MOSAjEVhp5:b-5a2px0) ([raw file](https://github.com/sillsdev/thecombine/blob/8ebf45a21874bb1941f5a17efebbef190a532e7f/Backend/Startup.cs#L107)):*
> ```Smalltalk
> 
>             // Configure JWT Authentication
>             const string secretKeyEnvName = "COMBINE_JWT_SECRET_KEY";
> ```

Ugh, maybe I shouldn't have led you down this path.

The naming convention for class `const`s is different than local `const`s. So these were all correct.

Rider suggests the naming convention based on standard C#/Visual Studio styles.

So if a `const` is a local variable, it should still be `lowerCamelCase`. Sorry for the extra work. In general I won't flag something unless it needs to be changed in that spot. If it should apply more broadly, I'll mention that in the message.


<!-- Sent from Reviewable.io -->

2021-04-30 14:22 UTC, johnthagen commented
___
*[Backend/Controllers/MergeController.cs, line 33 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXZ3v--wd7GdcwqRAI:-MZY99_OBWBNDf6cGUT_:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend/Controllers/MergeController.cs#L33)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I'm not sure we won't be allowing project owners additional merge capabilities at some point.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-30 14:24 UTC, johnthagen commented
___
*[Backend/Services/LiftService.cs, line 297 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZY9L_S1jBm96qbXNUh:-MZY9L_S1jBm96qbXNUi:bw468x5) ([raw file](https://github.com/sillsdev/thecombine/blob/e51247169bd970547161b9256bc1bb8b26ec6f91/Backend/Services/LiftService.cs#L297)):*
> ```Smalltalk
>                 // Pull from resources file with all English semantic domains
>                 var assembly = typeof(LiftService).GetTypeInfo().Assembly;
>                 const string SemDomListFile = "BackendFramework.Data.sdList.txt";
> ```

I won't mention this one any more, but as mentioned before, all local variables, (including `const`) should be `lowerCamelCase` per standard C# guidelines. Only class-scopes variables have a different style.


<!-- Sent from Reviewable.io -->

2021-04-30 14:25 UTC, johnthagen reviewed
> Reviewed 20 of 20 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1126)* status: all files reviewed, 6 unresolved discussions (waiting on @imnasnainaec and @johnthagen)



<!-- Sent from Reviewable.io -->

2021-04-30 14:29 UTC, johnthagen reviewed
> Reviewed 3 of 17 files at r1, 2 of 7 files at r2, 12 of 20 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1126)* status: all files reviewed, 6 unresolved discussions (waiting on @imnasnainaec)



<!-- Sent from Reviewable.io -->

2021-04-30 14:53 UTC, johnthagen commented
___
*[Backend.Tests/Controllers/MergeControllerTests.cs, line 39 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXfZtfCrVddQvtZWBb:-MZYFlPTDnPAkRcKqQVR:bt5qmxk) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend.Tests/Controllers/MergeControllerTests.cs#L39)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Might be possible with a test fixture.
</blockquote></details>

Actually, it looks like `Setup` is called for each test? So maybe that is the correct place for this.

It looks like `OneTimeSetUp` is what I thought `SetUp` is.


<!-- Sent from Reviewable.io -->

2021-04-30 14:53 UTC, johnthagen reviewed
> Reviewed 12 of 12 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1126)* status: all files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)



<!-- Sent from Reviewable.io -->

2021-04-30 14:58 UTC, imnasnainaec reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1126)* status: 36 of 37 files reviewed, 1 unresolved discussion (waiting on @johnthagen)

___
*[Backend.Tests/Controllers/MergeControllerTests.cs, line 39 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1126#-MZXfZtfCrVddQvtZWBb:-MZYHDl59lnQVhpLSfyp:b-o3jmfp) ([raw file](https://github.com/sillsdev/thecombine/blob/c30310df705cd2da36514bd4572205563d89b557/Backend.Tests/Controllers/MergeControllerTests.cs#L39)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Actually, it looks like `Setup` is called for each test? So maybe that is the correct place for this.

It looks like `OneTimeSetUp` is what I thought `SetUp` is.
</blockquote></details>

Yeah, I just discovered that myself. :)


<!-- Sent from Reviewable.io -->

2021-04-30 16:45 UTC, johnthagen approved these changes
> Reviewed 9 of 9 files at r9, 3 of 3 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1126)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)



<!-- Sent from Reviewable.io -->

2021-04-30 17:26 UTC, jasonleenaylor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1126#-:-MZYoHJqAITzNIWU1v9D:b593w57)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)



<!-- Sent from Reviewable.io -->

2021-04-30 17:28 UTC, merged