Move MergeDupFinder from frontend to backend
sillsdev/TheCombine pull request #1142
Opened 2021-05-04 18:08 UTC by imnasnainaec

Resolves #1131

2021-05-05 20:34 UTC, jasonleenaylor reviewed
> Reviewed 6 of 11 files at r1, 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1142)* status: 10 of 13 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec)

___
*[Backend/Services/MergeService.cs, line 166 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1142#-MZyBlIS6SE5rdeNe5fb:-MZyBlIS6SE5rdeNe5fc:b-ilj409) ([raw file](https://github.com/sillsdev/thecombine/blob/51e0a15fcaa572a64ac708f58d3b4c0c1802bcf8/Backend/Services/MergeService.cs#L166)):*
> ```
> private class DuplicateFinder
> ```

For maintenance purposes (file length) we will want to move this into its own file.
___
*[Backend.Tests/Helper/LevenshteinDistanceTests.cs, line 27 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1142#-MZyCRt8DqlFHUfUXyvd:-MZyCRt8DqlFHUfUXyve:bmn2pyd) ([raw file](https://github.com/sillsdev/thecombine/blob/51e0a15fcaa572a64ac708f58d3b4c0c1802bcf8/Backend.Tests/Helper/LevenshteinDistanceTests.cs#L27)):*
> ```
> AreEqual
> ```

The fluent constraint syntax is preferred for NUnit now.  It makes for easier to read tests and better default failure messages.
So this would be: `Assert.That(_levDist.GetDistance("",""), Is.EqualTo(0));`


<!-- Sent from Reviewable.io -->

2021-05-06 14:08 UTC, imnasnainaec reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1142)* status: 4 of 14 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @jasonleenaylor)

___
*[Backend/Services/MergeService.cs, line 166 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1142#-MZyBlIS6SE5rdeNe5fb:-M_1-YRa0Qij-RRpYC2d:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/51e0a15fcaa572a64ac708f58d3b4c0c1802bcf8/Backend/Services/MergeService.cs#L166)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> private class DuplicateFinder
> ```

For maintenance purposes (file length) we will want to move this into its own file.
</blockquote></details>

*[Backend.Tests/Helper/LevenshteinDistanceTests.cs, line 27 at r2](https://reviewable.io/reviews/sillsdev/thecombine/1142#-MZyCRt8DqlFHUfUXyvd:-M_1-_VhDsG_HP3Ki5OS:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/51e0a15fcaa572a64ac708f58d3b4c0c1802bcf8/Backend.Tests/Helper/LevenshteinDistanceTests.cs#L27)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> AreEqual
> ```

The fluent constraint syntax is preferred for NUnit now.  It makes for easier to read tests and better default failure messages.
So this would be: `Assert.That(_levDist.GetDistance("",""), Is.EqualTo(0));`
</blockquote></details>

Done. x2


<!-- Sent from Reviewable.io -->

2021-05-07 12:08 UTC, johnthagen commented
___
*[Backend/Controllers/MergeController.cs, line 69 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5iOrm2C5mJYt3eYzW:-M_5iOrm2C5mJYt3eYzX:b-4rxrvl) ([raw file](https://github.com/sillsdev/thecombine/blob/ef8ff89575c4d722196c93e42bc0a27d966096b2/Backend/Controllers/MergeController.cs#L69)):*
> ```Smalltalk
>         /// <param name="maxLists"> Max number of lists of potential duplicates. </param>
>         /// <returns> List of Lists of <see cref="Word"/>s. </returns>
>         [HttpGet("dups/{maxInList}/{maxLists}/{userid}")]
> ```

We can use route constraints to do validation of the type of `int` route parameters.

```cs
[HttpGet("dups/{maxInList:int}/{maxLists:int}/{userid}")]
```

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1#route-constraint-reference


<!-- Sent from Reviewable.io -->

2021-05-07 12:12 UTC, johnthagen commented
___
*[Backend/Helper/DuplicateFinder.cs, line 29 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5jR8p70Ggm1Y4dW-f:-M_5jR8p70Ggm1Y4dW-g:bmw738c) ([raw file](https://github.com/sillsdev/thecombine/blob/ef8ff89575c4d722196c93e42bc0a27d966096b2/Backend/Helper/DuplicateFinder.cs#L29)):*
> ```Smalltalk
>         /// each with multiple <see cref="Word"/>s having a common Vernacular.
>         /// </summary>
>         async public Task<List<List<Word>>> GetIdenticalVernWords(
> ```

For consistency, this should be declared with the order `public async`.


<!-- Sent from Reviewable.io -->

2021-05-07 12:12 UTC, johnthagen commented
___
*[Backend/Helper/DuplicateFinder.cs, line 64 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5jadE07ncJlu4Mm2-:-M_5jadE07ncJlu4Mm20:b-p6s4rk) ([raw file](https://github.com/sillsdev/thecombine/blob/ef8ff89575c4d722196c93e42bc0a27d966096b2/Backend/Helper/DuplicateFinder.cs#L64)):*
> ```Smalltalk
>         /// the outer list is ordered by similarity of the first two items in each inner List.
>         /// </returns>
>         async public Task<List<List<Word>>> GetSimilarWords(
> ```

`public async`


<!-- Sent from Reviewable.io -->

2021-05-07 12:15 UTC, johnthagen commented
___
*[Backend/Helper/DuplicateFinder.cs, line 101 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5k9jM2twlD2FDbB-r:-M_5k9jM2twlD2FDbB-s:b-ek4mw5) ([raw file](https://github.com/sillsdev/thecombine/blob/ef8ff89575c4d722196c93e42bc0a27d966096b2/Backend/Helper/DuplicateFinder.cs#L101)):*
> ```Smalltalk
> 
>                 // Insert at correct place in list.
>                 int i = wordLists.FindIndex(pair => score <= pair.Item1);
> ```

Use `var`


<!-- Sent from Reviewable.io -->

2021-05-07 12:16 UTC, johnthagen commented
___
*[Backend/Helper/DuplicateFinder.cs, line 198 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5kJy63ZkEUKN-wX1M:-M_5kJy63ZkEUKN-wX1N:bbwzrfz) ([raw file](https://github.com/sillsdev/thecombine/blob/ef8ff89575c4d722196c93e42bc0a27d966096b2/Backend/Helper/DuplicateFinder.cs#L198)):*
> ```Smalltalk
>         /// and if the Words share a common gloss, then we override the score with this threshold.</param>
>         /// <returns> A double: the adjusted distance between the words. </returns>
>         public double GetWordScore(Word wordA, Word wordB, double? checkGlossThreshold = 1)
> ```

Since `checkGlossThreshold` is a `double`, it's probably best to use `1.0` as the default value for clarity.


<!-- Sent from Reviewable.io -->

2021-05-07 12:16 UTC, johnthagen commented
___
*[Backend/Helper/DuplicateFinder.cs, line 215 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5kUcVAErG6PkbwbxH:-M_5kUcVAErG6PkbwbxI:bkc87z) ([raw file](https://github.com/sillsdev/thecombine/blob/ef8ff89575c4d722196c93e42bc0a27d966096b2/Backend/Helper/DuplicateFinder.cs#L215)):*
> ```Smalltalk
>         /// Check if two <see cref="Word"/>s have <see cref="Gloss"/>es with identical Language and nonempty Def.
>         /// </summary>
>         public bool HaveIdenticalGloss(Word wordA, Word wordB)
> ```

Convert this to a `static` method to limit scope.


<!-- Sent from Reviewable.io -->

2021-05-07 12:20 UTC, johnthagen commented
___
*[Backend/Helper/DuplicateFinder.cs, line 79 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5kvNH19sUsUJPNvr1:-M_5jnqhBOqcBdWWnere:b-w9xpiw) ([raw file](https://github.com/sillsdev/thecombine/blob/ef8ff89575c4d722196c93e42bc0a27d966096b2/Backend/Helper/DuplicateFinder.cs#L79)):*
Rider warns about using `==` for floating point numbers. 

> Equality comparison of floating point numbers. Possible loss of precision when rounding numbers.

It recommends something like:

```cs
Math.Abs(score - currentMax) < TOLERANCE
```


<!-- Sent from Reviewable.io -->

2021-05-07 12:20 UTC, johnthagen commented
___
*[Backend/Helper/DuplicateFinder.cs, line 49 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5lURx0EPsyNodxRjL:-M_5lURx0EPsyNodxRjM:b-s562md) ([raw file](https://github.com/sillsdev/thecombine/blob/ef8ff89575c4d722196c93e42bc0a27d966096b2/Backend/Helper/DuplicateFinder.cs#L49)):*
> ```Smalltalk
>                 {
>                     continue;
>                 };
> ```

Remove redundant `;`


<!-- Sent from Reviewable.io -->

2021-05-07 12:21 UTC, johnthagen commented
___
*[Backend/Helper/DuplicateFinder.cs, line 90 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5l_aa0rWg-vKYs6MH:-M_5l_ab-06ZByG6XNkt:b-s562md) ([raw file](https://github.com/sillsdev/thecombine/blob/ef8ff89575c4d722196c93e42bc0a27d966096b2/Backend/Helper/DuplicateFinder.cs#L90)):*
> ```Smalltalk
>                 {
>                     continue;
>                 };
> ```

Remove redundant `;`


<!-- Sent from Reviewable.io -->

2021-05-07 12:22 UTC, johnthagen commented
___
*[Backend/Helper/DuplicateFinder.cs, line 128 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5lo7N0YpjoQ4-GFH7:-M_5lo7N0YpjoQ4-GFH8:b-hd19dx) ([raw file](https://github.com/sillsdev/thecombine/blob/ef8ff89575c4d722196c93e42bc0a27d966096b2/Backend/Helper/DuplicateFinder.cs#L128)):*
> ```Smalltalk
> 
>         /// <summary> Get from specified List a sub-List with same vern as specified <see cref="Word"/>. </summary>
>         public List<Word> GetIdenticalVernToWord(Word word, List<Word> collection)
> ```

This can be made `private`. Should it?


<!-- Sent from Reviewable.io -->

2021-05-07 12:23 UTC, johnthagen commented
___
*[Backend/Helper/DuplicateFinder.cs, line 198 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5lzUFDqg8E63wydlq:-M_5lzUG1VCr6HIzZXEb:b-tzw5kv) ([raw file](https://github.com/sillsdev/thecombine/blob/ef8ff89575c4d722196c93e42bc0a27d966096b2/Backend/Helper/DuplicateFinder.cs#L198)):*
> ```Smalltalk
>         /// and if the Words share a common gloss, then we override the score with this threshold.</param>
>         /// <returns> A double: the adjusted distance between the words. </returns>
>         public double GetWordScore(Word wordA, Word wordB, double? checkGlossThreshold = 1)
> ```

Since we've added `param` for one parameter, I think we should go ahead and add it from `wordA` and `wordB` for consistency as well


<!-- Sent from Reviewable.io -->

2021-05-07 12:25 UTC, johnthagen commented
___
*[Backend/Helper/DuplicateFinder.cs, line 250 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5mFVG2MygalmEiiY4:-M_5mFVG2MygalmEiiY5:b-ux7jq9) ([raw file](https://github.com/sillsdev/thecombine/blob/ef8ff89575c4d722196c93e42bc0a27d966096b2/Backend/Helper/DuplicateFinder.cs#L250)):*
> ```Smalltalk
>         private double GetScaledDistance(string stringA, string stringB)
>         {
>             return _editDist.GetDistance(stringA, stringB) * 6.0 / (stringA.Length + 1);
> ```

What does this magic `6.0` represent? Could we define a `const` for this if it has some kind of particular significance?

It seems to be a scale, but why is `6.0` chosen? Should this be configurable with a default value?


<!-- Sent from Reviewable.io -->

2021-05-07 12:28 UTC, johnthagen commented
___
*[Backend/Helper/LevenshteinDistance.cs, line 41 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5nImC79Qtkj_ljqqI:-M_5nImC79Qtkj_ljqqJ:b-ek4mw5) ([raw file](https://github.com/sillsdev/thecombine/blob/ef8ff89575c4d722196c93e42bc0a27d966096b2/Backend/Helper/LevenshteinDistance.cs#L41)):*
> ```Smalltalk
>         {
>             int[,] matrix = new int[stringA.Length + 1, stringB.Length + 1];
>             for (int i = 0; i <= stringA.Length; i++)
> ```

Use `var`


<!-- Sent from Reviewable.io -->

2021-05-07 12:28 UTC, johnthagen commented
___
*[Backend/Helper/LevenshteinDistance.cs, line 43 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5nKwh3z3rM6YTjp25:-M_5nKwh3z3rM6YTjp26:b-ek4mw5) ([raw file](https://github.com/sillsdev/thecombine/blob/ef8ff89575c4d722196c93e42bc0a27d966096b2/Backend/Helper/LevenshteinDistance.cs#L43)):*
> ```Smalltalk
>             for (int i = 0; i <= stringA.Length; i++)
>             {
>                 for (int j = 0; j <= stringB.Length; j++)
> ```

Use `var`


<!-- Sent from Reviewable.io -->

2021-05-07 12:29 UTC, johnthagen commented
___
*[Backend/Helper/LevenshteinDistance.cs, line 53 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5nN4L1i2HrNSzf5Ll:-M_5nN4L1i2HrNSzf5Lm:b-ek4mw5) ([raw file](https://github.com/sillsdev/thecombine/blob/ef8ff89575c4d722196c93e42bc0a27d966096b2/Backend/Helper/LevenshteinDistance.cs#L53)):*
> ```Smalltalk
> 
>                     // Calculate other entries recursively.
>                     int scoreDeleteInsert = Math.Min(
> ```

Use `var`


<!-- Sent from Reviewable.io -->

2021-05-07 12:29 UTC, johnthagen commented
___
*[Backend/Helper/LevenshteinDistance.cs, line 48 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5nQuz8cuhwjISQdum:-M_5nQuz8cuhwjISQdun:b-ipkl1p) ([raw file](https://github.com/sillsdev/thecombine/blob/ef8ff89575c4d722196c93e42bc0a27d966096b2/Backend/Helper/LevenshteinDistance.cs#L48)):*
> ```Smalltalk
>                     if (i == 0 || j == 0)
>                     {
>                         matrix[i, j] = this.costDeletion * i + this.costInsertion * j;
> ```

Remove multiple redundant `this` in this function per style guide.


<!-- Sent from Reviewable.io -->

2021-05-07 12:29 UTC, johnthagen commented
___
*[Backend/Helper/LevenshteinDistance.cs, line 57 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5nUbMAw0EraCvANX_:-M_5nUbMAw0EraCvANXa:b-ek4mw5) ([raw file](https://github.com/sillsdev/thecombine/blob/ef8ff89575c4d722196c93e42bc0a27d966096b2/Backend/Helper/LevenshteinDistance.cs#L57)):*
> ```Smalltalk
>                         matrix[i, j - 1] + this.costInsertion
>                     );
>                     int localCostSub = (stringA[i - 1] == stringB[j - 1]) ? 0 : this.costSubstitution;
> ```

Use `var`


<!-- Sent from Reviewable.io -->

2021-05-07 12:35 UTC, johnthagen commented
___
*[Backend/Helper/LevenshteinDistance.cs, line 6 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5oXrD89au29vuAJd-:-M_5oXrD89au29vuAJd0:b-m5hcge) ([raw file](https://github.com/sillsdev/thecombine/blob/ef8ff89575c4d722196c93e42bc0a27d966096b2/Backend/Helper/LevenshteinDistance.cs#L6)):*
> ```Smalltalk
> namespace BackendFramework.Helper
> {
>     public class LevenshteinDistance : IEditDistance
> ```

Rather than implementing this ourselves, should we consider using a third party package? I seem to have found one that is maintained:

- https://github.com/feature23/StringSimilarity.NET
- https://www.nuget.org/packages/F23.StringSimilarity/


<!-- Sent from Reviewable.io -->

2021-05-07 12:39 UTC, johnthagen commented
___
*[Backend/Services/MergeService.cs, line 5 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5pYZN8HcKPfSkCgt9:-M_5pYZO-ntXCqHQjqz2:bki4a3k) ([raw file](https://github.com/sillsdev/thecombine/blob/ef8ff89575c4d722196c93e42bc0a27d966096b2/Backend/Services/MergeService.cs#L5)):*
> ```Smalltalk
> using System.Linq;
> using System.Threading.Tasks;
> using BackendFramework.Helper;
> ```

I'm starting to not like the name `Helper` much as it's becoming a grab bag of `Util` type stuff. Maybe in a follow on we should brainstorm new ways to organize these static, mostly pure set of functions.


<!-- Sent from Reviewable.io -->

2021-05-07 12:41 UTC, johnthagen commented
___
*[Backend.Tests/Helper/DuplicateFinderTests.cs, line 36 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5q6Tx28Wo6qqZvdkP:-M_5q6Tx28Wo6qqZvdkQ:b-ek4mw5) ([raw file](https://github.com/sillsdev/thecombine/blob/ef8ff89575c4d722196c93e42bc0a27d966096b2/Backend.Tests/Helper/DuplicateFinderTests.cs#L36)):*
> ```Smalltalk
>         {
>             const string vern = "Vertacular!";
>             for (int i = 0; i < 10; i++)
> ```

Use `var`


<!-- Sent from Reviewable.io -->

2021-05-07 12:41 UTC, johnthagen commented
___
*[Backend.Tests/Helper/DuplicateFinderTests.cs, line 35 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5q8FF8wS8gz_qH8RN:-M_5q8FF8wS8gz_qH8RO:b136q4j) ([raw file](https://github.com/sillsdev/thecombine/blob/ef8ff89575c4d722196c93e42bc0a27d966096b2/Backend.Tests/Helper/DuplicateFinderTests.cs#L35)):*
> ```Smalltalk
>         public void GetIdenticalVernToWordTest()
>         {
>             const string vern = "Vertacular!";
> ```

Was this typo intentional, or did you mean `Vernacular`?


<!-- Sent from Reviewable.io -->

2021-05-07 12:44 UTC, johnthagen commented
___
*[Backend.Tests/Helper/DuplicateFinderTests.cs, line 36 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5qTACBevYpOrOmphV:-M_5qTACBevYpOrOmphW:b-wv2a1b) ([raw file](https://github.com/sillsdev/thecombine/blob/ef8ff89575c4d722196c93e42bc0a27d966096b2/Backend.Tests/Helper/DuplicateFinderTests.cs#L36)):*
> ```Smalltalk
>         {
>             const string vern = "Vertacular!";
>             for (int i = 0; i < 10; i++)
> ```

What if we added a new `Util.RandomWords(var n)` function to create a `List` of random `Word`s? I wonder if there are only tests we could simplify with that common function.


<!-- Sent from Reviewable.io -->

2021-05-07 12:44 UTC, johnthagen commented
___
*[Backend.Tests/Helper/DuplicateFinderTests.cs, line 65 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5qvoZ92Wrmjbk9562:-M_5qvoZ92Wrmjbk9563:b-ek4mw5) ([raw file](https://github.com/sillsdev/thecombine/blob/ef8ff89575c4d722196c93e42bc0a27d966096b2/Backend.Tests/Helper/DuplicateFinderTests.cs#L65)):*
> ```Smalltalk
>         public void GetSimilarWordsAndMaxScoreTest()
>         {
>             for (int i = 0; i < MaxInList * MaxLists; i++)
> ```

Use `var`


<!-- Sent from Reviewable.io -->

2021-05-07 12:45 UTC, johnthagen commented
___
*[Backend.Tests/Helper/DuplicateFinderTests.cs, line 98 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5r0jE4GgRtdUMTO8w:-M_5r0jE4GgRtdUMTO8x:b-ek4mw5) ([raw file](https://github.com/sillsdev/thecombine/blob/ef8ff89575c4d722196c93e42bc0a27d966096b2/Backend.Tests/Helper/DuplicateFinderTests.cs#L98)):*
> ```Smalltalk
>         public void GetSimilarWordsBlacklistTest()
>         {
>             for (int i = 0; i < MaxInList + 1; i++)
> ```

Use `var`


<!-- Sent from Reviewable.io -->

2021-05-07 12:46 UTC, johnthagen commented
___
*[Backend.Tests/Helper/LevenshteinDistanceTests.cs, line 32 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5rKfpAmsGaT0rTOJu:-M_5rKfpAmsGaT0rTOJv:b-9io9hy) ([raw file](https://github.com/sillsdev/thecombine/blob/ef8ff89575c4d722196c93e42bc0a27d966096b2/Backend.Tests/Helper/LevenshteinDistanceTests.cs#L32)):*
> ```Smalltalk
>         }
> 
>         private static readonly List<Tuple<string, int>> _wordScorePairs = new List<Tuple<string, int>> {
> ```

`static`s should be named `WordScorePairs`


<!-- Sent from Reviewable.io -->

2021-05-07 12:49 UTC, johnthagen commented
___
*[src/utilities.tsx, line 17 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5s-QPAuPwtZ7lygLW:-M_5s-QPAuPwtZ7lygLX:byc67h9) ([raw file](https://github.com/sillsdev/thecombine/blob/ef8ff89575c4d722196c93e42bc0a27d966096b2/src/utilities.tsx#L17)):*
> ```XML
> }
> 
> //quicksort implmentation O(n log n)
> ```

Typo: `implementation`


<!-- Sent from Reviewable.io -->

2021-05-07 12:50 UTC, johnthagen commented
___
*[src/utilities.tsx, line 71 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5sHq0ALelJL8dKwoQ:-M_5sHq0ALelJL8dKwoR:bb613z1) ([raw file](https://github.com/sillsdev/thecombine/blob/ef8ff89575c4d722196c93e42bc0a27d966096b2/src/utilities.tsx#L71)):*
> ```XML
>     this.subsitutionCost = params.subCost;
>   }
>   getDistance(a: string, b: string): number {
> ```

Why is both the frontend and backend implementing this algorithm? Shouldn't just one or the other be responsible for it?


<!-- Sent from Reviewable.io -->

2021-05-07 12:51 UTC, johnthagen commented
___
*[src/utilities.tsx, line 55 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5sQGl7WI2a-4dLrO6:-M_5sQGl7WI2a-4dLrO7:b34b6cx) ([raw file](https://github.com/sillsdev/thecombine/blob/ef8ff89575c4d722196c93e42bc0a27d966096b2/src/utilities.tsx#L55)):*
> ```XML
>   delCost: number;
>   insCost: number;
>   subCost: number; // Must be <= delCost + insCost.
> ```

Should this be enforced in the `constructor` and an exception thrown if this invariant is not upheld?


<!-- Sent from Reviewable.io -->

2021-05-07 13:43 UTC, imnasnainaec reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1142)* status: 11 of 17 files reviewed, 34 unresolved discussions (waiting on @imnasnainaec, @jasonleenaylor, and @johnthagen)

___
*[Backend/Controllers/MergeController.cs, line 66 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5i3_X1zvrDJN_mLoJ:-M_61IU50CakgRVe7JTl:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7ad373e0e8fb0dcf3aaa9e8ecb513d39cae1c3d2/Backend/Controllers/MergeController.cs#L66)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

(I don't think every method that has `projectId` and `userId` needs `param`s for them, but I think if we document *some* of the parameters, it would be cleaner to document them all in that case so a developer isn't surprised if they read the docs for a function).
</blockquote></details>

*[Backend/Controllers/MergeController.cs, line 69 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5iOrm2C5mJYt3eYzW:-M_61N7o8vl0z_wOX5lG:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7ad373e0e8fb0dcf3aaa9e8ecb513d39cae1c3d2/Backend/Controllers/MergeController.cs#L69)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

We can use route constraints to do validation of the type of `int` route parameters.

```cs
[HttpGet("dups/{maxInList:int}/{maxLists:int}/{userid}")]
```

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1#route-constraint-reference
</blockquote></details>

*[Backend/Helper/DuplicateFinder.cs, line 29 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5jR8p70Ggm1Y4dW-f:-M_61OQ50OM4a5Ca2iph:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7ad373e0e8fb0dcf3aaa9e8ecb513d39cae1c3d2/Backend/Helper/DuplicateFinder.cs#L29)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

For consistency, this should be declared with the order `public async`.
</blockquote></details>

*[Backend/Helper/DuplicateFinder.cs, line 49 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5lURx0EPsyNodxRjL:-M_61PmkBvVfZTYkLhVr:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7ad373e0e8fb0dcf3aaa9e8ecb513d39cae1c3d2/Backend/Helper/DuplicateFinder.cs#L49)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Remove redundant `;`
</blockquote></details>

*[Backend/Helper/DuplicateFinder.cs, line 64 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5jadE07ncJlu4Mm2-:-M_61QQsBdBw-OmAUUBv:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7ad373e0e8fb0dcf3aaa9e8ecb513d39cae1c3d2/Backend/Helper/DuplicateFinder.cs#L64)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

`public async`
</blockquote></details>

*[Backend/Helper/DuplicateFinder.cs, line 90 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5l_aa0rWg-vKYs6MH:-M_61Sky9osU8VA-mOqY:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7ad373e0e8fb0dcf3aaa9e8ecb513d39cae1c3d2/Backend/Helper/DuplicateFinder.cs#L90)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Remove redundant `;`
</blockquote></details>

*[Backend/Helper/DuplicateFinder.cs, line 101 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5k9jM2twlD2FDbB-r:-M_61V4e3bukXveafmxZ:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7ad373e0e8fb0dcf3aaa9e8ecb513d39cae1c3d2/Backend/Helper/DuplicateFinder.cs#L101)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Use `var`
</blockquote></details>

Done. x7
___
*[Backend/Helper/DuplicateFinder.cs, line 128 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5lo7N0YpjoQ4-GFH7:-M_61WOm1lcxUX0qibvO:bum4s2) ([raw file](https://github.com/sillsdev/thecombine/blob/7ad373e0e8fb0dcf3aaa9e8ecb513d39cae1c3d2/Backend/Helper/DuplicateFinder.cs#L128)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This can be made `private`. Should it?
</blockquote></details>

I made it public for unit testing.
___
*[Backend/Helper/DuplicateFinder.cs, line 198 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5kJy63ZkEUKN-wX1M:-M_61_FF3KdSZ2iFM45h:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7ad373e0e8fb0dcf3aaa9e8ecb513d39cae1c3d2/Backend/Helper/DuplicateFinder.cs#L198)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Since `checkGlossThreshold` is a `double`, it's probably best to use `1.0` as the default value for clarity.
</blockquote></details>

*[Backend/Helper/DuplicateFinder.cs, line 198 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5lzUFDqg8E63wydlq:-M_61bWbBI1eX8BJbQVl:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7ad373e0e8fb0dcf3aaa9e8ecb513d39cae1c3d2/Backend/Helper/DuplicateFinder.cs#L198)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Since we've added `param` for one parameter, I think we should go ahead and add it from `wordA` and `wordB` for consistency as well
</blockquote></details>

*[Backend/Helper/DuplicateFinder.cs, line 215 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5kUcVAErG6PkbwbxH:-M_61ceY6G1na-mBIBbH:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7ad373e0e8fb0dcf3aaa9e8ecb513d39cae1c3d2/Backend/Helper/DuplicateFinder.cs#L215)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Convert this to a `static` method to limit scope.
</blockquote></details>

Done. x3
___
*[Backend/Helper/DuplicateFinder.cs, line 250 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5mFVG2MygalmEiiY4:-M_61dmO2QRtstdNhXGE:bu3huep) ([raw file](https://github.com/sillsdev/thecombine/blob/7ad373e0e8fb0dcf3aaa9e8ecb513d39cae1c3d2/Backend/Helper/DuplicateFinder.cs#L250)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

What does this magic `6.0` represent? Could we define a `const` for this if it has some kind of particular significance?

It seems to be a scale, but why is `6.0` chosen? Should this be configurable with a default value?
</blockquote></details>

It's a heuristic that we can adjust as developers based on our testing and user feedback--and I felt it needed to increase to 7 based on my recent tests. I don't see enough meaning to that number to name it or expose it directly to user control.
___
*[Backend/Helper/LevenshteinDistance.cs, line 10 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5n5BBEnzeHgnnJnql:-M_628zaCN_T0z4OCNu3:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7ad373e0e8fb0dcf3aaa9e8ecb513d39cae1c3d2/Backend/Helper/LevenshteinDistance.cs#L10)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Should all of these attributes be marked `private`?
</blockquote></details>

*[Backend/Helper/LevenshteinDistance.cs, line 27 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5myhY0f7STO6LKHRq:-M_62AGi7UXS5wyMeaJo:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7ad373e0e8fb0dcf3aaa9e8ecb513d39cae1c3d2/Backend/Helper/LevenshteinDistance.cs#L27)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Remove redundant `this`'s per style guide.
</blockquote></details>

*[Backend/Helper/LevenshteinDistance.cs, line 41 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5nImC79Qtkj_ljqqI:-M_62Aqv6n4XVHHBK9A7:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7ad373e0e8fb0dcf3aaa9e8ecb513d39cae1c3d2/Backend/Helper/LevenshteinDistance.cs#L41)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Use `var`
</blockquote></details>

*[Backend/Helper/LevenshteinDistance.cs, line 43 at r3](https://reviewable.io/reviews/sillsd [...]

2021-05-07 13:59 UTC, imnasnainaec reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1142)* status: 11 of 17 files reviewed, 34 unresolved discussions (waiting on @jasonleenaylor and @johnthagen)

___
*[Backend/Helper/LevenshteinDistance.cs, line 6 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5oXrD89au29vuAJd-:-M_65kuDDkK992-1fJSw:b-1po60f) ([raw file](https://github.com/sillsdev/thecombine/blob/7ad373e0e8fb0dcf3aaa9e8ecb513d39cae1c3d2/Backend/Helper/LevenshteinDistance.cs#L6)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Rather than implementing this ourselves, should we consider using a third party package? I seem to have found one that is maintained:

- https://github.com/feature23/StringSimilarity.NET
- https://www.nuget.org/packages/F23.StringSimilarity/
</blockquote></details>

That would be nice. The benefit to our current Levenshtein distance is that it is generalized with adjustable weights, which we can tweak (similar to the 6.0 you asked about elsewhere) until the dup finder feels right.
___
*[src/utilities.tsx, line 55 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5sQGl7WI2a-4dLrO6:-M_66B3XEW78K8iRzwX_:bqywqh7) ([raw file](https://github.com/sillsdev/thecombine/blob/7ad373e0e8fb0dcf3aaa9e8ecb513d39cae1c3d2/src/utilities.tsx#L55)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Should this be enforced in the `constructor` and an exception thrown if this invariant is not upheld?
</blockquote></details>

I'm not sure it needs to be enforced. It's not that the algorithm fails if `subCost > delCost + insCost`. Rather, it nullifies substitution as a possible cheapest step option to get from one string to another.


<!-- Sent from Reviewable.io -->

2021-05-07 14:03 UTC, johnthagen commented
___
*[Backend.Tests/Helper/DuplicateFinderTests.cs, line 36 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5qTACBevYpOrOmphV:-M_67if980uo6PoNpUOh:bm5hokj) ([raw file](https://github.com/sillsdev/thecombine/blob/7ad373e0e8fb0dcf3aaa9e8ecb513d39cae1c3d2/Backend.Tests/Helper/DuplicateFinderTests.cs#L36)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

This Util is only used for tests. Or do you mean "are other tests"?
</blockquote></details>

I meant "if there are other tests", yes. I seems like if we created this function we could simplify some unit tests (possibly in other test modules as well).


<!-- Sent from Reviewable.io -->

2021-05-07 14:04 UTC, johnthagen commented
___
*[src/utilities.tsx, line 55 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5sQGl7WI2a-4dLrO6:-M_687Kn3Os-yktV5TMN:b-hi8uwq) ([raw file](https://github.com/sillsdev/thecombine/blob/7ad373e0e8fb0dcf3aaa9e8ecb513d39cae1c3d2/src/utilities.tsx#L55)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I'm not sure it needs to be enforced. It's not that the algorithm fails if `subCost > delCost + insCost`. Rather, it nullifies substitution as a possible cheapest step option to get from one string to another.
</blockquote></details>

Could this comment be expanded to include this nuance then?


<!-- Sent from Reviewable.io -->

2021-05-07 14:08 UTC, johnthagen commented
___
*[Backend/Helper/LevenshteinDistance.cs, line 6 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5oXrD89au29vuAJd-:-M_696tJCjRKpSi13quq:b3t3u0t) ([raw file](https://github.com/sillsdev/thecombine/blob/7ad373e0e8fb0dcf3aaa9e8ecb513d39cae1c3d2/Backend/Helper/LevenshteinDistance.cs#L6)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

That would be nice. The benefit to our current Levenshtein distance is that it is generalized with adjustable weights, which we can tweak (similar to the 6.0 you asked about elsewhere) until the dup finder feels right.
</blockquote></details>

Indeed, their implementation seems to not support the weights :https://github.com/feature23/StringSimilarity.NET/blob/main/src/F23.StringSimilarity/Levenshtein.cs#L77


<!-- Sent from Reviewable.io -->

2021-05-07 14:09 UTC, johnthagen reviewed
> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1142)* status: all files reviewed, 5 unresolved discussions (waiting on @imnasnainaec and @jasonleenaylor)



<!-- Sent from Reviewable.io -->

2021-05-07 14:28 UTC, imnasnainaec reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1142)* status: 13 of 19 files reviewed, 5 unresolved discussions (waiting on @imnasnainaec, @jasonleenaylor, and @johnthagen)

___
*[Backend/Helper/DuplicateFinder.cs, line 128 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5lo7N0YpjoQ4-GFH7:-M_6Db1gBFtrGssNhv5a:b-qsfa4e) ([raw file](https://github.com/sillsdev/thecombine/blob/7ad373e0e8fb0dcf3aaa9e8ecb513d39cae1c3d2/Backend/Helper/DuplicateFinder.cs#L128)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Perhaps we could try using `PrivateObject` for this kind of thing?

https://stackoverflow.com/a/15607491

I think for this specific instance, leaving it as `public` seems fine, but for future APIs, let's keep this `PrivateObject` utility in mind.
</blockquote></details>

Ah, cool option.
___
*[Backend/Helper/DuplicateFinder.cs, line 250 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5mFVG2MygalmEiiY4:-M_6Dkwj9wWIZA_lzRHk:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7ad373e0e8fb0dcf3aaa9e8ecb513d39cae1c3d2/Backend/Helper/DuplicateFinder.cs#L250)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Could you add something along those lines to the method docstring? Even having documented that it's using a somewhat arbitrary number we've selected through trial and error would be helpful.
</blockquote></details>

Done.
___
*[Backend.Tests/Helper/DuplicateFinderTests.cs, line 36 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5qTACBevYpOrOmphV:-M_6DiTN3KOX5i33icz6:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7ad373e0e8fb0dcf3aaa9e8ecb513d39cae1c3d2/Backend.Tests/Helper/DuplicateFinderTests.cs#L36)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I meant "if there are other tests", yes. I seems like if we created this function we could simplify some unit tests (possibly in other test modules as well).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-07 14:31 UTC, imnasnainaec reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1142)* status: 12 of 19 files reviewed, 5 unresolved discussions (waiting on @jasonleenaylor and @johnthagen)

___
*[src/utilities.tsx, line 55 at r3](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_5sQGl7WI2a-4dLrO6:-M_6ERoR9tqjPxy7KCx1:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7ad373e0e8fb0dcf3aaa9e8ecb513d39cae1c3d2/src/utilities.tsx#L55)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Could this comment be expanded to include this nuance then?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-07 14:47 UTC, johnthagen commented
___
*[Backend.Tests/Util.cs, line 37 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_6GtavBe6xrdPMIdbB:-M_6GtavBe6xrdPMIdbC:b6c3es3) ([raw file](https://github.com/sillsdev/thecombine/blob/f38d2bf82afbb2ca5f3811a0dd3451676ca42df4/Backend.Tests/Util.cs#L37)):*
> ```Smalltalk
>         {
>             var wordList = new List<Word>();
>             for (var i = 0; i < length; i++)
> ```

I think this could be expressed a little more elegantly with:

```cs
foreach (var _ in Enumerable.Range(0, length))
```

If you do a search in all C# files for `for (var i` I think there are good number of cases where using `Enumerable.Range` could be used to do looping N number of times, without the boilerplate of manually doing the `< length` check and `i++`.

For cases where we need to use `i` in the loop, express as:

```cs
foreach (var i in Enumerable.Range(0, length))
```


<!-- Sent from Reviewable.io -->

2021-05-07 14:48 UTC, johnthagen requested changes
> Reviewed 6 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1142)* status: 18 of 19 files reviewed, 3 unresolved discussions (waiting on @imnasnainaec, @jasonleenaylor, and @johnthagen)



<!-- Sent from Reviewable.io -->

2021-05-07 15:37 UTC, imnasnainaec reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1142)* status: 18 of 19 files reviewed, 3 unresolved discussions (waiting on @jasonleenaylor and @johnthagen)

___
*[Backend.Tests/Util.cs, line 37 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1142#-M_6GtavBe6xrdPMIdbB:-M_6TMFr1jcb3Go6PUyv:bia97qs) ([raw file](https://github.com/sillsdev/thecombine/blob/f38d2bf82afbb2ca5f3811a0dd3451676ca42df4/Backend.Tests/Util.cs#L37)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I think this could be expressed a little more elegantly with:

```cs
foreach (var _ in Enumerable.Range(0, length))
```

If you do a search in all C# files for `for (var i` I think there are good number of cases where using `Enumerable.Range` could be used to do looping N number of times, without the boilerplate of manually doing the `< length` check and `i++`.

For cases where we need to use `i` in the loop, express as:

```cs
foreach (var i in Enumerable.Range(0, length))
```
</blockquote></details>

Future pr.


<!-- Sent from Reviewable.io -->

2021-05-07 15:39 UTC, johnthagen approved these changes
> Reviewed 1 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1142)* status: all files reviewed, 2 unresolved discussions (waiting on @jasonleenaylor)



<!-- Sent from Reviewable.io -->

2021-05-07 17:18 UTC, jasonleenaylor approved these changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1142)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @imnasnainaec)



<!-- Sent from Reviewable.io -->

2021-05-07 17:20 UTC, merged