Implement user management functionality in project settings
sillsdev/TheCombine pull request #1253
Opened 2021-07-14 21:27 UTC by WeJamUS

Closes #940

2021-07-15 16:12 UTC, imnasnainaec requested changes
> Reviewed 1 of 8 files at r2, 6 of 8 files at r3, 4 of 8 files at r4, 1 of 2 files at r5, 2 of 2 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1253)* status: 14 of 19 files reviewed, 8 unresolved discussions (waiting on @jasonleenaylor and @WeJamUS)

___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 80 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Meetu7X20rHTHzW1N-j:-Meetu7X20rHTHzW1N-k:bx4lcha) ([raw file](https://github.com/sillsdev/thecombine/blob/ce7a5852f7d0888f77825109691e9bab942b5a35/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L80)):*
> ```XML
>   }
> 
>   // TODO: Add the correct text for toast
> ```

Can this TODO comment be removed?
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 88 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MeeuKwxAnQcCfRgyit9:-MeeuKwy8eoBpv2eEwzn:bfb7va) ([raw file](https://github.com/sillsdev/thecombine/blob/ce7a5852f7d0888f77825109691e9bab942b5a35/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L88)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>       .then(this.handleRemoveUserDialogClose.bind(this))
>       .then(() => {
>         this.setState({ anchorEl: undefined });
>       })
> ```
</details>

Similar to comments below, try
```
       .then(() => this.handleRemoveUserDialogClose())
       .then(() => this.setState({ anchorEl: undefined }))
```
(...here and in similar lines.)
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 94 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MeeujJh2vm5urkSlTet:-MeeujJh2vm5urkSlTeu:b9nq8m) ([raw file](https://github.com/sillsdev/thecombine/blob/ce7a5852f7d0888f77825109691e9bab942b5a35/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L94)):*
> ```XML
>       })
>       .catch((err: string) => {
>         console.log(err);
> ```

`console.error(err)` is preferable for errors.
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 99 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Meeuqq6Bf-u3D95dLbq:-Meeuqq6Bf-u3D95dLbr:bbn37co) ([raw file](https://github.com/sillsdev/thecombine/blob/ce7a5852f7d0888f77825109691e9bab942b5a35/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L99)):*
> ```XML
>   }
> 
>   // TODO: Add the correct text for toast
> ```

Can this TODO comment be removed now?
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 182 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MeevCOPEFkmSxNgD-vO:-MeevCOPEFkmSxNgD-vP:b-oqxpr) ([raw file](https://github.com/sillsdev/thecombine/blob/ce7a5852f7d0888f77825109691e9bab942b5a35/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L182)):*
> ```
>     console.log(this.state.projUserRoles);
>     console.log(userRoleId);
> ```
These console.logs probably should be removed now.
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 238 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MeevXq1AxkkZENHHQmz:-MeevXq1AxkkZENHHQn-:b-m5rtpy) ([raw file](https://github.com/sillsdev/thecombine/blob/ce7a5852f7d0888f77825109691e9bab942b5a35/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L238)):*
> ```
>         var hi = this.isProjectAdmin(user.projectRoles[currentProjectId]);
>         console.log(hi);
>         if (hi) {
> ```
This doesn't look like it was intended for the final form. :)
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 240 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Meet7AwBMmbOG-d8ar4:-Meet7AwBMmbOG-d8ar5:b-qmm50u) ([raw file](https://github.com/sillsdev/thecombine/blob/ce7a5852f7d0888f77825109691e9bab942b5a35/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L240)):*
> ```XML
>         if (hi) {
>           adminOption = (
>             <MenuItem onClick={this.handleRemoveAdminDialogOpen.bind(this)}>
> ```

Although present in some parts of our code, we generally try to avoid binding local functions. For example, instead of `this.handleRemoveAdminDialogOpen.bind(this)`, use `()=>this.handleRemoveAdminDialogOpen()`.
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 292 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MeetZqbAQ-lBgYMdXdI:-MeetZqbAQ-lBgYMdXdJ:b-d7u120) ([raw file](https://github.com/sillsdev/thecombine/blob/ce7a5852f7d0888f77825109691e9bab942b5a35/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L292)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>               onClose={() => {
>                 this.setState({
>                   anchorEl: undefined,
>                 });
>               }}
> ```
</details>

I think `onClose={() => this.setState({ anchorEl: undefined })}` is short enough to fit in one line.


<!-- Sent from Reviewable.io -->

2021-07-15 16:40 UTC, WeJamUS commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 240 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Meet7AwBMmbOG-d8ar4:-Mef1h4O8BAVgpdfoujN:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/ce7a5852f7d0888f77825109691e9bab942b5a35/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L240)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Although present in some parts of our code, we generally try to avoid binding local functions. For example, instead of `this.handleRemoveAdminDialogOpen.bind(this)`, use `()=>this.handleRemoveAdminDialogOpen()`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-15 16:41 UTC, WeJamUS commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 238 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MeevXq1AxkkZENHHQmz:-Mef1jOP3iHklMLHXZxW:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/ce7a5852f7d0888f77825109691e9bab942b5a35/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L238)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>         var hi = this.isProjectAdmin(user.projectRoles[currentProjectId]);
>         console.log(hi);
>         if (hi) {
> ```
This doesn't look like it was intended for the final form. :)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-15 16:41 UTC, WeJamUS commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 182 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MeevCOPEFkmSxNgD-vO:-Mef1oYu-806lALJnYn2:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/ce7a5852f7d0888f77825109691e9bab942b5a35/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L182)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>     console.log(this.state.projUserRoles);
>     console.log(userRoleId);
> ```
These console.logs probably should be removed now.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-15 17:44 UTC, imnasnainaec requested changes
> Reviewed 1 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1253)* status: 14 of 19 files reviewed, 8 unresolved discussions (waiting on @imnasnainaec, @jasonleenaylor, and @WeJamUS)

___
*[Backend/Controllers/UserRoleController.cs, line 125 at r9](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MefDxjp-p0yZlTRn-bQ:-MefDxjqDsMG-VEuMHDe:byq4zev) ([raw file](https://github.com/sillsdev/thecombine/blob/05da6743c3660e03196aba153841da0036d719be/Backend/Controllers/UserRoleController.cs#L125)):*
> ```Smalltalk
>         }
> 
>         /// <summary> Deletes <see cref="UserRole"/> with specified id </summary>
> ```

`<summary>` needs to be updated
___
*[Backend.Tests/Controllers/UserRoleControllerTests.cs, line 193 at r9](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MefEqtPEcCOSrVrbSh_:-MefEqtPEcCOSrVrbSha:b57h400) ([raw file](https://github.com/sillsdev/thecombine/blob/05da6743c3660e03196aba153841da0036d719be/Backend.Tests/Controllers/UserRoleControllerTests.cs#L193)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>             var userId = _userRepo.Create(user).Result!.Id;
>             Assert.That(_userRoleRepo.GetAllUserRoles(_projId).Result, Has.Count.EqualTo(1));
>             _ = _userRoleController.DeleteUserRole(_projId, userId).Result;
>             Assert.That(_userRoleRepo.GetAllUserRoles(_projId).Result, Has.Count.EqualTo(0));
> ```
</details>

It would be good to add a pair of `Asserts` to test that the user in the `_userRepo` had the user role and then didn't.
___
*[src/backend/index.ts, line 462 at r9](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MefFI5V95-bOaKO3mu6:-MefFI5W2yb3wfxHSOGi:b35zdqd) ([raw file](https://github.com/sillsdev/thecombine/blob/05da6743c3660e03196aba153841da0036d719be/src/backend/index.ts#L462)):*
> ```
> ): Promise<void> {
> ...
>   return (await userRoleApi.deleteUserRole(params, defaultOptions())).data;
> ```
If the return type is `Promise(void)`, then the final line can be just `await userRoleApi.deleteUserRole(params, defaultOptions())`.
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 274 at r9](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MefCUhqE0Vo9znXl_NI:-MefCUhqE0Vo9znXl_NJ:bqjs41x) ([raw file](https://github.com/sillsdev/thecombine/blob/05da6743c3660e03196aba153841da0036d719be/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L274)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>               handleAccept={this.removeUser.bind(this, [user.id])}
>...
>               handleAccept={this.makeAdmin.bind(this, [user.id])}
>...
>               handleAccept={this.removeAdmin.bind(this, [user.id])}
> ```
</details>

Three more `bind`s to replace.


<!-- Sent from Reviewable.io -->

2021-07-15 17:53 UTC, WeJamUS commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 88 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MeeuKwxAnQcCfRgyit9:-MefIJ8T5xFTXdOwQjyU:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/ce7a5852f7d0888f77825109691e9bab942b5a35/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L88)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>       .then(this.handleRemoveUserDialogClose.bind(this))
>       .then(() => {
>         this.setState({ anchorEl: undefined });
>       })
> ```
Similar to comments below, try
```
       .then(() => this.handleRemoveUserDialogClose())
       .then(() => this.setState({ anchorEl: undefined }))
```
(...here and in similar lines.)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-15 17:53 UTC, WeJamUS commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 94 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MeeujJh2vm5urkSlTet:-MefIKBv6npOb3ek6smr:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/ce7a5852f7d0888f77825109691e9bab942b5a35/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L94)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`console.error(err)` is preferable for errors.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-15 17:53 UTC, WeJamUS commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 80 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Meetu7X20rHTHzW1N-j:-MefILH6BcmQEukNjxHW:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/ce7a5852f7d0888f77825109691e9bab942b5a35/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L80)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Can this TODO comment be removed?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-15 17:53 UTC, WeJamUS commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 99 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Meeuqq6Bf-u3D95dLbq:-MefIOv_4fBTNdmxsiu5:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/ce7a5852f7d0888f77825109691e9bab942b5a35/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L99)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Can this TODO comment be removed now?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-15 17:55 UTC, imnasnainaec requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1253)* status: 14 of 19 files reviewed, 7 unresolved discussions (waiting on @imnasnainaec, @jasonleenaylor, and @WeJamUS)

___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 220 at r9](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MefHGFf5aK0pFi5btpO:-MefHGFf5aK0pFi5btpP:bu4fo9q) ([raw file](https://github.com/sillsdev/thecombine/blob/05da6743c3660e03196aba153841da0036d719be/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L220)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
>   private handleRemoveUserDialogOpen() {
>     this.setState({ removeUserDialogOpen: true });
>   }
>   ..
>   private handleMakeAdminDialogOpen() {
>     this.setState({ makeAdminDialogOpen: true });
>   }
>   ...
>   private handleRemoveAdminDialogOpen() {
>     this.setState({ removeAdminDialogOpen: true });
>   }
> ```
</details>

I think it would be nice to add `anchorEl: undefined` inside the `setState` of each `...DialogOpen` handle for a cleaner look. As a side-effect, you could then remove a `.then(...` from the chain of events after Confirm is selected.


<!-- Sent from Reviewable.io -->

2021-07-15 17:56 UTC, WeJamUS commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 274 at r9](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MefCUhqE0Vo9znXl_NI:-MefJ2LdCwbfXMv8Hwdf:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/05da6743c3660e03196aba153841da0036d719be/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L274)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>               handleAccept={this.removeUser.bind(this, [user.id])}
>...
>               handleAccept={this.makeAdmin.bind(this, [user.id])}
>...
>               handleAccept={this.removeAdmin.bind(this, [user.id])}
> ```
Three more `bind`s to replace.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-15 17:57 UTC, WeJamUS commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 292 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MeetZqbAQ-lBgYMdXdI:-MefJCT1D4Pf_UOKJE6h:bjoctjp) ([raw file](https://github.com/sillsdev/thecombine/blob/ce7a5852f7d0888f77825109691e9bab942b5a35/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L292)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>               onClose={() => {
>                 this.setState({
>                   anchorEl: undefined,
>                 });
>               }}
> ```
I think `onClose={() => this.setState({ anchorEl: undefined })}` is short enough to fit in one line.
</blockquote></details>

The autoformat on save for some reason is splitting it into multiple lines.


<!-- Sent from Reviewable.io -->

2021-07-15 18:01 UTC, imnasnainaec reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1253)* status: 14 of 19 files reviewed, 8 unresolved discussions (waiting on @imnasnainaec, @jasonleenaylor, and @WeJamUS)

___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 292 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MeetZqbAQ-lBgYMdXdI:-MefJgZt3AMVrlI4C3pO:b-xsexbj) ([raw file](https://github.com/sillsdev/thecombine/blob/ce7a5852f7d0888f77825109691e9bab942b5a35/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L292)):*
<details><summary><i>Previously, WeJamUS (James Wu) wrote…</i></summary><blockquote>

The autoformat on save for some reason is splitting it into multiple lines.
</blockquote></details>

That's fine. But since it's a single function call, it doesn't need the `{ ... };` wrapper after the `=>`.


<!-- Sent from Reviewable.io -->

2021-07-15 18:06 UTC, WeJamUS commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 292 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MeetZqbAQ-lBgYMdXdI:-MefLJEt8D1RvLLQckYQ:btn461w) ([raw file](https://github.com/sillsdev/thecombine/blob/ce7a5852f7d0888f77825109691e9bab942b5a35/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L292)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

That's fine. But since it's a single function call, it doesn't need the `{ ... };` wrapper after the `=>`.
</blockquote></details>

Got it


<!-- Sent from Reviewable.io -->

2021-07-15 18:18 UTC, WeJamUS commented
___
*[src/backend/index.ts, line 462 at r9](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MefFI5V95-bOaKO3mu6:-MefNynD-Q96it-yBQ1m:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/05da6743c3660e03196aba153841da0036d719be/src/backend/index.ts#L462)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> ): Promise<void> {
> ...
>   return (await userRoleApi.deleteUserRole(params, defaultOptions())).data;
> ```
If the return type is `Promise(void)`, then the final line can be just `await userRoleApi.deleteUserRole(params, defaultOptions())`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-15 18:20 UTC, WeJamUS commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 274 at r9](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MefCUhqE0Vo9znXl_NI:-MefO0Li4YQy33SfC3fe:bjy8f3v) ([raw file](https://github.com/sillsdev/thecombine/blob/05da6743c3660e03196aba153841da0036d719be/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L274)):*
<details><summary><i>Previously, WeJamUS (James Wu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I now have () => this.removeAdmin(user.id) and added a parameter to removeAdmin. The functionality seems to work fine but the linter is not happy about "Function declared in a loop contains unsafe references to variable(s) 'user'"


<!-- Sent from Reviewable.io -->

2021-07-15 20:03 UTC, imnasnainaec requested changes
> Reviewed 1 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1253)* status: 15 of 19 files reviewed, 4 unresolved discussions (waiting on @imnasnainaec, @jasonleenaylor, and @WeJamUS)

___
*[Backend/Controllers/UserRoleController.cs, line 125 at r9](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MefDxjp-p0yZlTRn-bQ:-Mefkezl5qyEdm9voh_9:b-5eyhvp) ([raw file](https://github.com/sillsdev/thecombine/blob/05da6743c3660e03196aba153841da0036d719be/Backend/Controllers/UserRoleController.cs#L125)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`<summary>` needs to be updated
</blockquote></details>

Deletes <see cref="UserRole"/> for specified projectId and userId.
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 274 at r9](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MefCUhqE0Vo9znXl_NI:-MefieN24NVB78WEoXIX:b5ddgbh) ([raw file](https://github.com/sillsdev/thecombine/blob/05da6743c3660e03196aba153841da0036d719be/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L274)):*
<details><summary><i>Previously, WeJamUS (James Wu) wrote…</i></summary><blockquote>

I now have () => this.removeAdmin(user.id) and added a parameter to removeAdmin. The functionality seems to work fine but the linter is not happy about "Function declared in a loop contains unsafe references to variable(s) 'user'"
</blockquote></details>

One idea:
Right after `user` is defined in the `for` loop, add `const userId = user.id;` and use that literal instead.
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 222 at r10](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Mefiw4o4g8X1oHuccWE:-Mefiw4o4g8X1oHuccWF:bp4bpjw) ([raw file](https://github.com/sillsdev/thecombine/blob/fda5983fc6d199c4abc36dab1d97080241e33e27/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L222)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>     var userList: React.ReactElement<ListItemProps>[] = [];
>     var manageUser: React.ReactElement<ElementType>;
>     var adminOption: React.ReactElement<MenuItemProps>;
>     ...
>     for (var i = 0; i < sortedUserList.length; i++) {
>       var user = sortedUserList[i];
> ```
</details>


We generally avoid the older `var` and rather:
* use `let` for variables that are (re)assigned later, like `manageUser`, `adminOption`, `i` here;
* use `const` for variables that aren't (re)assigned later, even if they are mutable, like `userList`, `user` here. 


<!-- Sent from Reviewable.io -->

2021-07-15 23:15 UTC, WeJamUS commented
___
*[Backend.Tests/Controllers/UserRoleControllerTests.cs, line 193 at r9](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MefEqtPEcCOSrVrbSh_:-MegS00lD6OqODkrqZ1I:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/05da6743c3660e03196aba153841da0036d719be/Backend.Tests/Controllers/UserRoleControllerTests.cs#L193)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>             var userId = _userRepo.Create(user).Result!.Id;
>             Assert.That(_userRoleRepo.GetAllUserRoles(_projId).Result, Has.Count.EqualTo(1));
>             _ = _userRoleController.DeleteUserRole(_projId, userId).Result;
>             Assert.That(_userRoleRepo.GetAllUserRoles(_projId).Result, Has.Count.EqualTo(0));
> ```
It would be good to add a pair of `Asserts` to test that the user in the `_userRepo` had the user role and then didn't.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-15 23:15 UTC, WeJamUS commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 222 at r10](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Mefiw4o4g8X1oHuccWE:-MegS29X1fKEnVx2TfLK:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/fda5983fc6d199c4abc36dab1d97080241e33e27/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L222)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>     var userList: React.ReactElement<ListItemProps>[] = [];
>     var manageUser: React.ReactElement<ElementType>;
>     var adminOption: React.ReactElement<MenuItemProps>;
>     ...
>     for (var i = 0; i < sortedUserList.length; i++) {
>       var user = sortedUserList[i];
> ```

We generally avoid the older `var` and rather:
* use `let` for variables that are (re)assigned later, like `manageUser`, `adminOption`, `i` here;
* use `const` for variables that aren't (re)assigned later, even if they are mutable, like `userList`, `user` here. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-15 23:15 UTC, WeJamUS commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 274 at r9](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MefCUhqE0Vo9znXl_NI:-MegS3K-ERs_ZHjFqya5:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/05da6743c3660e03196aba153841da0036d719be/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L274)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

One idea:
Right after `user` is defined in the `for` loop, add `const userId = user.id;` and use that literal instead.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-15 23:15 UTC, WeJamUS commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 220 at r9](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MefHGFf5aK0pFi5btpO:-MefJ3Gs33cELwhotFzP:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/05da6743c3660e03196aba153841da0036d719be/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L220)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>   private handleRemoveUserDialogOpen() {
>     this.setState({ removeUserDialogOpen: true });
>   }
>   ..
>   private handleMakeAdminDialogOpen() {
>     this.setState({ makeAdminDialogOpen: true });
>   }
>   ...
>   private handleRemoveAdminDialogOpen() {
>     this.setState({ removeAdminDialogOpen: true });
>   }
> ```
I think it would be nice to add `anchorEl: undefined` inside the `setState` of each `...DialogOpen` handle for a cleaner look. As a side-effect, you could then remove a `.then(...` from the chain of events after Confirm is selected.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-15 23:15 UTC, WeJamUS commented
___
*[Backend/Controllers/UserRoleController.cs, line 125 at r9](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MefDxjp-p0yZlTRn-bQ:-MegS6NfCVgodr4khKBU:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/05da6743c3660e03196aba153841da0036d719be/Backend/Controllers/UserRoleController.cs#L125)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Deletes <see cref="UserRole"/> for specified projectId and userId.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-16 12:18 UTC, johnthagen commented
___
*[Backend/Controllers/UserRoleController.cs, line 148 at r11](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MejF3ld5ibBcoVTiPHL:-MejF3ld5ibBcoVTiPHM:bx85u03) ([raw file](https://github.com/sillsdev/thecombine/blob/139ab03724fa7c6db3bfe43aecfddb9e69ad1a13/Backend/Controllers/UserRoleController.cs#L148)):*
> ```Smalltalk
>                 return NotFound(userId);
>             }
>             else
> ```

This `else` is redundant and can be removed. In general we prefer to reduce indentation as much as possible as it lowers cognitive load.


<!-- Sent from Reviewable.io -->

2021-07-16 12:23 UTC, johnthagen commented
___
*[Backend/Controllers/UserRoleController.cs, line 127 at r11](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MejGFfQ-AfZGF4STy4s:-MejGFfQ-AfZGF4STy4t:b-woyttl) ([raw file](https://github.com/sillsdev/thecombine/blob/139ab03724fa7c6db3bfe43aecfddb9e69ad1a13/Backend/Controllers/UserRoleController.cs#L127)):*
> ```Smalltalk
>         /// <summary> Deletes the <see cref="UserRole"/> for the specified projectId and userId </summary>
>         [HttpDelete("{userId}", Name = "DeleteUserRole")]
>         [ProducesResponseType(StatusCodes.Status200OK)]
> ```

I believe we should add`Type = typeof(bool))` to this response type now that we are returning a `bool` inside the `Ok`.


<!-- Sent from Reviewable.io -->

2021-07-16 12:27 UTC, johnthagen commented
___
*[Backend.Tests/Controllers/UserRoleControllerTests.cs, line 188 at r11](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MejH9lP-4L8KUJKKa8a:-MejH9lP-4L8KUJKKa8b:b-c981tt) ([raw file](https://github.com/sillsdev/thecombine/blob/139ab03724fa7c6db3bfe43aecfddb9e69ad1a13/Backend.Tests/Controllers/UserRoleControllerTests.cs#L188)):*
> ```Smalltalk
>             var user = new User { ProjectRoles = { [_projId] = userRole.Id } };
>             var userId = _userRepo.Create(user).Result!.Id;
>             KeyValuePair<string, string> projectRole = new KeyValuePair<string, string>(_projId, userRole.Id);
> ```

Use `var`, though actually this variable doesn't seem to be used at all, so should we just remove it?


<!-- Sent from Reviewable.io -->

2021-07-16 12:28 UTC, johnthagen commented
___
*[Backend.Tests/Controllers/UserRoleControllerTests.cs, line 199 at r11](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MejHQdSAamYHtqMOhUh:-MejHQdSAamYHtqMOhUi:bbbiqcp) ([raw file](https://github.com/sillsdev/thecombine/blob/139ab03724fa7c6db3bfe43aecfddb9e69ad1a13/Backend.Tests/Controllers/UserRoleControllerTests.cs#L199)):*
> ```Smalltalk
>             Assert.That(_userRoleRepo.GetAllUserRoles(_projId).Result, Has.Count.EqualTo(0));
>             fetchedUser = _userRepo.GetUser(userId).Result ?? throw new System.Exception();
>             Assert.That(!fetchedUser.ProjectRoles.ContainsKey(_projId));
> ```

These might be more readable as `Assert.False()` rathe than `Assert.That(!)` but I don't have a strong opinion.


<!-- Sent from Reviewable.io -->

2021-07-16 12:29 UTC, johnthagen commented
___
*[src/backend/index.ts, line 456 at r11](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MejHjzg6MaYf6Sy2T5v:-MejHjzg6MaYf6Sy2T5w:b-7c2suc) ([raw file](https://github.com/sillsdev/thecombine/blob/139ab03724fa7c6db3bfe43aecfddb9e69ad1a13/src/backend/index.ts#L456)):*
> ```XML
>   userId: string
> ): Promise<void> {
>   console.log(userId);
> ```

We probably don't want to leave any `console.log`s in the final merge.


<!-- Sent from Reviewable.io -->

2021-07-16 12:34 UTC, johnthagen commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 110 at r11](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MejIpK0-wROXxq6wzwh:-MejIpK0-wROXxq6wzwi:b-q6xxwa) ([raw file](https://github.com/sillsdev/thecombine/blob/139ab03724fa7c6db3bfe43aecfddb9e69ad1a13/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L110)):*
> ```XML
>       .then(() => {
>         toast(
>           <Translate id="projectSettings.userManagement.makeAdminToastSuccess" />
> ```

Since this string is duplicated twice, should we define it once as a `const` and reuse it?


<!-- Sent from Reviewable.io -->

2021-07-16 12:34 UTC, johnthagen commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 129 at r11](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MejIv905gvfCihQHmgM:-MejIv905gvfCihQHmgN:b-q6xxwa) ([raw file](https://github.com/sillsdev/thecombine/blob/139ab03724fa7c6db3bfe43aecfddb9e69ad1a13/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L129)):*
> ```XML
>       .then(() => {
>         toast(
>           <Translate id="projectSettings.userManagement.removeAdminToastSuccess" />
> ```

Since this string is duplicated twice, should we define it once as a `const` and reuse it?


<!-- Sent from Reviewable.io -->

2021-07-16 12:36 UTC, johnthagen commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 156 at r11](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MejJ5-U4g9b-eOQ9PHf:-MejJ5-U4g9b-eOQ9PHg:b-6xbld6) ([raw file](https://github.com/sillsdev/thecombine/blob/139ab03724fa7c6db3bfe43aecfddb9e69ad1a13/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L156)):*
> ```XML
>     getUserRoles()
>       .then((projUserRoles) => this.setState({ projUserRoles }))
>       .catch((err) => console.error(err));
> ```

@imnasnainaec Off topic, but this makes me think about https://github.com/sillsdev/TheCombine/issues/1125 in general that perhaps we want to take a look at error handling in general in the Combine frontend. I'm worried that many errors are missed because they don't make any noise in the UI. Even if we did a common snackbar pop up with these kinds of things, we might catch more of these errors.


<!-- Sent from Reviewable.io -->

2021-07-16 12:40 UTC, johnthagen commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 221 at r11](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MejJu5O1tM1hO4I_UnH:-MejJu5P7hY65DMGWW7m:bf0pvda) ([raw file](https://github.com/sillsdev/thecombine/blob/139ab03724fa7c6db3bfe43aecfddb9e69ad1a13/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L221)):*
> ```XML
>     const sortedUserList = this.getSortedUsers();
> 
>     for (let i = 0; i < sortedUserList.length; i++) {
> ```

This `for` loop could be simplified into:

```ts
sortedUserList.forEach(user => {
  ...
}
```

This removes a lot of error prone boilerplate around `i` and length checks.


<!-- Sent from Reviewable.io -->

2021-07-16 12:41 UTC, johnthagen requested changes
> Reviewed 1 of 2 files at r9, 3 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1253)* status: all files reviewed, 13 unresolved discussions (waiting on @imnasnainaec, @jasonleenaylor, and @WeJamUS)



<!-- Sent from Reviewable.io -->

2021-07-16 16:19 UTC, WeJamUS commented
___
*[src/backend/index.ts, line 456 at r11](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MejHjzg6MaYf6Sy2T5v:-Mek6N3YE92MhZ2cGHUW:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/139ab03724fa7c6db3bfe43aecfddb9e69ad1a13/src/backend/index.ts#L456)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

We probably don't want to leave any `console.log`s in the final merge.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-16 16:19 UTC, WeJamUS commented
___
*[Backend.Tests/Controllers/UserRoleControllerTests.cs, line 188 at r11](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MejH9lP-4L8KUJKKa8a:-Mek6PhQA0RuoHH_7Nyg:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/139ab03724fa7c6db3bfe43aecfddb9e69ad1a13/Backend.Tests/Controllers/UserRoleControllerTests.cs#L188)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Use `var`, though actually this variable doesn't seem to be used at all, so should we just remove it?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-16 16:19 UTC, WeJamUS commented
___
*[Backend/Controllers/UserRoleController.cs, line 148 at r11](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MejF3ld5ibBcoVTiPHL:-Mek6Qkd4GjrPLbMxEdk:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/139ab03724fa7c6db3bfe43aecfddb9e69ad1a13/Backend/Controllers/UserRoleController.cs#L148)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This `else` is redundant and can be removed. In general we prefer to reduce indentation as much as possible as it lowers cognitive load.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-16 16:19 UTC, WeJamUS commented
___
*[Backend/Controllers/UserRoleController.cs, line 127 at r11](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MejGFfQ-AfZGF4STy4s:-Mek6RfgA7PXOAVvAkje:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/139ab03724fa7c6db3bfe43aecfddb9e69ad1a13/Backend/Controllers/UserRoleController.cs#L127)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I believe we should add`Type = typeof(bool))` to this response type now that we are returning a `bool` inside the `Ok`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-16 16:19 UTC, WeJamUS commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 221 at r11](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MejJu5O1tM1hO4I_UnH:-Mek6UILBA3ZyTl5vced:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/139ab03724fa7c6db3bfe43aecfddb9e69ad1a13/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L221)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This `for` loop could be simplified into:

```ts
sortedUserList.forEach(user => {
  ...
}
```

This removes a lot of error prone boilerplate around `i` and length checks.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-16 17:42 UTC, johnthagen reviewed
> Reviewed 3 of 4 files at r12, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1253)* status: all files reviewed, 7 unresolved discussions (waiting on @imnasnainaec, @jasonleenaylor, and @WeJamUS)



<!-- Sent from Reviewable.io -->

2021-07-16 19:57 UTC, johnthagen commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 244 at r14](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Mekt70QAbV3lbbcPFwA:-Mekt70QAbV3lbbcPFwB:b-ulpp0y) ([raw file](https://github.com/sillsdev/thecombine/blob/862241230a450cc022f4fb8d2d73c6e9e0f35960/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L244)):*
> ```XML
>       ) {
>         if (this.isProjectAdmin(user.projectRoles[currentProjectId])) {
>           console.log(user.username + " is admin");
> ```

Probably wouldn't want this `console.log` to end up in the final merge.


<!-- Sent from Reviewable.io -->

2021-07-16 19:59 UTC, johnthagen commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 261 at r14](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MektCDh2EePfo41ftUo:-MektCDh2EePfo41ftUp:b-tfv6ag) ([raw file](https://github.com/sillsdev/thecombine/blob/862241230a450cc022f4fb8d2d73c6e9e0f35960/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L261)):*
> ```XML
>             <CancelConfirmDialog
>               open={this.state.removeUserDialogOpen}
>               textId={projectSettingsTranslation + "removeUserWarning"}
> ```

Can we use string interpolation here to make this a little more concise?

```
`${projectSettingsTranslation}removeUserWarning`
```

This can be used on the other usages of `string` `+` as well.


<!-- Sent from Reviewable.io -->

2021-07-16 19:59 UTC, johnthagen requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1253)* status: 18 of 19 files reviewed, 9 unresolved discussions (waiting on @imnasnainaec, @jasonleenaylor, @johnthagen, and @WeJamUS)



<!-- Sent from Reviewable.io -->

2021-07-16 20:33 UTC, WeJamUS commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 244 at r14](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Mekt70QAbV3lbbcPFwA:-Mel0Zu0D1fYCrycrGnN:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/862241230a450cc022f4fb8d2d73c6e9e0f35960/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L244)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Probably wouldn't want this `console.log` to end up in the final merge.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-16 20:33 UTC, WeJamUS commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 261 at r14](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MektCDh2EePfo41ftUo:-Mel0c7f7TCfXKLZr1_y:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/862241230a450cc022f4fb8d2d73c6e9e0f35960/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L261)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Can we use string interpolation here to make this a little more concise?

```
`${projectSettingsTranslation}removeUserWarning`
```

This can be used on the other usages of `string` `+` as well.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-17 17:20 UTC, johnthagen reviewed
> Reviewed 1 of 1 files at r15.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1253)* status: all files reviewed, 7 unresolved discussions (waiting on @imnasnainaec, @jasonleenaylor, and @WeJamUS)



<!-- Sent from Reviewable.io -->

2021-07-17 17:21 UTC, johnthagen approved these changes
> Reviewed 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1253)* status: all files reviewed, 7 unresolved discussions (waiting on @imnasnainaec, @jasonleenaylor, and @WeJamUS)



<!-- Sent from Reviewable.io -->

2021-07-19 15:26 UTC, imnasnainaec requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1253)* status: 18 of 19 files reviewed, 8 unresolved discussions (waiting on @jasonleenaylor, @johnthagen, and @WeJamUS)

___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 277 at r17](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MezMdHc0MeeVEbZA5Y8:-MezMdHc0MeeVEbZA5Y9:b-lhtk9h) ([raw file](https://github.com/sillsdev/thecombine/blob/86c1b0d1c16b0d3f4bbbe77eafec7e21479ac59d/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L277)):*
> ```XML
>               handleAccept={() => this.removeAdmin(user.id)}
>             />
>             <Tooltip title="Manage User" placement="right">
> ```

Please add text for "Manage User" to `translations.json`.
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 309 at r17](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MezMSfA6TmtNTV1xeqO:-MezMSfA6TmtNTV1xeqP:bd1tppe) ([raw file](https://github.com/sillsdev/thecombine/blob/86c1b0d1c16b0d3f4bbbe77eafec7e21479ac59d/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L309)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>           <Tooltip title="You cannot edit this user">
>             <IconButton disabled>
>               <MoreVertIcon />
>             </IconButton>
>           </Tooltip>
> ```
</details>

By default, Tooltips only appear on active buttons. There's a way around that, but in this instance, let's just cut out the Tooltip.
___
*[src/resources/translations.json, line 385 at r17](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MezKqSv2HC-KG8LMUi7:-MezKqSv2HC-KG8LMUi8:bvpkstv) ([raw file](https://github.com/sillsdev/thecombine/blob/86c1b0d1c16b0d3f4bbbe77eafec7e21479ac59d/src/resources/translations.json#L385)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>       "makeAdminWarning": [
>         "Give this user admin privileges?",
>         "Give this user admin privileges?",
>         "Give this user admin privileges?"
>       ],
>       "removeAdminWarning": [
>         "Remove admin privileges from this user?",
>         "Remove admin privileges from this user?",
>         "Remove admin privileges from this user?"
> ```
</details>

Jason indicated that we don't want to use "privileges" in the UI, so let's change these to "Make this user a project admin?" and "Remove project admin from this user?" (even though the latter sounds awkward).
___
*[src/resources/translations.json, line 421 at r17](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MezLhki7ycx9ABhV_2W:-MezLhkj0JxBOuYjNN7k:b8mz93r) ([raw file](https://github.com/sillsdev/thecombine/blob/86c1b0d1c16b0d3f4bbbe77eafec7e21479ac59d/src/resources/translations.json#L421)):*
<details><summary><i alt="summary">Quoted 19 lines of code…</i></summary>

> ```
>       "makeAdminToastSuccess": [
>         "User Given Admin Privileges!",
>         "User Given Admin Privileges!",
>         "User Given Admin Privileges!"
>       ],
>       "makeAdminToastFailure": [
>         "Failed to give admin privileges to user.",
>         "Failed to give admin privileges to user.",
>         "Failed to give admin privileges to user."
>       ],
>       "removeAdminToastSuccess": [
>         "Removed Admin Privileges from User!",
>         "Removed Admin Privileges from User!",
>         "Removed Admin Privileges from User!"
>       ],
>       "removeAdminToastFailure": [
>         "Failed to remove admin privileges from user.",
>         "Failed to remove admin privileges from user.",
>         "Failed to remove admin privileges from user."
> ```
</details>

Jason indicated that we don't want to use "privileges" or "permissions" in the UI, so let's reword these accordingly.
___
*[src/resources/translations.json, line 804 at r17](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MezMJCWB8SYiyF1Yqyu:-MezMJCWB8SYiyF1Yqyv:bw73ib8) ([raw file](https://github.com/sillsdev/thecombine/blob/86c1b0d1c16b0d3f4bbbe77eafec7e21479ac59d/src/resources/translations.json#L804)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     "removeAdmin": [
>       "Remove Admin Permissions",
>       "Remove Admin Permissions",
>       "Remove Admin Permissions"
>     ],
> ```
</details>

Jason indicated that we don't want to use "privileges" or "permissions" in the UI, so let's simply use "Remove Admin" here.


<!-- Sent from Reviewable.io -->

2021-07-19 16:22 UTC, WeJamUS commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 277 at r17](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MezMdHc0MeeVEbZA5Y8:-MezZwEWDpJ3STI62CuN:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/86c1b0d1c16b0d3f4bbbe77eafec7e21479ac59d/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L277)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Please add text for "Manage User" to `translations.json`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-19 16:22 UTC, WeJamUS commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 309 at r17](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MezMSfA6TmtNTV1xeqO:-MezZxBk2_6ZY66QO5nK:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/86c1b0d1c16b0d3f4bbbe77eafec7e21479ac59d/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L309)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>           <Tooltip title="You cannot edit this user">
>             <IconButton disabled>
>               <MoreVertIcon />
>             </IconButton>
>           </Tooltip>
> ```
By default, Tooltips only appear on active buttons. There's a way around that, but in this instance, let's just cut out the Tooltip.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-19 16:26 UTC, WeJamUS commented
___
*[src/resources/translations.json, line 804 at r17](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MezMJCWB8SYiyF1Yqyu:-Mez_ilnAYx0zmaRE1yb:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/86c1b0d1c16b0d3f4bbbe77eafec7e21479ac59d/src/resources/translations.json#L804)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>     "removeAdmin": [
>       "Remove Admin Permissions",
>       "Remove Admin Permissions",
>       "Remove Admin Permissions"
>     ],
> ```
Jason indicated that we don't want to use "privileges" or "permissions" in the UI, so let's simply use "Remove Admin" here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-19 16:26 UTC, WeJamUS commented
___
*[src/resources/translations.json, line 421 at r17](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MezLhki7ycx9ABhV_2W:-Mez_jDhEqGCqoIejidT:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/86c1b0d1c16b0d3f4bbbe77eafec7e21479ac59d/src/resources/translations.json#L421)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>       "makeAdminToastSuccess": [
>         "User Given Admin Privileges!",
>         "User Given Admin Privileges!",
>         "User Given Admin Privileges!"
>       ],
>       "makeAdminToastFailure": [
>         "Failed to give admin privileges to user.",
>         "Failed to give admin privileges to user.",
>         "Failed to give admin privileges to user."
>       ],
>       "removeAdminToastSuccess": [
>         "Removed Admin Privileges from User!",
>         "Removed Admin Privileges from User!",
>         "Removed Admin Privileges from User!"
>       ],
>       "removeAdminToastFailure": [
>         "Failed to remove admin privileges from user.",
>         "Failed to remove admin privileges from user.",
>         "Failed to remove admin privileges from user."
> ```
Jason indicated that we don't want to use "privileges" or "permissions" in the UI, so let's reword these accordingly.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-19 16:26 UTC, WeJamUS commented
___
*[src/resources/translations.json, line 385 at r17](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MezKqSv2HC-KG8LMUi7:-Mez_kGB3cDyTC-zJYzy:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/86c1b0d1c16b0d3f4bbbe77eafec7e21479ac59d/src/resources/translations.json#L385)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>       "makeAdminWarning": [
>         "Give this user admin privileges?",
>         "Give this user admin privileges?",
>         "Give this user admin privileges?"
>       ],
>       "removeAdminWarning": [
>         "Remove admin privileges from this user?",
>         "Remove admin privileges from this user?",
>         "Remove admin privileges from this user?"
> ```
Jason indicated that we don't want to use "privileges" in the UI, so let's change these to "Make this user a project admin?" and "Remove project admin from this user?" (even though the latter sounds awkward).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-19 20:12 UTC, imnasnainaec requested changes
> Reviewed 1 of 4 files at r12, 1 of 1 files at r13, 1 of 2 files at r18.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1253)* status: 18 of 19 files reviewed, 2 unresolved discussions (waiting on @jasonleenaylor, @johnthagen, and @WeJamUS)

___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 34 at r18](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Mf-NWNJ1APkBRbSx7Tu:-Mf-NWNJ1APkBRbSx7Tv:bqcszrl) ([raw file](https://github.com/sillsdev/thecombine/blob/f9063f32e5d7191aa5dc2ec91c1682a72b170634/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L34)):*
> ```
> const projectSettingsTranslation = "projectSettings.userManagement.";
> ```
I think I understand why you introduced this `const`, but I think it will make translation maintenance a bit harder.


<!-- Sent from Reviewable.io -->

2021-07-19 20:21 UTC, WeJamUS commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 34 at r18](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Mf-NWNJ1APkBRbSx7Tu:-Mf-QH5iDzeR4FAfjEU2:b-eut62u) ([raw file](https://github.com/sillsdev/thecombine/blob/f9063f32e5d7191aa5dc2ec91c1682a72b170634/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L34)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> const projectSettingsTranslation = "projectSettings.userManagement.";
> ```
I think I understand why you introduced this `const`, but I think it will make translation maintenance a bit harder.
</blockquote></details>

The const was originally a change requested by John last Friday. Should I still revert the change?


<!-- Sent from Reviewable.io -->

2021-07-19 20:43 UTC, imnasnainaec reviewed
> Reviewed 1 of 4 files at r12.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1253)* status: 18 of 19 files reviewed, 2 unresolved discussions (waiting on @jasonleenaylor, @johnthagen, and @WeJamUS)

___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 34 at r18](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Mf-NWNJ1APkBRbSx7Tu:-Mf-T6_dBfOrAMv_J8VD:b-s3e5aa) ([raw file](https://github.com/sillsdev/thecombine/blob/f9063f32e5d7191aa5dc2ec91c1682a72b170634/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L34)):*
<details><summary><i>Previously, WeJamUS (James Wu) wrote…</i></summary><blockquote>

The const was originally a change requested by John last Friday. Should I still revert the change?
</blockquote></details>

Yes, I think so, sorry for any whiplash. I'm not sure what @johnthagen meant when he mentioned a string occurring twice, as none of the full strings recur and this substring appears many times.


<!-- Sent from Reviewable.io -->

2021-07-20 04:59 UTC, WeJamUS commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 34 at r18](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Mf-NWNJ1APkBRbSx7Tu:-Mf1HDOU1jvSGwbsJYIS:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/f9063f32e5d7191aa5dc2ec91c1682a72b170634/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L34)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Yes, I think so, sorry for any whiplash. I'm not sure what @johnthagen meant when he mentioned a string occurring twice, as none of the full strings recur and this substring appears many times.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-21 16:21 UTC, imnasnainaec reviewed
> Reviewed 1 of 2 files at r21.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1253)* status: 17 of 20 files reviewed, 10 unresolved discussions (waiting on @imnasnainaec, @jasonleenaylor, @johnthagen, and @WeJamUS)

___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 13 at r21](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Mf8mENsCnhG_vAfLQ9f:-Mf8mENtEKPEAWy8Ml4u:b-vpqfj8) ([raw file](https://github.com/sillsdev/thecombine/blob/7c59c156a58c26fff8993b93542ac1b47ff66cbe/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L13)):*
> ```XML
>   Select,
> } from "@material-ui/core";
> import CancelConfirmDialogCollection from "./CancelConfirmDialogCollection";
> ```

To match our global style, this import should be changed from a relative to an absolute path, and moved down to the bottom of the local imports below.
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 15 at r21](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Mf8m4Pu09qsR-aw-lYl:-Mf8m4Pu09qsR-aw-lYm:b-gj8h6d) ([raw file](https://github.com/sillsdev/thecombine/blob/7c59c156a58c26fff8993b93542ac1b47ff66cbe/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L15)):*
> ```XML
> import CancelConfirmDialogCollection from "./CancelConfirmDialogCollection";
> import MoreVertIcon from "@material-ui/icons/MoreVert";
> ```

This blank link in the middle of the external imports should be removed.
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 60 at r21](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Mf8mkri640HNpzoVlHF:-Mf8mkrjA0Xt78CGMIZ9:bt21h94) ([raw file](https://github.com/sillsdev/thecombine/blob/7c59c156a58c26fff8993b93542ac1b47ff66cbe/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L60)):*
> ```XML
>   }
> 
>   private async populateUsers() {
> ```

The `await` in this function is inside a `.then()` so the functions isn't actually `async`.
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 103 at r21](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Mf8nTlg91wBJw0FJ93f:-Mf8nTlg91wBJw0FJ93g:baqe5ge) ([raw file](https://github.com/sillsdev/thecombine/blob/7c59c156a58c26fff8993b93542ac1b47ff66cbe/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L103)):*
> ```
>         userRole.permissions.includes(Permission.DeleteEditSettingsAndUsers) &&
>         userRole.permissions.includes(Permission.ImportExport)
> ```
We might want to allow non-admin users to have import/export permissions, so we probably only want to think of `DeleteEditSettingsAndUsers` as the project admin permission.
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 112 at r21](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Mf8nvEf6hCT-K4P91oq:-Mf8nvEf6hCT-K4P91or:bvtsrzi) ([raw file](https://github.com/sillsdev/thecombine/blob/7c59c156a58c26fff8993b93542ac1b47ff66cbe/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L112)):*
> ```
>     const currentUser = localStorage.getItem("user");
>     const currentProjectId = localStorage.getItem("projectId");
> ```
Please use the functions in `src/backend/localStorage.ts` for all local storage access.
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 122 at r21](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Mf8odG75-ciU5CFx7gz:-Mf8odG75-ciU5CFx7h-:b-pfma8z) ([raw file](https://github.com/sillsdev/thecombine/blob/7c59c156a58c26fff8993b93542ac1b47ff66cbe/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L122)):*
> ```
> !user.isAdmin
> ```
This prevents a site admin from being removed from a project or demoted from project admin, but those actions should be allowed. We want to prevent altering the project owner instead.
___
*[src/components/ProjectSettings/ProjectUsers/CancelConfirmDialogCollection.tsx, line 10 at r21](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Mf8pRFU9qTBpdZq96fa:-Mf8pRFU9qTBpdZq96fb:b1xg6yk) ([raw file](https://github.com/sillsdev/thecombine/blob/7c59c156a58c26fff8993b93542ac1b47ff66cbe/src/components/ProjectSettings/ProjectUsers/CancelConfirmDialogCollection.tsx#L10)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
> import { IconButton, Menu, MenuItem, Tooltip } from "@material-ui/core";
> import CancelConfirmDialog from "components/Buttons/CancelConfirmDialog";
> import React, { useState } from "react";
> import { Translate } from "react-localize-redux";
> import MoreVertIcon from "@material-ui/icons/MoreVert";
> import { Permission } from "api/models";
> import { addOrUpdateUserRole, removeUserRole } from "backend";
> import { toast } from "react-toastify";
> //styles the ToastContainer so that it appears on the upper right corner with the message.
> import "react-toastify/dist/ReactToastify.min.css";
> ```
</details>


Please sort these: first section external imports; second section internal imports; alphabetized by path within each section.
___
*[src/components/ProjectSettings/ProjectUsers/CancelConfirmDialogCollection.tsx, line 63 at r21](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Mf8qLBe417ctjFrx_k3:-Mf8qLBf50EpbeMJKezS:b-mzrkko) ([raw file](https://github.com/sillsdev/thecombine/blob/7c59c156a58c26fff8993b93542ac1b47ff66cbe/src/components/ProjectSettings/ProjectUsers/CancelConfirmDialogCollection.tsx#L63)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>       .then(() => setMakeAdmin(false))
>       .then(() => setAnchorEl(undefined))
>       .then(() => {
>         toast(
>           <Translate id="projectSettings.userManagement.makeAdminToastSuccess" />
>         );
>       })
> ```
</details>

These (and again below) can be combined in a single `then`:
```
      .then(() => {
        setRemoveAdmin(false);
        setAnchorEl(undefined);
        toast(
          <Translate id="projectSettings.userManagement.removeAdminToastSuccess" />
        );
      })
```

___
*[src/components/ProjectSettings/ProjectUsers/CancelConfirmDialogCollection.tsx, line 129 at r21](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Mf8rEcQD2kgJyueqOCH:-Mf8rEcSBLoyOZQhopxt:b-hvpzdw) ([raw file](https://github.com/sillsdev/thecombine/blob/7c59c156a58c26fff8993b93542ac1b47ff66cbe/src/components/ProjectSettings/ProjectUsers/CancelConfirmDialogCollection.tsx#L129)):*
> ```
>           onClick={(event) => {
>             setAnchorEl(event.currentTarget);
>           }}
> ```
Unnecessary `{....;}` around `setAnchorEl(...)`.


<!-- Sent from Reviewable.io -->

2021-07-21 16:37 UTC, WeJamUS commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 112 at r21](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Mf8nvEf6hCT-K4P91oq:-Mf8v_401mHDRCYqf-6k:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7c59c156a58c26fff8993b93542ac1b47ff66cbe/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L112)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>     const currentUser = localStorage.getItem("user");
>     const currentProjectId = localStorage.getItem("projectId");
> ```
Please use the functions in `src/backend/localStorage.ts` for all local storage access.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-21 16:41 UTC, WeJamUS commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 122 at r21](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Mf8odG75-ciU5CFx7gz:-Mf8wBmA3K068wuDx2lO:b-bbfga3) ([raw file](https://github.com/sillsdev/thecombine/blob/7c59c156a58c26fff8993b93542ac1b47ff66cbe/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L122)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> !user.isAdmin
> ```
This prevents a site admin from being removed from a project or demoted from project admin, but those actions should be allowed. We want to prevent altering the project owner instead.
</blockquote></details>

Should I remove the user.isAdmin check and then implement not altering the project owner after the project owner creation pull request goes through?


<!-- Sent from Reviewable.io -->

2021-07-21 16:47 UTC, WeJamUS commented
___
*[src/components/ProjectSettings/ProjectUsers/CancelConfirmDialogCollection.tsx, line 10 at r21](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Mf8pRFU9qTBpdZq96fa:-Mf8xkrf1zju0n8j3VOM:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7c59c156a58c26fff8993b93542ac1b47ff66cbe/src/components/ProjectSettings/ProjectUsers/CancelConfirmDialogCollection.tsx#L10)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> import { IconButton, Menu, MenuItem, Tooltip } from "@material-ui/core";
> import CancelConfirmDialog from "components/Buttons/CancelConfirmDialog";
> import React, { useState } from "react";
> import { Translate } from "react-localize-redux";
> import MoreVertIcon from "@material-ui/icons/MoreVert";
> import { Permission } from "api/models";
> import { addOrUpdateUserRole, removeUserRole } from "backend";
> import { toast } from "react-toastify";
> //styles the ToastContainer so that it appears on the upper right corner with the message.
> import "react-toastify/dist/ReactToastify.min.css";
> ```

Please sort these: first section external imports; second section internal imports; alphabetized by path within each section.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-21 16:47 UTC, WeJamUS commented
___
*[src/components/ProjectSettings/ProjectUsers/CancelConfirmDialogCollection.tsx, line 129 at r21](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Mf8rEcQD2kgJyueqOCH:-Mf8xmaI9HRuvmdCI1E3:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7c59c156a58c26fff8993b93542ac1b47ff66cbe/src/components/ProjectSettings/ProjectUsers/CancelConfirmDialogCollection.tsx#L129)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>           onClick={(event) => {
>             setAnchorEl(event.currentTarget);
>           }}
> ```
Unnecessary `{....;}` around `setAnchorEl(...)`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-21 16:49 UTC, WeJamUS commented
___
*[src/components/ProjectSettings/ProjectUsers/CancelConfirmDialogCollection.tsx, line 63 at r21](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Mf8qLBe417ctjFrx_k3:-Mf8yGO6A39vUKPAtePn:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7c59c156a58c26fff8993b93542ac1b47ff66cbe/src/components/ProjectSettings/ProjectUsers/CancelConfirmDialogCollection.tsx#L63)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>       .then(() => setMakeAdmin(false))
>       .then(() => setAnchorEl(undefined))
>       .then(() => {
>         toast(
>           <Translate id="projectSettings.userManagement.makeAdminToastSuccess" />
>         );
>       })
> ```
These (and again below) can be combined in a single `then`:
```
      .then(() => {
        setRemoveAdmin(false);
        setAnchorEl(undefined);
        toast(
          <Translate id="projectSettings.userManagement.removeAdminToastSuccess" />
        );
      })
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-21 17:50 UTC, imnasnainaec requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1253)* status: 17 of 20 files reviewed, 3 unresolved discussions (waiting on @imnasnainaec, @jasonleenaylor, @johnthagen, and @WeJamUS)

___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 60 at r21](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Mf8mkri640HNpzoVlHF:-Mf97jXE1W8m4mGXqFTV:b-43zjpr) ([raw file](https://github.com/sillsdev/thecombine/blob/7c59c156a58c26fff8993b93542ac1b47ff66cbe/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L60)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

The `await` in this function is inside a `.then()` so the functions isn't actually `async`.
</blockquote></details>

I should clarify: the function inside the `then` was correctly async: the final line setting the state needed to come after all the promises were awaited. It is the outside function `populateUsers`, which lacks any awaits, and so should not have `async`.
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 122 at r21](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Mf8odG75-ciU5CFx7gz:-Mf98Cow790vjEAttrDk:b2hy93i) ([raw file](https://github.com/sillsdev/thecombine/blob/7c59c156a58c26fff8993b93542ac1b47ff66cbe/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L122)):*
<details><summary><i>Previously, WeJamUS (James Wu) wrote…</i></summary><blockquote>

Should I remove the user.isAdmin check and then implement not altering the project owner after the project owner creation pull request goes through?
</blockquote></details>

The project owner pr is already merged, so you can proceed with these. One thing to consider (I'm not suggesting you do or don't... this is just a suggestion that may or may not be useful for what is left to do): you could move all the contents of the `{...}` in `sortedUserList.forEach((user) => {...}` into the CancelConfirmDialogCollection component.

I think these are the cases we need to consider:
* Remove any checks of `.isAdmin`;
* Both a project admin and the project owner should be able to add somebody to the project;
* Both a project admin and the project owner should be able to remove a user from the project if they are not a project admin;
* Only the project owner should be able to add or remove admin to/from a user;
* Only the project owner should be able to remove a user from the project if they are a project admin.

Feel free to message me in Slack or request a Google Meet if you want to talk over any of this more.


<!-- Sent from Reviewable.io -->

2021-07-22 16:12 UTC, WeJamUS commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 122 at r21](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Mf8odG75-ciU5CFx7gz:-MfDzM2qD5x6xd47buXX:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7c59c156a58c26fff8993b93542ac1b47ff66cbe/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L122)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

The project owner pr is already merged, so you can proceed with these. One thing to consider (I'm not suggesting you do or don't... this is just a suggestion that may or may not be useful for what is left to do): you could move all the contents of the `{...}` in `sortedUserList.forEach((user) => {...}` into the CancelConfirmDialogCollection component.

I think these are the cases we need to consider:
* Remove any checks of `.isAdmin`;
* Both a project admin and the project owner should be able to add somebody to the project;
* Both a project admin and the project owner should be able to remove a user from the project if they are not a project admin;
* Only the project owner should be able to add or remove admin to/from a user;
* Only the project owner should be able to remove a user from the project if they are a project admin.

Feel free to message me in Slack or request a Google Meet if you want to talk over any of this more.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-22 16:12 UTC, WeJamUS commented
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 60 at r21](https://reviewable.io/reviews/sillsdev/thecombine/1253#-Mf8mkri640HNpzoVlHF:-MfDzNdfE_I98SZdMU9D:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/7c59c156a58c26fff8993b93542ac1b47ff66cbe/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L60)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I should clarify: the function inside the `then` was correctly async: the final line setting the state needed to come after all the promises were awaited. It is the outside function `populateUsers`, which lacks any awaits, and so should not have `async`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-22 17:38 UTC, imnasnainaec reviewed
> Reviewed 1 of 2 files at r21.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1253)* status: 18 of 20 files reviewed, 4 unresolved discussions (waiting on @jasonleenaylor, @johnthagen, and @WeJamUS)

___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 121 at r23](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MfEG6veE3IG_B5xT3nP:-MfEG6veE3IG_B5xT3nQ:b3p5g4n) ([raw file](https://github.com/sillsdev/thecombine/blob/6bdae39db21f4a6a18cce06512fff8f9d9b206d7/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L121)):*
> ```
>     const currentUser = getCurrentUser();
>     const currentProjectId = getProjectId();
> ```
If you add `if (!currentUser || !currentProjectId){return <div/>}` after these two are declared (to quickly move past cases that should never occur on this page) you can remove the three checks for `currentUser` and one check for `currentProjectId` below.
___
*[src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx, line 137 at r23](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MfEG2JE1eoCtpZyOnpY:-MfEG2JE1eoCtpZyOnpZ:b-obnvhk) ([raw file](https://github.com/sillsdev/thecombine/blob/6bdae39db21f4a6a18cce06512fff8f9d9b206d7/src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx#L137)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>       let userIsProjectAdmin = this.isProjectAdmin(
>         user.projectRoles[currentProjectId]
>       );
>       let userIsProjectOwner = this.isProjectOwner(
>         user.projectRoles[currentProjectId]
>       );
> ```
</details>

These two can be `const`.
___
*[src/components/ProjectSettings/ProjectUsers/CancelConfirmDialogCollection.tsx, line 105 at r23](https://reviewable.io/reviews/sillsdev/thecombine/1253#-MfEGiFO59oolgVRY9UF:-MfEGiFO59oolgVRY9UG:b35dvxg) ([raw file](https://github.com/sillsdev/thecombine/blob/6bdae39db21f4a6a18cce06512fff8f9d9b206d7/src/components/ProjectSettings/ProjectUsers/CancelConfirmDialogCollection.tsx#L105)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>   let managementOptions: React.ReactElement<MenuItemProps>[] = [];
>   managementOptions.push(
>     <MenuItem onClick={() => setRemoveUser(true)}>
>       <Translate id="buttons.removeFromProject" />
>     </MenuItem>
>   );
> ```
</details>

You can allow for an implicit typing here by initiating with an element: 
```
>.  const managementOptions = [
>     <MenuItem onClick={() => setRemoveUser(true)}>
>       <Translate id="buttons.removeFromProject" />
>     </MenuItem>
>   ];
```



<!-- Sent from Reviewable.io -->

2021-07-22 20:23 UTC, imnasnainaec approved these changes
> Reviewed 1 of 1 files at r24, 1 of 1 files at r26.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1253)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jasonleenaylor)



<!-- Sent from Reviewable.io -->

2021-07-23 04:42 UTC, merged