Implement merge undo
sillsdev/TheCombine pull request #1300
Opened 2021-08-10 22:38 UTC by WeJamUS

2021-08-18 23:18 UTC, JacobHaimes reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1300)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @WeJamUS)

___
*[src/goals/MergeDupGoal/MergeDupsTypes.ts, line 16 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhQY4UBBOEVBk1lMBOR:-MhQY4UBBOEVBk1lMBOS:b-kevhzw) ([raw file](https://github.com/sillsdev/thecombine/blob/5bac888ec85d2ac41d079cf6c20db2418b262018/src/goals/MergeDupGoal/MergeDupsTypes.ts#L16)):*
> ```XML
> }
> 
> export interface MergesCompleted {
> ```

Since CompletedMerge is no longer what is being passed, and MergeUndoIds is not being changed between being imported and exported, is it possible to skip this step and import MergeUndoIds wherever MergeCompleted is being imported?


<!-- Sent from Reviewable.io -->

2021-08-19 01:04 UTC, WeJamUS commented
___
*[src/goals/MergeDupGoal/MergeDupsTypes.ts, line 16 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhQY4UBBOEVBk1lMBOR:-MhQtr2y9Rpyi5JtDovb:b-1yaqzv) ([raw file](https://github.com/sillsdev/thecombine/blob/5bac888ec85d2ac41d079cf6c20db2418b262018/src/goals/MergeDupGoal/MergeDupsTypes.ts#L16)):*
<details><summary><i>Previously, JacobHaimes wrote…</i></summary><blockquote>

Since CompletedMerge is no longer what is being passed, and MergeUndoIds is not being changed between being imported and exported, is it possible to skip this step and import MergeUndoIds wherever MergeCompleted is being imported?
</blockquote></details>

I think what you're describing also could have applied to when MergesCompleted's "merges" field was still a CompletedMerge[] where we might have been able to just import CompletedMerge and use CompletedMerge[] in place of MergesCompleted. Whoever designed this might have intended MergesCompleted to serve more of an encapsulating role than a functional role.


<!-- Sent from Reviewable.io -->

2021-08-19 13:47 UTC, imnasnainaec reviewed
> Reviewed 1 of 6 files at r1, 8 of 14 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1300)* status: 9 of 15 files reviewed, 3 unresolved discussions (waiting on @JacobHaimes and @WeJamUS)

*[a discussion](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhTebF-4I5P73NjbUHz:-MhTebF-4I5P73NjbUI-:bdwcgvn) (no related file):*
Instead of `Backend/Models/MergeUndoIds.cs` can you create a `.../Models/MergeWords.cs` which contains `MergeWords` and `MergeSourceWord` (both taken out of `.../Word.cs`) and `MergeUndoIds`?

---
___
*[src/backend/index.ts, line 193 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhF-tU-8wgWFx8oBlWe:-MhF-nXO2b-xqETPfswo:biaq0k) ([raw file](https://github.com/sillsdev/thecombine/blob/eec378824fbf66a7246ec5cda3b6b07385a28fd4/src/backend/index.ts#L193)):*
> ```XML
> }
> 
> export async function undoMerge(wordIds: { [key: string]: Array<string> }) {
> ```

Try `string[]` here instead of `Array<string>` (if TypeScript allows it).
___
*[src/goals/MergeDupGoal/MergeDupsTypes.ts, line 16 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhQY4UBBOEVBk1lMBOR:-MhTajqC56YRKHu6U7EB:b-r3wcax) ([raw file](https://github.com/sillsdev/thecombine/blob/5bac888ec85d2ac41d079cf6c20db2418b262018/src/goals/MergeDupGoal/MergeDupsTypes.ts#L16)):*
<details><summary><i>Previously, WeJamUS (James Wu) wrote…</i></summary><blockquote>

I think what you're describing also could have applied to when MergesCompleted's "merges" field was still a CompletedMerge[] where we might have been able to just import CompletedMerge and use CompletedMerge[] in place of MergesCompleted. Whoever designed this might have intended MergesCompleted to serve more of an encapsulating role than a functional role.
</blockquote></details>

Yes, that is a very reasonable suggestion, @jacobhaimes, but @wejamus has correctly identified the intent here. The `changes` field of the `Goal` model is general for all goal types, and we have a specific interface for changes for each goal type. This is the one for merges, so we can `goal.changes as MergesCompleted` when `goal.goalType === GoalType.MergeDups`.
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 114 at r7](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhTZcw3B7ntscZuYIg9:-MhTZcw3B7ntscZuYIgA:bo2n1ps) ([raw file](https://github.com/sillsdev/thecombine/blob/c273fbcfcffbdd0c6a65abc96a9d9fa17e574357/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L114)):*
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>

> ```
>       await getFrontierWords().then((words) => {
>         const frontierIds = words.map((word) => word.id);
>         let activateBtn = true;
>         props.merges.forEach((merge) => {
>           merge.parentIds.forEach((id) => {
>             if (!frontierIds.includes(id)) {
>               activateBtn = false;
>             }
>           });
>         });
>         setUndoBtn(activateBtn);
>       });
> ```
</details>

Let's separate this a little by moving the logic from inside `.then(...)` to its own function, something like `doWordsIncludeAllMerges(words: Word[]): boolean {...`. One advantage is that you will be able to `return false;` and break out of the loops instead of `activateBtn = false;` and continuing anyway.

Then inside the `useEffect`, instead of defining an async function that is never `await`ed, we can have:
`getFrontierWords().then((words)=>setUndoBtn(doWordsIncludeAllMerges(words)));`


<!-- Sent from Reviewable.io -->

2021-08-19 18:21 UTC, WeJamUS commented
___
*[src/backend/index.ts, line 193 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhF-tU-8wgWFx8oBlWe:-MhUdJGEAOkcfc1OidDL:b-8awm8d) ([raw file](https://github.com/sillsdev/thecombine/blob/eec378824fbf66a7246ec5cda3b6b07385a28fd4/src/backend/index.ts#L193)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Try `string[]` here instead of `Array<string>` (if TypeScript allows it).
</blockquote></details>

Could you elaborate a bit on where I should make this change?


<!-- Sent from Reviewable.io -->

2021-08-19 18:40 UTC, imnasnainaec requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1300)* status: 9 of 15 files reviewed, 5 unresolved discussions (waiting on @JacobHaimes and @WeJamUS)

___
*[src/backend/index.ts, line 193 at r5](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhF-tU-8wgWFx8oBlWe:-MhUfJ8A5b2RxPBpnLiY:b-drvm6x) ([raw file](https://github.com/sillsdev/thecombine/blob/eec378824fbf66a7246ec5cda3b6b07385a28fd4/src/backend/index.ts#L193)):*
<details><summary><i>Previously, WeJamUS (James Wu) wrote…</i></summary><blockquote>

Could you elaborate a bit on where I should make this change?
</blockquote></details>

That was an old comment, no longer relevant.
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 99 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhUgrNdDZWl1llB8g9y:-MhUgldD7RK8TaZDOvQG:b-6tazyj) ([raw file](https://github.com/sillsdev/thecombine/blob/fa562ab42add6e6fbd84b395fcb102216664f1c0/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L99)):*
> ```XML
> function UndoButton(props: UndoButtonProps) {
>   const [undoBtn, setUndoBtn] = useState<boolean>(false);
>   const [undoDialogOpen, setUndo] = useState<boolean>(false);
> ```

For consistent naming across all our `useState` usage, `setUndo` should be `setUndoDialogOpen`.
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 122 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhUhO5wEr9u6veZKgvz:-MhUhO5wEr9u6veZKgw-:b-o75gws) ([raw file](https://github.com/sillsdev/thecombine/blob/fa562ab42add6e6fbd84b395fcb102216664f1c0/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L122)):*
> ```
>           handleAccept={async () =>
>             await undoMerges(props.merges).then(() => setUndo(false))
>           }
> ```
The `CancelConfirmDialog`'s `handleAccept` doesn't do anything with asynchronous functions, so we can remove the `async` and `await` here.
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 134 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhUfiQG-ToR_B3CelsQ:-MhUfiQG-ToR_B3CelsR:bbnuotu) ([raw file](https://github.com/sillsdev/thecombine/blob/fa562ab42add6e6fbd84b395fcb102216664f1c0/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L134)):*
<details><summary><i alt="summary">Quoted 16 lines of code…</i></summary>

> ```
> function doWordsIncludeMerges(words: Word[], merges: MergeUndoIds[]): boolean {
>   const frontierIds = words.map((word) => word.id);
>   let activateBtn = true;
>   merges.forEach((merge) => {
>     if (!activateBtn) {
>       return activateBtn;
>     }
>     merge.parentIds.forEach((id) => {
>       if (!frontierIds.includes(id)) {
>         activateBtn = false;
>         return;
>       }
>     });
>   });
>   return activateBtn;
> }
> ```
</details>

It's nice to have this broken out, but now you don't even need the variable `activateBtn`. Use `return false;` instead of `activateBtn = false; return;` then at the very end of the function, outside both `forEach` loops, you can `return true;`.


<!-- Sent from Reviewable.io -->

2021-08-19 19:49 UTC, WeJamUS commented
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 99 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhUgrNdDZWl1llB8g9y:-MhUxRgq9BEi65ksWvYr:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/fa562ab42add6e6fbd84b395fcb102216664f1c0/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L99)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

For consistent naming across all our `useState` usage, `setUndo` should be `setUndoDialogOpen`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-19 19:52 UTC, WeJamUS commented
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 134 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhUfiQG-ToR_B3CelsQ:-MhUxeQx1LzIKj6oz3sa:b5lxnf) ([raw file](https://github.com/sillsdev/thecombine/blob/fa562ab42add6e6fbd84b395fcb102216664f1c0/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L134)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
> function doWordsIncludeMerges(words: Word[], merges: MergeUndoIds[]): boolean {
>   const frontierIds = words.map((word) => word.id);
>   let activateBtn = true;
>   merges.forEach((merge) => {
>     if (!activateBtn) {
>       return activateBtn;
>     }
>     merge.parentIds.forEach((id) => {
>       if (!frontierIds.includes(id)) {
>         activateBtn = false;
>         return;
>       }
>     });
>   });
>   return activateBtn;
> }
> ```
It's nice to have this broken out, but now you don't even need the variable `activateBtn`. Use `return false;` instead of `activateBtn = false; return;` then at the very end of the function, outside both `forEach` loops, you can `return true;`.
</blockquote></details>

I tried having return false within the innermost nested foreach loop but I ran into where doWordsIncludeMerges wasn't ever returning false. I thought it might have had to do with the scoping of the return false where returning from the nested loop wasn't causing a return in the doWordsIncludeMerges scope so it would always get to the return true at the end.


<!-- Sent from Reviewable.io -->

2021-08-19 20:02 UTC, WeJamUS commented
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 122 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhUhO5wEr9u6veZKgvz:-MhV-O9JBDRk5IuT7K7V:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/fa562ab42add6e6fbd84b395fcb102216664f1c0/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L122)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>           handleAccept={async () =>
>             await undoMerges(props.merges).then(() => setUndo(false))
>           }
> ```
The `CancelConfirmDialog`'s `handleAccept` doesn't do anything with asynchronous functions, so we can remove the `async` and `await` here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-19 20:35 UTC, imnasnainaec requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1300)* status: 9 of 16 files reviewed, 2 unresolved discussions (waiting on @JacobHaimes and @WeJamUS)

___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 134 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhUfiQG-ToR_B3CelsQ:-MhV6BRXBtflxkpgPx-A:b-7zbzks) ([raw file](https://github.com/sillsdev/thecombine/blob/fa562ab42add6e6fbd84b395fcb102216664f1c0/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L134)):*
<details><summary><i>Previously, WeJamUS (James Wu) wrote…</i></summary><blockquote>

I tried having return false within the innermost nested foreach loop but I ran into where doWordsIncludeMerges wasn't ever returning false. I thought it might have had to do with the scoping of the return false where returning from the nested loop wasn't causing a return in the doWordsIncludeMerges scope so it would always get to the return true at the end.
</blockquote></details>

Oh, right! The function inside the `forEach` is a different scope. You can switch these out for the more traditional for loop:
```
  for (const merge of merges) {
    for (const id of merge.parentIds) {
...
```


<!-- Sent from Reviewable.io -->

2021-08-19 20:55 UTC, WeJamUS commented
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 134 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhUfiQG-ToR_B3CelsQ:-MhVBaVP3Z8EOxRnHC9I:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/fa562ab42add6e6fbd84b395fcb102216664f1c0/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L134)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Oh, right! The function inside the `forEach` is a different scope. You can switch these out for the more traditional for loop:
```
  for (const merge of merges) {
    for (const id of merge.parentIds) {
...
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-19 21:09 UTC, imnasnainaec requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1300)* status: 9 of 16 files reviewed, 3 unresolved discussions (waiting on @JacobHaimes and @WeJamUS)

___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 134 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhUfiQG-ToR_B3CelsQ:-MhVDYHGAeo-MMe7HPeG:bkicqou) ([raw file](https://github.com/sillsdev/thecombine/blob/fa562ab42add6e6fbd84b395fcb102216664f1c0/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L134)):*
<details><summary><i>Previously, WeJamUS (James Wu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I just discovered an even crisper way to do this:
```
  const wordIds = words.map((word) => word.id);
  return merges.every((merge) =>
    merge.parentIds.every((id) => wordIds.includes(id))
  );
```
(Also note the move away from `frontierIds` since this function is more general purpose.)
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 42 at r11](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhVE2Y1-pbnjj_aUXBQ:-MhVE2Y1-pbnjj_aUXBR:bw5trf9) ([raw file](https://github.com/sillsdev/thecombine/blob/0e9686191e8cf2e36d6585c965f74345a66b4f87/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L42)):*
> ```XML
>       {MergesCount(changes)}
>       {changes.merges?.map(MergeChange)}
>       <UndoButton merges={changes.merges} />
> ```

I've been focused on the details and only just noticed. This is a function for undoing all the changes from a merge session, which is nice to have, but we don't want to force all-or-nothing on the user. There should be an undo button for each element of `changes.merges`, and (if that array has more than one entry) a final "undo all" button.


<!-- Sent from Reviewable.io -->

2021-08-19 22:03 UTC, WeJamUS commented
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 134 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhUfiQG-ToR_B3CelsQ:-MhVR4GRCyi92RMBo9NJ:b7d6vk7) ([raw file](https://github.com/sillsdev/thecombine/blob/fa562ab42add6e6fbd84b395fcb102216664f1c0/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L134)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I just discovered an even crisper way to do this:
```
  const wordIds = words.map((word) => word.id);
  return merges.every((merge) =>
    merge.parentIds.every((id) => wordIds.includes(id))
  );
```
(Also note the move away from `frontierIds` since this function is more general purpose.)
</blockquote></details>

After implementing this, when I click onto a completed merge card with no merges, it crashes with an TypeError saying "Cannot read property 'every' of undefined"


<!-- Sent from Reviewable.io -->

2021-08-19 22:04 UTC, WeJamUS commented
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 42 at r11](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhVE2Y1-pbnjj_aUXBQ:-MhVRKNBErAIvK8R7e3O:b-c0zpvm) ([raw file](https://github.com/sillsdev/thecombine/blob/0e9686191e8cf2e36d6585c965f74345a66b4f87/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L42)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I've been focused on the details and only just noticed. This is a function for undoing all the changes from a merge session, which is nice to have, but we don't want to force all-or-nothing on the user. There should be an undo button for each element of `changes.merges`, and (if that array has more than one entry) a final "undo all" button.
</blockquote></details>

I'm having trouble getting the enabled undo button to be centered and styled similar to the disabled undo button. The enabled button is always at the "top" of the container while the disabled button shows up in the middle.


<!-- Sent from Reviewable.io -->

2021-08-20 12:28 UTC, johnthagen commented
___
*[Backend/Models/MergeWords.cs, line 64 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhYWm7gA_N44lTP0OHE:-MhYWm7gA_N44lTP0OHF:b-e0u6eo) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend/Models/MergeWords.cs#L64)):*
> ```Smalltalk
>         }
> 
>         public MergeUndoIds(List<string> ParentIds, List<string> ChildIds)
> ```

To match our style guide parameter variables should start with a lower case letter: `parentIds` / `childIds`


<!-- Sent from Reviewable.io -->

2021-08-20 12:29 UTC, johnthagen commented
___
*[Backend/Controllers/MergeController.cs, line 57 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhYXHIFC50kfl5-lleF:-MhYXHIFC50kfl5-lleG:b-v5byzm) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend/Controllers/MergeController.cs#L57)):*
> ```Smalltalk
>         [HttpPut("undo", Name = "UndoMerges")]
>         [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
>         public async Task<IActionResult> UndoMerges(string projectId, [FromBody, BindRequired] MergeUndoIds[] ids)
> ```

The `ids` parameter name might be a little more descriptive if it were named `mergeIds`


<!-- Sent from Reviewable.io -->

2021-08-20 12:29 UTC, johnthagen commented
___
*[Backend/Controllers/MergeController.cs, line 76 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhYXNdgDBoB8IBVFsbF:-MhYXNdgDBoB8IBVFsbG:b-29zde7) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend/Controllers/MergeController.cs#L76)):*
> ```Smalltalk
>                 return BadRequest("Undo failed.");
>             }
> ```

Can remove extra newline.


<!-- Sent from Reviewable.io -->

2021-08-20 12:32 UTC, johnthagen commented
___
*[Backend/Controllers/MergeController.cs, line 72 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhYXVDJ4TZSbZvyy0QG:-MhYXVDK6K-f6tVTL-Ie:b-aq3qv2) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend/Controllers/MergeController.cs#L72)):*
> ```Smalltalk
>                 return Ok(true);
>             }
>             catch
> ```

I see that we are doing this in `MergeWords` as well, but in general we should not put blank `catch` clauses in the backend. This could mask real bugs because we could be catching and (somewhat)-silently suppressing them.

Ideally, we should document what exceptions can be thrown from `UndoMerge()` and catch those here. If an exception is thrown we don't expect, the backend will return 500 and then we have an opportunity to correct the logic bug.

This would then put us in a better situation when https://github.com/sillsdev/TheCombine/issues/1125 is implemented.


<!-- Sent from Reviewable.io -->

2021-08-20 12:33 UTC, johnthagen commented
___
*[Backend/Interfaces/IMergeService.cs, line 12 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhYYNoX6hEG7qTAz53w:-MhYYNoX6hEG7qTAz53x:bbyud51) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend/Interfaces/IMergeService.cs#L12)):*
> ```Smalltalk
>         Task<List<Word>> Merge(string projectId, List<MergeWords> mergeWordsList);
>         Task<bool> UndoMerge(string projectId, MergeUndoIds ids);
> ```

Can remove this extra newline.


<!-- Sent from Reviewable.io -->

2021-08-20 12:35 UTC, johnthagen commented
___
*[Backend/Models/MergeWords.cs, line 47 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhYY_XT063Wc4KeH54x:-MhYY_XT063Wc4KeH54y:bchijmo) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend/Models/MergeWords.cs#L47)):*
> ```Smalltalk
>     }
> 
>     /// <summary> The parent and children ids of each <see cref="Word"> involved in a merge </summary>
> ```

Internal XML element is not closed. Can fix with `<see cref="Word"/>`


<!-- Sent from Reviewable.io -->

2021-08-20 12:37 UTC, johnthagen commented
___
*[Backend/Models/MergeWords.cs, line 70 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhYYply3hKtmwoOhKtf:-MhYYplz0vHoCVNZGC0_:b-2sd3kc) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend/Models/MergeWords.cs#L70)):*
> ```Smalltalk
>         }
> 
>         public MergeUndoIds Clone()
> ```

We should add unit tests for this `Model` into `Backend.Tests/Models/MergeWords.cs`. You can use run the code coverage task to verify all of the lines have been covered: https://github.com/sillsdev/TheCombine#backend-code-coverage-report


<!-- Sent from Reviewable.io -->

2021-08-20 12:38 UTC, johnthagen commented
___
*[Backend/Models/MergeWords.cs, line 66 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhYZIqu3onzv3SGVzAp:-MhYZIqu3onzv3SGVzAq:b-m80sdt) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend/Models/MergeWords.cs#L66)):*
> ```Smalltalk
>         public MergeUndoIds(List<string> ParentIds, List<string> ChildIds)
>         {
>             this.ParentIds = ParentIds;
> ```

When the parameter variable names are renamed to use a lowercase first letter, you can remove the `this.` prefixes here to follow our C# conventions.


<!-- Sent from Reviewable.io -->

2021-08-20 12:39 UTC, johnthagen commented
___
*[Backend/Services/MergeService.cs, line 18 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhYZfDX9TPgBHGWPrSV:-MhYZfDX9TPgBHGWPrSW:b-l560ju) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend/Services/MergeService.cs#L18)):*
> ```Smalltalk
>         private readonly IWordService _wordService;
> 
>         public MergeService(IMergeBlacklistRepository mergeBlacklistRepo, IWordRepository wordRepo, IWordService wordService)
> ```

Can wrap this line so that it stays within 120 characters:

```
        public MergeService(
            IMergeBlacklistRepository mergeBlacklistRepo, IWordRepository wordRepo, IWordService wordService)
        {
```


<!-- Sent from Reviewable.io -->

2021-08-20 12:40 UTC, johnthagen commented
___
*[Backend/Services/MergeService.cs, line 95 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhYZuYx7a4cKEMjrBil:-MhYZuYx7a4cKEMjrBim:b6o1m5q) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend/Services/MergeService.cs#L95)):*
> ```Smalltalk
>             }
> 
>             List<Word> childWords = new List<Word>();
> ```

This can be simplified to:

```
var childWords = new List<Word>();
```


<!-- Sent from Reviewable.io -->

2021-08-20 12:42 UTC, johnthagen commented
___
*[Backend.Tests/Controllers/MergeControllerTests.cs, line 21 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhY_LGL6IitCBfnOgP1:-MhY_LGL6IitCBfnOgP2:b-3g92z2) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend.Tests/Controllers/MergeControllerTests.cs#L21)):*
> ```Smalltalk
> 
>         private const string ProjId = "MergeServiceTestProjId";
>         private const string UserId = "MergeServiceTestUserId";
> ```

This variable is never used and can be removed.


<!-- Sent from Reviewable.io -->

2021-08-20 12:43 UTC, johnthagen commented
___
*[Backend.Tests/Controllers/MergeControllerTests.cs, line 33 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhY_YHdEw_B3fWuAQ2z:-MhY_YHdEw_B3fWuAQ3-:b-amsu3t) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend.Tests/Controllers/MergeControllerTests.cs#L33)):*
> ```Smalltalk
>             _mergeController = new MergeController(_mergeService, _permissionService);
>         }
> ```

Should we add unit test(s) for MergeController.UndoMerges()`?


<!-- Sent from Reviewable.io -->

2021-08-20 12:44 UTC, johnthagen commented
___
*[Backend.Tests/Services/MergeServiceTests.cs, line 128 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhY_qHS6ENIuMBszAII:-MhY_qHS6ENIuMBszAIJ:b-e6qhmv) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend.Tests/Services/MergeServiceTests.cs#L128)):*
> ```Smalltalk
> 
>             var childIds = mergeObject.Children.ConvertAll<string>(word => word.SrcWordId);
>             var parentIds = new List<string>();
> ```

These two lines can be simplified to:

```
var parentIds = new List<string> { newWords[0].Id };
```


<!-- Sent from Reviewable.io -->

2021-08-20 12:45 UTC, johnthagen commented
___
*[Backend.Tests/Services/MergeServiceTests.cs, line 131 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhYa-YdCBvH8Ror5Btd:-MhYa-YdCBvH8Ror5Bte:b-lkhisu) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend.Tests/Services/MergeServiceTests.cs#L131)):*
> ```Smalltalk
>             parentIds.Add(newWords[0].Id);
>             var mergedWord = new MergeUndoIds(parentIds, childIds);
>             var undo = _mergeService.UndoMerge(ProjId, mergedWord).Result;
> ```

Should we assert that `undo` is `True`?


<!-- Sent from Reviewable.io -->

2021-08-20 13:29 UTC, johnthagen commented
___
*[Backend.Tests/Services/MergeServiceTests.cs, line 127 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhYjni_3Rl7OGs5R0uF:-MhYjni_3Rl7OGs5R0uG:b-h5z4n5) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend.Tests/Services/MergeServiceTests.cs#L127)):*
> ```Smalltalk
>             Assert.That(newWords.First().ContentEquals(thisWord));
> 
>             var childIds = mergeObject.Children.ConvertAll<string>(word => word.SrcWordId);
> ```

This can be "simplified" to

```
var childIds = mergeObject.Children.Select(word => word.SrcWordId).ToList();
```

This allows for avoiding the redundant `<string>` type.

According to SO, `Select()` is preferred to `ConvertAll()`: https://stackoverflow.com/a/1571843


<!-- Sent from Reviewable.io -->

2021-08-20 13:29 UTC, johnthagen commented
___
*[Backend.Tests/Services/MergeServiceTests.cs, line 134 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhYk50l0ztYWVPteJAb:-MhYk50l0ztYWVPteJAc:bhxp2r2) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend.Tests/Services/MergeServiceTests.cs#L134)):*
> ```Smalltalk
> 
>             var frontierWords = _wordRepo.GetFrontier(ProjId).Result;
>             var frontierWordIds = frontierWords.ConvertAll<string>(word => word.Id);
> ```

`ConvertAll` can be simplified to `Select(...).ToList()`.


<!-- Sent from Reviewable.io -->

2021-08-20 13:30 UTC, johnthagen commented
___
*[Backend.Tests/Services/MergeServiceTests.cs, line 161 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhYkHyYA0wvOW-e-y9h:-MhYkHyYA0wvOW-e-y9i:bo84k5n) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend.Tests/Services/MergeServiceTests.cs#L161)):*
> ```Smalltalk
> 
>             var childIds = mergeWords.Children.ConvertAll<string>(word => word.SrcWordId);
>             var parentIds = new List<string>();
> ```

Can be simplified to:

```
            var parentIds = new List<string> { newWords[0].Id };
```


<!-- Sent from Reviewable.io -->

2021-08-20 13:30 UTC, johnthagen commented
___
*[Backend.Tests/Services/MergeServiceTests.cs, line 164 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhYkMeqA4VG-m5rILtX:-MhYkMeqA4VG-m5rILtY:bxo13k6) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend.Tests/Services/MergeServiceTests.cs#L164)):*
> ```Smalltalk
>             parentIds.Add(newWords[0].Id);
>             var mergedWord = new MergeUndoIds(parentIds, childIds);
>             var undo = _mergeService.UndoMerge(ProjId, mergedWord).Result;
> ```

Assert `undo` is `True`?


<!-- Sent from Reviewable.io -->

2021-08-20 13:31 UTC, johnthagen commented
___
*[Backend.Tests/Services/MergeServiceTests.cs, line 160 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhYkRIJ3bs6ZuTh-2G4:-MhYkRIJ3bs6ZuTh-2G5:b5bzbw8) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend.Tests/Services/MergeServiceTests.cs#L160)):*
> ```Smalltalk
>             Assert.That(_wordRepo.GetFrontier(ProjId).Result, Has.Count.EqualTo(1));
> 
>             var childIds = mergeWords.Children.ConvertAll<string>(word => word.SrcWordId);
> ```

As above, the two `ConvertAll()`'s can be simplified into `Select()` queries.


<!-- Sent from Reviewable.io -->

2021-08-20 15:23 UTC, johnthagen commented
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 117 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhZ915KBTFbFF1E1vNV:-MhZ915KBTFbFF1E1vNW:bdzhh02) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L117)):*
> ```XML
> 
> function UndoButton(props: UndoButtonProps) {
>   const [undoBtn, setUndoBtn] = useState<boolean>(false);
> ```

Could `undoBtn` be made a little more descriptive? Something like `isUndoBtnEnabled`?


<!-- Sent from Reviewable.io -->

2021-08-20 15:25 UTC, johnthagen commented
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 153 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhZ9Oar5YhEz5Odwf7q:-MhZ9Oar5YhEz5Odwf7r:bxc5sx2) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L153)):*
> ```XML
> }
> 
> function doWordsIncludeMerges(words: Word[], merges: MergeUndoIds[]): boolean {
> ```

Because this is a pure function, it would be easy to unit test in isolation. Could we add some unit tests for this?


<!-- Sent from Reviewable.io -->

2021-08-20 15:26 UTC, johnthagen requested changes
> Reviewed 1 of 2 files at r3, 3 of 14 files at r6, 2 of 3 files at r9, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1300)* status: all files reviewed, 24 unresolved discussions (waiting on @imnasnainaec, @JacobHaimes, and @WeJamUS)



<!-- Sent from Reviewable.io -->

2021-08-20 18:39 UTC, WeJamUS commented
___
*[Backend/Controllers/MergeController.cs, line 76 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhYXNdgDBoB8IBVFsbF:-MhZr2e3-qP8QXLWa8wD:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend/Controllers/MergeController.cs#L76)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Can remove extra newline.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-20 18:39 UTC, WeJamUS commented
___
*[Backend/Interfaces/IMergeService.cs, line 12 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhYYNoX6hEG7qTAz53w:-MhZr3wo5Dx8UVPL2TG4:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend/Interfaces/IMergeService.cs#L12)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Can remove this extra newline.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-20 18:39 UTC, WeJamUS commented
___
*[Backend/Models/MergeWords.cs, line 47 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhYY_XT063Wc4KeH54x:-MhZr4iZ72EErK3V8Lur:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend/Models/MergeWords.cs#L47)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Internal XML element is not closed. Can fix with `<see cref="Word"/>`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-20 18:39 UTC, WeJamUS commented
___
*[Backend/Models/MergeWords.cs, line 64 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhYWm7gA_N44lTP0OHE:-MhZr6B50hvHYiapQQKh:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend/Models/MergeWords.cs#L64)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

To match our style guide parameter variables should start with a lower case letter: `parentIds` / `childIds`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-20 18:39 UTC, WeJamUS commented
___
*[Backend/Models/MergeWords.cs, line 66 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhYZIqu3onzv3SGVzAp:-MhZr6gM7TcfPTgXYBH9:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend/Models/MergeWords.cs#L66)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

When the parameter variable names are renamed to use a lowercase first letter, you can remove the `this.` prefixes here to follow our C# conventions.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-20 18:39 UTC, WeJamUS commented
___
*[Backend/Services/MergeService.cs, line 95 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhYZuYx7a4cKEMjrBil:-MhZr8Hu1H57R8j1xEB0:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend/Services/MergeService.cs#L95)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This can be simplified to:

```
var childWords = new List<Word>();
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-20 18:39 UTC, WeJamUS commented
___
*[Backend.Tests/Controllers/MergeControllerTests.cs, line 21 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhY_LGL6IitCBfnOgP1:-MhZr9kLCxBV-Enz34rR:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend.Tests/Controllers/MergeControllerTests.cs#L21)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This variable is never used and can be removed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-20 18:40 UTC, WeJamUS commented
___
*[Backend.Tests/Services/MergeServiceTests.cs, line 127 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhYjni_3Rl7OGs5R0uF:-MhZrGbX20k-_hW0FKic:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend.Tests/Services/MergeServiceTests.cs#L127)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

This can be "simplified" to

```
var childIds = mergeObject.Children.Select(word => word.SrcWordId).ToList();
```

This allows for avoiding the redundant `<string>` type.

According to SO, `Select()` is preferred to `ConvertAll()`: https://stackoverflow.com/a/1571843
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-20 18:40 UTC, WeJamUS commented
___
*[Backend.Tests/Services/MergeServiceTests.cs, line 128 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhY_qHS6ENIuMBszAII:-MhZrILV-6NOZoHHXRWM:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend.Tests/Services/MergeServiceTests.cs#L128)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

These two lines can be simplified to:

```
var parentIds = new List<string> { newWords[0].Id };
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-20 18:40 UTC, WeJamUS commented
___
*[Backend.Tests/Services/MergeServiceTests.cs, line 134 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhYk50l0ztYWVPteJAb:-MhZrJt62vAv4HZmPCWz:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend.Tests/Services/MergeServiceTests.cs#L134)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

`ConvertAll` can be simplified to `Select(...).ToList()`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-20 18:40 UTC, WeJamUS commented
___
*[Backend.Tests/Services/MergeServiceTests.cs, line 161 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhYkHyYA0wvOW-e-y9h:-MhZrLkY3VKRW1TKC3ol:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend.Tests/Services/MergeServiceTests.cs#L161)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Can be simplified to:

```
            var parentIds = new List<string> { newWords[0].Id };
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-20 19:10 UTC, WeJamUS commented
___
*[Backend.Tests/Services/MergeServiceTests.cs, line 131 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhYa-YdCBvH8Ror5Btd:-MhZyEPN7uLYlCUj3pTS:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend.Tests/Services/MergeServiceTests.cs#L131)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Should we assert that `undo` is `True`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-20 19:10 UTC, WeJamUS commented
___
*[Backend.Tests/Services/MergeServiceTests.cs, line 160 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhYkRIJ3bs6ZuTh-2G4:-MhZyFEl7ImG5s6Nfro4:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend.Tests/Services/MergeServiceTests.cs#L160)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

As above, the two `ConvertAll()`'s can be simplified into `Select()` queries.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-20 19:10 UTC, WeJamUS commented
___
*[Backend.Tests/Services/MergeServiceTests.cs, line 164 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhYkMeqA4VG-m5rILtX:-MhZyHKM2PKFiOP1UsrM:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/Backend.Tests/Services/MergeServiceTests.cs#L164)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Assert `undo` is `True`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-20 19:32 UTC, WeJamUS commented
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 153 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhZ9Oar5YhEz5Odwf7q:-Mh_1tIC4g-K_gN_rsXV:b-dvqou1) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L153)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Because this is a pure function, it would be easy to unit test in isolation. Could we add some unit tests for this?
</blockquote></details>

Which directory should these tests go? I can't seem to find a directory dedicated to unit-testing functions in front-end components.


<!-- Sent from Reviewable.io -->

2021-08-20 19:33 UTC, johnthagen commented
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 153 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhZ9Oar5YhEz5Odwf7q:-Mh_2XpKDnlqUlJwx96H:b3l97pn) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L153)):*
<details><summary><i>Previously, WeJamUS (James Wu) wrote…</i></summary><blockquote>

Which directory should these tests go? I can't seem to find a directory dedicated to unit-testing functions in front-end components.
</blockquote></details>

@imnasnainaec Thoughts?


<!-- Sent from Reviewable.io -->

2021-08-20 19:36 UTC, imnasnainaec reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1300)* status: 9 of 16 files reviewed, 6 unresolved discussions (waiting on @imnasnainaec, @JacobHaimes, @johnthagen, and @WeJamUS)

___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 134 at r8](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhUfiQG-ToR_B3CelsQ:-Mh_2z1r1CFCYwovHOzP:b-yfsqvy) ([raw file](https://github.com/sillsdev/thecombine/blob/fa562ab42add6e6fbd84b395fcb102216664f1c0/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L134)):*
<details><summary><i>Previously, WeJamUS (James Wu) wrote…</i></summary><blockquote>

After implementing this, when I click onto a completed merge card with no merges, it crashes with an TypeError saying "Cannot read property 'every' of undefined"
</blockquote></details>

When you call `setUndoBtnEnabled(doWordsIncludeMerges(words, props.merges))` above you could add ` ?? []` after `props.merges` to catch that.
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 153 at r12](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhZ9Oar5YhEz5Odwf7q:-Mh_3CMA83VNgSde7MT8:brapb70) ([raw file](https://github.com/sillsdev/thecombine/blob/bee6e7e48b9855083b167c0700b39cc547d30299/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L153)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

@imnasnainaec Thoughts?
</blockquote></details>

Create `/src/goals/MergeDupGoal/MergeDupComponent/tests/`


<!-- Sent from Reviewable.io -->

2021-08-20 20:13 UTC, WeJamUS commented
___
*[src/goals/MergeDupGoal/MergeDupsTypes.ts, line 16 at r6](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MhQY4UBBOEVBk1lMBOR:-Mh_BYo2A04FmJKB5nLg:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/5bac888ec85d2ac41d079cf6c20db2418b262018/src/goals/MergeDupGoal/MergeDupsTypes.ts#L16)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Yes, that is a very reasonable suggestion, @jacobhaimes, but @wejamus has correctly identified the intent here. The `changes` field of the `Goal` model is general for all goal types, and we have a specific interface for changes for each goal type. This is the one for merges, so we can `goal.changes as MergesCompleted` when `goal.goalType === GoalType.MergeDups`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-28 12:26 UTC, imnasnainaec requested changes
> Reviewed 1 of 7 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1300)* status: 11 of 18 files reviewed, 8 unresolved discussions (waiting on @JacobHaimes, @johnthagen, and @WeJamUS)

___
*[Backend/Services/MergeService.cs, line 93 at r19](https://reviewable.io/reviews/sillsdev/thecombine/1300#-Mi7m2HN5zqHwRh6aOwf:-MiBgNm_7ls9dmzUnCqK:bxjor9d) ([raw file](https://github.com/sillsdev/thecombine/blob/d8cdddc3fb8377f61673d8b94a855e09cfe276e7/Backend/Services/MergeService.cs#L93)):*
<details><summary><i>Previously, WeJamUS (James Wu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It should go after the child `foreach` too. We don't want to delete parents just to discover that we can't restore their purported children.
___
*[Backend.Tests/Models/MergeWordsTests.cs, line 40 at r22](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MiBh45vDPWWnwECuAKC:-MiBh45vDPWWnwECuAKD:bld5d07) ([raw file](https://github.com/sillsdev/thecombine/blob/889b9563184487bc86c7619f1a0ead0dcac8c43c/Backend.Tests/Models/MergeWordsTests.cs#L40)):*
> ```
>             Assert.IsFalse(mergeNonEmpty2.Equals(mergeNonEmpty3));
>             Assert.IsFalse(mergeNonEmpty2.Equals(mergeNonEmpty4));
>             Assert.IsFalse(mergeNonEmpty3.Equals(mergeNonEmpty4));
> ```
These three are overkill. The others tests cover with different parents, different children, and both.
___
*[src/goals/MergeDupGoal/MergeDupComponent/tests/MergeDupsCompleted.test.tsx, line 37 at r22](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MiBi9LyA96XRE9K1mRR:-MiBi9LyA96XRE9K1mRS:b-cwbyaz) ([raw file](https://github.com/sillsdev/thecombine/blob/889b9563184487bc86c7619f1a0ead0dcac8c43c/src/goals/MergeDupGoal/MergeDupComponent/tests/MergeDupsCompleted.test.tsx#L37)):*
> ```XML
> 
>     const words: Word[] = [newWord(), newWord(), newWord(), newWord()];
>     words[0].id = "merge1PId";
> ```

If it is important for the strings to match, then this should be:
```
words[0].id = merge1.parentIds[0];
...
```
___
*[src/goals/MergeDupGoal/MergeDupComponent/tests/MergeDupsCompleted.test.tsx, line 50 at r22](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MiBhmmtEEbYbxCKBowF:-MiBhmmtEEbYbxCKBowG:b-4p4ijf) ([raw file](https://github.com/sillsdev/thecombine/blob/889b9563184487bc86c7619f1a0ead0dcac8c43c/src/goals/MergeDupGoal/MergeDupComponent/tests/MergeDupsCompleted.test.tsx#L50)):*
> ```
>     words[2].id = "merge2PId";
>     words[3].id = "merge2PId2";
> ```
You could drop these two. I don't see a reason to have both "1P" and "2P" in this tests scenario.


<!-- Sent from Reviewable.io -->

2021-08-30 08:35 UTC, WeJamUS commented
___
*[Backend/Services/MergeService.cs, line 93 at r19](https://reviewable.io/reviews/sillsdev/thecombine/1300#-Mi7m2HN5zqHwRh6aOwf:-MiLBgq77dRIqbEUFWrN:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/d8cdddc3fb8377f61673d8b94a855e09cfe276e7/Backend/Services/MergeService.cs#L93)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

It should go after the child `foreach` too. We don't want to delete parents just to discover that we can't restore their purported children.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-30 08:35 UTC, WeJamUS commented
___
*[src/goals/MergeDupGoal/MergeDupComponent/tests/MergeDupsCompleted.test.tsx, line 37 at r22](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MiBi9LyA96XRE9K1mRR:-MiLBjKi1NoTaKKRvfoT:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/889b9563184487bc86c7619f1a0ead0dcac8c43c/src/goals/MergeDupGoal/MergeDupComponent/tests/MergeDupsCompleted.test.tsx#L37)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

If it is important for the strings to match, then this should be:
```
words[0].id = merge1.parentIds[0];
...
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-30 18:30 UTC, imnasnainaec requested changes
> Reviewed 1 of 1 files at r14, 1 of 2 files at r18, 1 of 2 files at r22, 2 of 3 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1300)* status: 16 of 18 files reviewed, 5 unresolved discussions (waiting on @JacobHaimes, @johnthagen, and @WeJamUS)

___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 103 at r23](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MiNInsIENwT8geCmHtv:-MiNInsIENwT8geCmHtw:b4ed3yi) ([raw file](https://github.com/sillsdev/thecombine/blob/1e67e6aa8eeeb3f34f2bdd64d5c43d60a24ef6f2/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L103)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>         <UndoButton
>           merges={[change]}
>           textId="mergeDups.undo.undo"
>           dialogId="mergeDups.undo.undoDialog"
>           disabledId="mergeDups.undo.undoDisabled"
>         />
> ```
</details>

Let's work a little on the visual of this button.
First, it would benefit from an outline, so it's clearly a button even when the cursor isn't over it.
Second, try to vertically center it, like the arrow. You can try a `Grid` around a `div` around the `UndoButton`, where the `div` has the same `style` as the `ArrowRightAlt`, though I'm not sure that will place the button quite right, it's a starting place.


<!-- Sent from Reviewable.io -->

2021-08-30 18:39 UTC, imnasnainaec requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1300)* status: 16 of 18 files reviewed, 8 unresolved discussions (waiting on @JacobHaimes, @johnthagen, and @WeJamUS)

___
*[Backend/Controllers/MergeController.cs, line 57 at r23](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MiNLeRp03_TjRhEmte-:-MiNLeRp03_TjRhEmte0:b-2tldz9) ([raw file](https://github.com/sillsdev/thecombine/blob/1e67e6aa8eeeb3f34f2bdd64d5c43d60a24ef6f2/Backend/Controllers/MergeController.cs#L57)):*
> ```Smalltalk
>         [HttpPut("undo", Name = "UndoMerges")]
>         [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
>         public async Task<IActionResult> UndoMerges(string projectId, [FromBody, BindRequired] MergeUndoIds[] mergeIds)
> ```

Let's remove the Undo all, and change this to only take a single `MergeUndoIds` instead of an array. Then you can `await _mergeService.UndoMerge(projectId, mergeIds);` And you'll need to rerun OpenApi generation.
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 47 at r23](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MiNLQPV-kOIF3PGAaxT:-MiNLQPV-kOIF3PGAaxU:be7cm6p) ([raw file](https://github.com/sillsdev/thecombine/blob/1e67e6aa8eeeb3f34f2bdd64d5c43d60a24ef6f2/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L47)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>       <UndoButton
>         merges={changes.merges}
>         textId="mergeDups.undo.undoAll"
>         dialogId="mergeDups.undo.undoAllDialog"
>         disabledId="mergeDups.undo.undoAllDisabled"
>       />
> ```
</details>

Let's remove the Undo All.
___
*[src/resources/translations.json, line 801 at r23](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MiNLX2l6eZVsOaesiGU:-MiNLX2mBWtA7AereSo4:bqzd2hu) ([raw file](https://github.com/sillsdev/thecombine/blob/1e67e6aa8eeeb3f34f2bdd64d5c43d60a24ef6f2/src/resources/translations.json#L801)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
>       "undoAll": ["Undo All Merges", "Undo All Merges", "Undo All Merges"],
>       "undoAllDialog": [
>         "Undo all merges from in this session?",
>         "Undo all merges from in this session?",
>         "Undo all merges from in this session?"
>       ],
>       "undoAllDisabled": [
>         "Undo All Unavailable",
>         "Undo All Unavailable",
>         "Undo All Unavailable"
>       ],
> ```
</details>

Let's remove the Undo All.


<!-- Sent from Reviewable.io -->

2021-08-30 18:40 UTC, imnasnainaec requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1300)* status: 16 of 18 files reviewed, 9 unresolved discussions (waiting on @JacobHaimes, @johnthagen, and @WeJamUS)

___
*[Backend/Controllers/MergeController.cs, line 55 at r23](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MiNM39G3aNH5c3Obhm0:-MiNM39G3aNH5c3Obhm1:b-ni7x8h) ([raw file](https://github.com/sillsdev/thecombine/blob/1e67e6aa8eeeb3f34f2bdd64d5c43d60a24ef6f2/Backend/Controllers/MergeController.cs#L55)):*
> ```
>         /// <summary> Undo merges </summary>
>         /// <returns> True if merges were successfully undone </returns>
>         [HttpPut("undo", Name = "UndoMerges")]
> ```
This will need to be reverted to "merge" / "merge was" / "UndoMerge".


<!-- Sent from Reviewable.io -->

2021-08-30 20:11 UTC, WeJamUS commented
___
*[Backend/Controllers/MergeController.cs, line 55 at r23](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MiNM39G3aNH5c3Obhm0:-MiNg1s008eH7P24LFN3:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/1e67e6aa8eeeb3f34f2bdd64d5c43d60a24ef6f2/Backend/Controllers/MergeController.cs#L55)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>         /// <summary> Undo merges </summary>
>         /// <returns> True if merges were successfully undone </returns>
>         [HttpPut("undo", Name = "UndoMerges")]
> ```
This will need to be reverted to "merge" / "merge was" / "UndoMerge".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-30 20:11 UTC, WeJamUS commented
___
*[Backend/Controllers/MergeController.cs, line 57 at r23](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MiNLeRp03_TjRhEmte-:-MiNg42-2SXoFS4qE_to:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/1e67e6aa8eeeb3f34f2bdd64d5c43d60a24ef6f2/Backend/Controllers/MergeController.cs#L57)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Let's remove the Undo all, and change this to only take a single `MergeUndoIds` instead of an array. Then you can `await _mergeService.UndoMerge(projectId, mergeIds);` And you'll need to rerun OpenApi generation.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-30 20:11 UTC, WeJamUS commented
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 47 at r23](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MiNLQPV-kOIF3PGAaxT:-MiNg8UZ45OuZtkNmjD8:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/1e67e6aa8eeeb3f34f2bdd64d5c43d60a24ef6f2/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L47)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>       <UndoButton
>         merges={changes.merges}
>         textId="mergeDups.undo.undoAll"
>         dialogId="mergeDups.undo.undoAllDialog"
>         disabledId="mergeDups.undo.undoAllDisabled"
>       />
> ```
Let's remove the Undo All.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-30 20:12 UTC, WeJamUS commented
___
*[src/resources/translations.json, line 801 at r23](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MiNLX2l6eZVsOaesiGU:-MiNgAdtEnIddhVzdRmo:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/1e67e6aa8eeeb3f34f2bdd64d5c43d60a24ef6f2/src/resources/translations.json#L801)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>       "undoAll": ["Undo All Merges", "Undo All Merges", "Undo All Merges"],
>       "undoAllDialog": [
>         "Undo all merges from in this session?",
>         "Undo all merges from in this session?",
>         "Undo all merges from in this session?"
>       ],
>       "undoAllDisabled": [
>         "Undo All Unavailable",
>         "Undo All Unavailable",
>         "Undo All Unavailable"
>       ],
> ```
Let's remove the Undo All.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-30 20:37 UTC, WeJamUS commented
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 103 at r23](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MiNInsIENwT8geCmHtv:-MiNlzLrA4gG1Tj2FKYZ:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/1e67e6aa8eeeb3f34f2bdd64d5c43d60a24ef6f2/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L103)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

> ```
>         <UndoButton
>           merges={[change]}
>           textId="mergeDups.undo.undo"
>           dialogId="mergeDups.undo.undoDialog"
>           disabledId="mergeDups.undo.undoDisabled"
>         />
> ```
Let's work a little on the visual of this button.
First, it would benefit from an outline, so it's clearly a button even when the cursor isn't over it.
Second, try to vertically center it, like the arrow. You can try a `Grid` around a `div` around the `UndoButton`, where the `div` has the same `style` as the `ArrowRightAlt`, though I'm not sure that will place the button quite right, it's a starting place.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-30 20:59 UTC, imnasnainaec requested changes
> Reviewed 8 of 10 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1300)* status: 18 of 20 files reviewed, 6 unresolved discussions (waiting on @JacobHaimes, @johnthagen, and @WeJamUS)

___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 129 at r24](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MiNpdui6ioi7qzBfTh4:-MiNpdui6ioi7qzBfTh5:b-lugco7) ([raw file](https://github.com/sillsdev/thecombine/blob/b70d23006bc51c4b9c623fc173040c8d22026943/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L129)):*
> ```XML
>       <Grid container direction="column" justify="center">
>         <div>
>           <Button onClick={() => setUndoDialogOpen(true)}>
> ```

Let's make this button outlined (https://material-ui.com/components/buttons/#outlined-buttons) and give it
```
id={`merge-undo-${'-'.join(merge.parentIds)}`}
```
___
*[src/goals/MergeDupGoal/MergeDupComponent/tests/MergeDupsCompleted.test.tsx, line 18 at r24](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MiNqurLC5cvuK6XgzXM:-MiNqurLC5cvuK6XgzXN:b59opai) ([raw file](https://github.com/sillsdev/thecombine/blob/b70d23006bc51c4b9c623fc173040c8d22026943/src/goals/MergeDupGoal/MergeDupComponent/tests/MergeDupsCompleted.test.tsx#L18)):*
> ```
>   it("should return false since words doesn't contain all of the parentIds in merge", () => {
>   ...
>   it("should return true since words contains all the parentIds in merge", () => {
> ```
For consistent wording across your `it`s, let's change "since" -> "if"


<!-- Sent from Reviewable.io -->

2021-08-30 21:53 UTC, WeJamUS commented
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 129 at r24](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MiNpdui6ioi7qzBfTh4:-MiO2STd6wTN6qOO0plE:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/b70d23006bc51c4b9c623fc173040c8d22026943/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L129)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Let's make this button outlined (https://material-ui.com/components/buttons/#outlined-buttons) and give it
```
id={`merge-undo-${'-'.join(merge.parentIds)}`}
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-30 22:32 UTC, imnasnainaec requested changes
> Reviewed 1 of 1 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1300)* status: 18 of 20 files reviewed, 6 unresolved discussions (waiting on @JacobHaimes, @johnthagen, and @WeJamUS)

___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 129 at r24](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MiNpdui6ioi7qzBfTh4:-MiOAoqG1M9tvhhU1c9f:bwghjuu) ([raw file](https://github.com/sillsdev/thecombine/blob/b70d23006bc51c4b9c623fc173040c8d22026943/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L129)):*
<details><summary><i>Previously, WeJamUS (James Wu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oh, I had my `string` and `string[]` reversed. That should be 
```
            id={`merge-undo-${props.merge.parentIds.join("-")}`}
```
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 127 at r26](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MiOAIUD60U4qL1x4DDG:-MiOAIUGDJWm7VfMwVcI:b-4m16ds) ([raw file](https://github.com/sillsdev/thecombine/blob/090814c9fd9b43b3ecc5afe6227518aa51fdb8ab/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L127)):*
> ```XML
>   if (isUndoBtnEnabled) {
>     return (
>       <Grid container direction="column" justify="center">
> ```

I just checked the web console testing this and saw a warning.`Grid` property `justify` is deprecated, so it should be replaced here and below with `justifyContent`.


<!-- Sent from Reviewable.io -->

2021-08-30 22:50 UTC, WeJamUS commented
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 127 at r26](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MiOAIUD60U4qL1x4DDG:-MiOFKg10ALdjjJW61u8:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/090814c9fd9b43b3ecc5afe6227518aa51fdb8ab/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L127)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I just checked the web console testing this and saw a warning.`Grid` property `justify` is deprecated, so it should be replaced here and below with `justifyContent`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-30 22:50 UTC, WeJamUS commented
___
*[src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx, line 129 at r24](https://reviewable.io/reviews/sillsdev/thecombine/1300#-MiNpdui6ioi7qzBfTh4:-MiOFMwx4V3MbumVbU9i:b-896fix) ([raw file](https://github.com/sillsdev/thecombine/blob/b70d23006bc51c4b9c623fc173040c8d22026943/src/goals/MergeDupGoal/MergeDupComponent/MergeDupsCompleted.tsx#L129)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Oh, I had my `string` and `string[]` reversed. That should be 
```
            id={`merge-undo-${props.merge.parentIds.join("-")}`}
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-31 01:08 UTC, imnasnainaec approved these changes
> Reviewed 1 of 2 files at r25, 1 of 1 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/1300)* status: all files reviewed, 4 unresolved discussions (waiting on @JacobHaimes and @johnthagen)



<!-- Sent from Reviewable.io -->

2021-08-31 13:45 UTC, merged