Update GoalTimeline component to use redux toolkit
sillsdev/TheCombine pull request #2465
Opened 2023-08-10 14:51 UTC by jmgrady

2023-08-14 13:50 UTC, imnasnainaec requested changes
> Reviewed 4 of 40 files at r3, 1 of 44 files at r4, 22 of 56 files at r5, 9 of 28 files at r7, 3 of 10 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 39 of 80 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

___
*[`README.md` line 473 at r8](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NboFsf9ERUMBq3oAYmk:-NboFsf9ERUMBq3oAYml:b-zh0wdm) ([raw file](https://github.com/sillsdev/TheCombine/blob/6457c20816dcea440d431888f2458096bcd1628a/README.md#L473)):*
> ```Markdown
> 
> ```bash
> python scripts/generate-rtk-query.py --backend
> ```

These two `python scripts/generate-rtk-query.py` should be `python scripts/generate_rtk_query.py`
___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 255 at r8](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NboHTAr1Fn7vVUqkhOO:-NboHTAr1Fn7vVUqkhOP:babztrm) ([raw file](https://github.com/sillsdev/TheCombine/blob/6457c20816dcea440d431888f2458096bcd1628a/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L255)):*
> ```XML
>       expect(currentGoal.currentStep).toEqual(i + 1);
>       // verify step is updated from the data
>       // verify dispatchMergeStepData is called
> ```

It looks like tests were intended for these two comments. Either add tests or remove comments.


<!-- Sent from Reviewable.io -->

2023-08-14 17:58 UTC, imnasnainaec reviewed
> Reviewed 2 of 34 files at r1, 14 of 56 files at r5, 1 of 28 files at r7, 1 of 10 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 65 of 80 files reviewed, 3 unresolved discussions (waiting on @jmgrady)

___
*[`README.md` line 456 at r9](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nbp8l822lrFQLPa5nQ4:-Nbp8l822lrFQLPa5nQ5:bp9g4yv) ([raw file](https://github.com/sillsdev/TheCombine/blob/4263492e6044372222164aca75d7a720b15973d3/README.md#L456)):*
> ```Markdown
> ```
> 
> ### Generate API Files for RTK Query
> ```

It might be nice for the `#using-openapi` and `#generate-api-files-for-rtk-query` sections to reference each other, especially since both need to be updated when `Backend/controllers` functions are changed (until our use of OpenAPI is phased out).
___
*[`src/components/GoalTimeline/DefaultState.ts` line 15 at r9](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbpAPvvDxdHt1QBaUhN:-NbpAPvvDxdHt1QBaUhO:b60wkzn) ([raw file](https://github.com/sillsdev/TheCombine/blob/4263492e6044372222164aca75d7a720b15973d3/src/components/GoalTimeline/DefaultState.ts#L15)):*
> ```XML
>   history: [],
>   previousGoalType: GoalType.Default,
> };
> ```

`implementedTypes` and `defaultState` are duplicated here and in `src/components/GoalTimeline/Redux/GoalReduxTypes.ts`.
___
*[`src/components/GoalTimeline/index.tsx` line 121 at r9](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbpBbeT2Yvt2tgq39ju:-NbpBbeT2Yvt2tgq39jv:b-hvn7sb) ([raw file](https://github.com/sillsdev/TheCombine/blob/4263492e6044372222164aca75d7a720b15973d3/src/components/GoalTimeline/index.tsx#L121)):*
> ```XML
>         onClick={() => chooseGoal(goal)}
>         id={`new-goal-${goal.name}`}
>         role="goal-button"
> ```

Should we be overriding `role` with a custom value? https://www.w3schools.com/accessibility/accessibility_role_name_value.php


<!-- Sent from Reviewable.io -->

2023-08-14 18:04 UTC, imnasnainaec reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 65 of 80 files reviewed, 5 unresolved discussions (waiting on @jmgrady)

___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 138 at r9](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbpCp9i2Tw1qoThTYY2:-NbpCp9i2Tw1qoThTYY3:b648n77) ([raw file](https://github.com/sillsdev/TheCombine/blob/4263492e6044372222164aca75d7a720b15973d3/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L138)):*
> ```XML
>       renderWithProviders(<GoalTimeline />, { store: store });
>       await store.dispatch(setCurrentGoal());
>     });
> ```

`setCurrentGoal()` is synchronous, so this await should be dropped.
___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 334 at r9](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbpCNvF2FY6Kia1EMpD:-NbpCNvF2FY6Kia1EMpE:b-77i5t4) ([raw file](https://github.com/sillsdev/TheCombine/blob/4263492e6044372222164aca75d7a720b15973d3/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L334)):*
> ```XML
>     //   - dispatch asyncUpdateGoal(new goal)
>     await act(async () => {
>       await store.dispatch(asyncAddCompletedMergeToGoal(mockCompletedMerge));
> ```

`store.dispatch(asyncAddCompletedMergeToGoal(mockCompletedMerge))` is not async and needs no `await` (and probably needs `async` removed from its name).


<!-- Sent from Reviewable.io -->

2023-08-14 18:14 UTC, imnasnainaec reviewed
> Reviewed 1 of 56 files at r5, 1 of 28 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 67 of 80 files reviewed, 5 unresolved discussions (waiting on @jmgrady)

___
*[`README.md` line 456 at r9](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nbp8l822lrFQLPa5nQ4:-NbpEpqh4nlc6YAcwTT2:b-igedmg) ([raw file](https://github.com/sillsdev/TheCombine/blob/4263492e6044372222164aca75d7a720b15973d3/README.md#L456)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

It might be nice for the `#using-openapi` and `#generate-api-files-for-rtk-query` sections to reference each other, especially since both need to be updated when `Backend/controllers` functions are changed (until our use of OpenAPI is phased out).
</blockquote></details>

By "use of OpenApi is phased out", I meant "use of @openapitools/openapi-generator-cli to generate `src/api/` is phased out".

But now I'm wondering, if this pr doesn't import anything from `src/rtk-query/`, why are those files included? Just the script to generate them should be sufficient groundwork for future use.


<!-- Sent from Reviewable.io -->

2023-08-14 20:16 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 45 of 81 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

___
*[`README.md` line 456 at r9](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nbp8l822lrFQLPa5nQ4:-NbpbT0b1ITUnMNc9H-3:b-5sx9vt) ([raw file](https://github.com/sillsdev/TheCombine/blob/4263492e6044372222164aca75d7a720b15973d3/README.md#L456)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

By "use of OpenApi is phased out", I meant "use of @openapitools/openapi-generator-cli to generate `src/api/` is phased out".

But now I'm wondering, if this pr doesn't import anything from `src/rtk-query/`, why are those files included? Just the script to generate them should be sufficient groundwork for future use.
</blockquote></details>

I was wondering the same thing and was going to ask your opinion but instead chose to get the PR to be reviewable.
I do not think we will be migrating to `rtk-query` before we have migrated all of the redux store to `rtk-toolkit` but I do not want to lose the script.  I will do the following to resolve this:
1. create a new branch for the `rtk-query` work;
2. Move the script and all the generated files to that branch;
3. Revert the changes to the README.md.
___
*[`src/components/GoalTimeline/DefaultState.ts` line 15 at r9](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbpAPvvDxdHt1QBaUhN:-Nbpe68t5SS1r5q-tdin:bk1nw72) ([raw file](https://github.com/sillsdev/TheCombine/blob/4263492e6044372222164aca75d7a720b15973d3/src/components/GoalTimeline/DefaultState.ts#L15)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`implementedTypes` and `defaultState` are duplicated here and in `src/components/GoalTimeline/Redux/GoalReduxTypes.ts`.
</blockquote></details>

Done.
Removed `src/components/GoalTimeline/Redux/GoalReduxTypes.ts`.
___
*[`src/components/GoalTimeline/index.tsx` line 121 at r9](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbpBbeT2Yvt2tgq39ju:-NbpeEyy8gwWxwjdAH3e:b-ld2ze5) ([raw file](https://github.com/sillsdev/TheCombine/blob/4263492e6044372222164aca75d7a720b15973d3/src/components/GoalTimeline/index.tsx#L121)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Should we be overriding `role` with a custom value? https://www.w3schools.com/accessibility/accessibility_role_name_value.php
</blockquote></details>

No we should not.  I was not aware that it had a specific use for accessibility (obviously).  I will find a different method.
___
*[`src/components/GoalTimeline/Redux/GoalReducer.ts` line 80 at r9](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbooiGV7CYvn-FBhn3q:-NbpeX2a7yhdWrBMiykQ:b-clxji6) ([raw file](https://github.com/sillsdev/TheCombine/blob/4263492e6044372222164aca75d7a720b15973d3/src/components/GoalTimeline/Redux/GoalReducer.ts#L80)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Currently none of the reducers are an `export default`, but perhaps they should be. If you agree, `export default goalSlice.reducer;` here could set the pattern for future slice-implemented reducers.
</blockquote></details>

Done.
As a noob I was actually under the opposite impression.  `grep` proved me wrong!
___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 138 at r9](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbpCp9i2Tw1qoThTYY2:-Nbpetkm4sHwPXsU9D3s:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/4263492e6044372222164aca75d7a720b15973d3/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L138)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`setCurrentGoal()` is synchronous, so this await should be dropped.
</blockquote></details>

Done.
___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 202 at r9](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NboprUQ0lV1kHeCeL_G:-Nbpeya51AeVHBBbvJAY:b-8g29qq) ([raw file](https://github.com/sillsdev/TheCombine/blob/4263492e6044372222164aca75d7a720b15973d3/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L202)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

For readability, it might be nice to have a newline between `it(...`s
Likewise, or more-so, between `describes(...`s.
</blockquote></details>

Done.
(if I understood your request properly)
___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 334 at r9](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbpCNvF2FY6Kia1EMpD:-NbpgDHf8pIgKtoLqtHp:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/4263492e6044372222164aca75d7a720b15973d3/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L334)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`store.dispatch(asyncAddCompletedMergeToGoal(mockCompletedMerge))` is not async and needs no `await` (and probably needs `async` removed from its name).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-14 20:28 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 45 of 81 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[`src/components/GoalTimeline/index.tsx` line 121 at r9](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbpBbeT2Yvt2tgq39ju:-Nbpix8M6I5PD3jsoYpX:b-z0q7gb) ([raw file](https://github.com/sillsdev/TheCombine/blob/4263492e6044372222164aca75d7a720b15973d3/src/components/GoalTimeline/index.tsx#L121)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

No we should not.  I was not aware that it had a specific use for accessibility (obviously).  I will find a different method.
</blockquote></details>

Done.
I was able to use `data-testid` instead.


<!-- Sent from Reviewable.io -->

2023-08-14 21:22 UTC, imnasnainaec reviewed
> Reviewed 1 of 40 files at r3, 25 of 31 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 71 of 81 files reviewed, 9 unresolved discussions (waiting on @jmgrady)

___
*[`.gitignore` line 74 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbpqNkd6uD5wr9oSOLk:-NbpqNkd6uD5wr9oSOLl:b-yy9yko) ([raw file](https://github.com/sillsdev/TheCombine/blob/28dcc73c68aac62b03de6c27b3e57b11894d82e5/.gitignore#L74)):*
> ```ignore
> # from openapi schema file
> src/rtk-query/openapi-*.ts
> src/rtk-query/openapi.json
> ```

Split this off with the other rtk-query stuff?
___
*[`codecov.yml` line 5 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbpqYFUBGWpMmpcsQBB:-NbpqYFUBGWpMmpcsQBC:bgcfrot) ([raw file](https://github.com/sillsdev/TheCombine/blob/28dcc73c68aac62b03de6c27b3e57b11894d82e5/codecov.yml#L5)):*
> ```YAML
>   - "src/backend/index.ts"
>   - "src/resources"
>   - "src/rtk-query"
> ```

Split this change off as well?
___
*[`package.json` line 108 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nbppxxq-zkFKaeOCew5:-Nbppxxq-zkFKaeOCew6:bgarny2) ([raw file](https://github.com/sillsdev/TheCombine/blob/28dcc73c68aac62b03de6c27b3e57b11894d82e5/package.json#L108)):*
> ```JSON
>     "@typescript-eslint/eslint-plugin": "^5.60.1",
>     "@typescript-eslint/parser": "^5.60.1",
>     "esbuild-runner": "^2.2.2",
> ```

Are `"@rtk-query/codegen-openapi"` and `"esbuild-runner"` used, now that the rtk-query part has been split off?
___
*[`README.md` line 58 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nbpq84I6z_TVW0SM6Km:-Nbpq84I6z_TVW0SM6Kn:bykl38b) ([raw file](https://github.com/sillsdev/TheCombine/blob/28dcc73c68aac62b03de6c27b3e57b11894d82e5/README.md#L58)):*
> ```Markdown
>    6. [Inspect Database](#inspect-database)
>    7. [Cleanup Local Repository](#cleanup-local-repository)
>    8. [Generate API Files for RTK Query](#generate-api-files-for-rtk-query)
> ```

Vestigial ToC entry
___
*[`scripts/files/openapi-config.json` line 7 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbpqdtV2P1_o5PiyGIl:-NbpqdtV2P1_o5PiyGIm:bibb3xt) ([raw file](https://github.com/sillsdev/TheCombine/blob/28dcc73c68aac62b03de6c27b3e57b11894d82e5/scripts/files/openapi-config.json#L7)):*
> ```JSON
>   "outputFiles": {},
>   "hooks": true
> }
> ```

Does this also go with the rtk-query stuff?
___
*[`src/store.ts` line 5 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbprAQQEFHVEJaTaaQ5:-NbprAQQEFHVEJaTaaQ6:b-dkhfq8) ([raw file](https://github.com/sillsdev/TheCombine/blob/28dcc73c68aac62b03de6c27b3e57b11894d82e5/src/store.ts#L5)):*
> ```XML
> import storage from "redux-persist/lib/storage";
> 
> import type { PreloadedState } from "@reduxjs/toolkit";
> ```

I wasn't familiar with this `import type ...` pattern (though I now see we have it in `src/types/hooks.ts`). Is there any particular reason to prefer it over `import { configureStore, PreloadedState } from "@reduxjs/toolkit";`?
___
*[`src/components/GoalTimeline/Redux/GoalActions.ts` line 41 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbptLb20eguyeHaeBj7:-NbptLb20eguyeHaeBj8:b-7up5ia) ([raw file](https://github.com/sillsdev/TheCombine/blob/28dcc73c68aac62b03de6c27b3e57b11894d82e5/src/components/GoalTimeline/Redux/GoalActions.ts#L41)):*
> ```XML
> 
> export function setCurrentGoal(goal?: Goal): PayloadAction {
>   if (goal == null) {
> ```

`===`
___
*[`src/components/GoalTimeline/Redux/GoalReducer.ts` line 16 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbpsWmSBIeHY7jTwXEH:-NbpsWmSBIeHY7jTwXEI:b-7up5ia) ([raw file](https://github.com/sillsdev/TheCombine/blob/28dcc73c68aac62b03de6c27b3e57b11894d82e5/src/components/GoalTimeline/Redux/GoalReducer.ts#L16)):*
> ```XML
>   reducers: {
>     addCompletedMergeToGoalAction: (state, action) => {
>       if (state.currentGoal.goalType == GoalType.MergeDups) {
> ```

`===`
___
*[`src/goals/MergeDuplicates/Redux/MergeDupsActions.ts` line 269 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbpuzpnBl1gFNgN-Pjn:-NbpuzpnBl1gFNgN-Pjo:b-yzj6gb) ([raw file](https://github.com/sillsdev/TheCombine/blob/28dcc73c68aac62b03de6c27b3e57b11894d82e5/src/goals/MergeDuplicates/Redux/MergeDupsActions.ts#L269)):*
> ```XML
>         // need to look up the currentGoal again since the previous dispatch
>         // will result in a new goal object
>         await dispatch(asyncUpdateGoal(getState().goalsState.currentGoal));
> ```

There seems to be some redundancy introduced here, since the only effect that `asyncUpdateGoal` has on the state is to `dispatch(setCurrentGoal(goal))` on the argument/input `goal`. But in this case, that input _is_ the current goal.


<!-- Sent from Reviewable.io -->

2023-08-15 10:46 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 71 of 81 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[`.gitignore` line 74 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbpqNkd6uD5wr9oSOLk:-Nbs_ifR5cUNw_oCIw0h:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/28dcc73c68aac62b03de6c27b3e57b11894d82e5/.gitignore#L74)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Split this off with the other rtk-query stuff?
</blockquote></details>

Done.
___
*[`codecov.yml` line 5 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbpqYFUBGWpMmpcsQBB:-Nbsa1-7A7ih2QBsbyWF:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/28dcc73c68aac62b03de6c27b3e57b11894d82e5/codecov.yml#L5)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Split this change off as well?
</blockquote></details>

Done.
___
*[`package.json` line 108 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nbppxxq-zkFKaeOCew5:-Nbsa2QD3AUl1ZIjjYuQ:b-60o8p) ([raw file](https://github.com/sillsdev/TheCombine/blob/28dcc73c68aac62b03de6c27b3e57b11894d82e5/package.json#L108)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Are `"@rtk-query/codegen-openapi"` and `"esbuild-runner"` used, now that the rtk-query part has been split off?
</blockquote></details>

No they are not.
Done.
___
*[`README.md` line 58 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nbpq84I6z_TVW0SM6Km:-NbsaR5Q49aGS-VTVqwn:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/28dcc73c68aac62b03de6c27b3e57b11894d82e5/README.md#L58)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Vestigial ToC entry
</blockquote></details>

Done.
___
*[`scripts/files/openapi-config.json` line 7 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbpqdtV2P1_o5PiyGIl:-Nbsb9P7Bh6LIiuxSqfb:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/28dcc73c68aac62b03de6c27b3e57b11894d82e5/scripts/files/openapi-config.json#L7)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Does this also go with the rtk-query stuff?
</blockquote></details>

Done.
___
*[`src/store.ts` line 5 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbprAQQEFHVEJaTaaQ5:-NbsbBxtBpQI5bvD3hu4:b1g3igb) ([raw file](https://github.com/sillsdev/TheCombine/blob/28dcc73c68aac62b03de6c27b3e57b11894d82e5/src/store.ts#L5)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I wasn't familiar with this `import type ...` pattern (though I now see we have it in `src/types/hooks.ts`). Is there any particular reason to prefer it over `import { configureStore, PreloadedState } from "@reduxjs/toolkit";`?
</blockquote></details>

This is from the example in Redux documentation on Writing Tests, specifically, the [Setting Up a Reusable Test Render Function](https://redux.js.org/usage/writing-tests#setting-up-a-reusable-test-render-function) section.  In both cases, only a type is exported.  It may be to make it clearer to a developer/maintainer that this is a type and not a value.
___
*[`src/components/GoalTimeline/Redux/GoalActions.ts` line 41 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbptLb20eguyeHaeBj7:-NbsdOvk6sPv4CDcsdg_:b-ralozz) ([raw file](https://github.com/sillsdev/TheCombine/blob/28dcc73c68aac62b03de6c27b3e57b11894d82e5/src/components/GoalTimeline/Redux/GoalActions.ts#L41)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`===`
</blockquote></details>

Actually, this was testing for null or undefined.  I changed the structure of the function to use a more standard (to my understanding) way of testing for this:
```
export function setCurrentGoal(goal?: Goal): PayloadAction {
  if (goal) {
     return setCurrentGoalAction({ ...goal });
  }
  return setCurrentGoalAction(new Goal());
}
```
___
*[`src/components/GoalTimeline/Redux/GoalReducer.ts` line 16 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbpsWmSBIeHY7jTwXEH:-NbsdbS70GdcvFb7NId5:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/28dcc73c68aac62b03de6c27b3e57b11894d82e5/src/components/GoalTimeline/Redux/GoalReducer.ts#L16)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`===`
</blockquote></details>

Done.
___
*[`src/goals/MergeDuplicates/Redux/MergeDupsActions.ts` line 269 at r10](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbpuzpnBl1gFNgN-Pjn:-NbsmL0V8fP8GbCnlWyh:b-iddzm1) ([raw file](https://github.com/sillsdev/TheCombine/blob/28dcc73c68aac62b03de6c27b3e57b11894d82e5/src/goals/MergeDuplicates/Redux/MergeDupsActions.ts#L269)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

There seems to be some redundancy introduced here, since the only effect that `asyncUpdateGoal` has on the state is to `dispatch(setCurrentGoal(goal))` on the argument/input `goal`. But in this case, that input _is_ the current goal.
</blockquote></details>

Done.
This had been done this way because the `CharacterInventory` goal was passing in a new goal to `asyncUpdateGoal`.  It is a simple matter to move the `setCurrentGoal()` call from `asyncUpdateGoal` to the `CharacterInventory` function.  See changes to  `src/goals/CharacterInventory/Redux/CharacterInventoryActions.ts`


<!-- Sent from Reviewable.io -->

2023-08-15 13:58 UTC, imnasnainaec requested changes
> Reviewed 1 of 28 files at r7, 4 of 11 files at r11, 16 of 16 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 86 of 96 files reviewed, 3 unresolved discussions (waiting on @jmgrady)

*[a discussion](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbtQfGL7g8Ncu4K1FWd:-NbtQfGL7g8Ncu4K1FWe:b-acp92y) (no related file):*
Revert `package-lock.json` too?

___
*[a discussion](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbtThPz1bXQAtdqdTp3:-NbtThPz1bXQAtdqdTp4:b738o11) (no related file):*
Console error in the CharInv goal when accepting a character:
```
immutableStateInvariantMiddleware.ts:25
Uncaught Error: Invariant failed: A state mutation was detected inside a dispatch, in the path: characterInventoryState.characterSet.0.status. Take a look at the reducer(s) handling the action {"type":"ADD_TO_VALID_CHARACTERS","payload":["a"]}. (https://redux.js.org/style-guide/style-guide#do-not-mutate-state)
    at invariant (immutableStateInvariantMiddleware.ts:25:1)
    at immutableStateInvariantMiddleware.ts:273:1
    at Object.measureTime (utils.ts:10:1)
    at immutableStateInvariantMiddleware.ts:266:1
    at dispatch (redux.js:691:1)
    at CharacterInventoryActions.ts:99:1
    at index.js:16:1
    at Object.dispatch (immutableStateInvariantMiddleware.ts:264:1)
    at dispatch (<anonymous>:1:55424)
    at accept (CharacterStatusControl.tsx:19:1)
invariant @ immutableStateInvariantMiddleware.ts:25
(anonymous) @ immutableStateInvariantMiddleware.ts:273
measureTime @ utils.ts:10
(anonymous) @ immutableStateInvariantMiddleware.ts:266
dispatch @ redux.js:691
(anonymous) @ CharacterInventoryActions.ts:99
(anonymous) @ index.js:16
(anonymous) @ immutableStateInvariantMiddleware.ts:264
dispatch @ VM10:1
accept @ CharacterStatusControl.tsx:19
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
executeDispatch @ react-dom.development.js:8243
processDispatchQueueItemsInOrder @ react-dom.development.js:8275
processDispatchQueue @ react-dom.development.js:8288
dispatchEventsForPlugins @ react-dom.development.js:8299
(anonymous) @ react-dom.development.js:8508
batchedEventUpdates$1 @ react-dom.development.js:22396
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
```

___
___
*[`src/components/GoalTimeline/Redux/GoalActions.ts` line 164 at r14](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbtQzc6EyRyIcvF9DQN:-NbtQzc6EyRyIcvF9DQO:b89l0o7) ([raw file](https://github.com/sillsdev/TheCombine/blob/5608a118ffc81b7889ce02474504d774c2ea4012/src/components/GoalTimeline/Redux/GoalActions.ts#L164)):*
> ```XML
> 
> export function asyncUpdateGoal() {
>   return async (dispatch: StoreStateDispatch, getState: () => StoreState) => {
> ```

Maybe `_` or `_dispatch` since the first argument is no longer used.


<!-- Sent from Reviewable.io -->

2023-08-15 18:17 UTC, jmgrady reviewed
Per our Slack discussion, set `REACT_APP_IMMUTABLE_CHECK=0` in `.env.development.local` or remove the file.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-:-NbuApL01CfyxATVChV-:bywk5qo)* status: 86 of 114 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

*[a discussion](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbtThPz1bXQAtdqdTp3:-NbuBOezDinPkwzIXmkX:bywk5qo) (no related file):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Console error in the CharInv goal when accepting a character:
```
immutableStateInvariantMiddleware.ts:25
Uncaught Error: Invariant failed: A state mutation was detected inside a dispatch, in the path: characterInventoryState.characterSet.0.status. Take a look at the reducer(s) handling the action {"type":"ADD_TO_VALID_CHARACTERS","payload":["a"]}. (https://redux.js.org/style-guide/style-guide#do-not-mutate-state)
    at invariant (immutableStateInvariantMiddleware.ts:25:1)
    at immutableStateInvariantMiddleware.ts:273:1
    at Object.measureTime (utils.ts:10:1)
    at immutableStateInvariantMiddleware.ts:266:1
    at dispatch (redux.js:691:1)
    at CharacterInventoryActions.ts:99:1
    at index.js:16:1
    at Object.dispatch (immutableStateInvariantMiddleware.ts:264:1)
    at dispatch (<anonymous>:1:55424)
    at accept (CharacterStatusControl.tsx:19:1)
invariant @ immutableStateInvariantMiddleware.ts:25
(anonymous) @ immutableStateInvariantMiddleware.ts:273
measureTime @ utils.ts:10
(anonymous) @ immutableStateInvariantMiddleware.ts:266
dispatch @ redux.js:691
(anonymous) @ CharacterInventoryActions.ts:99
(anonymous) @ index.js:16
(anonymous) @ immutableStateInvariantMiddleware.ts:264
dispatch @ VM10:1
accept @ CharacterStatusControl.tsx:19
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
executeDispatch @ react-dom.development.js:8243
processDispatchQueueItemsInOrder @ react-dom.development.js:8275
processDispatchQueue @ react-dom.development.js:8288
dispatchEventsForPlugins @ react-dom.development.js:8299
(anonymous) @ react-dom.development.js:8508
batchedEventUpdates$1 @ react-dom.development.js:22396
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
```
</blockquote></details>

Per our Slack discussion, set `REACT_APP_IMMUTABLE_CHECK=0` in `.env.development.local` or remove the file.

___
*[a discussion](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbtQfGL7g8Ncu4K1FWd:-NbuPcGk5-xhWhk6dBsq:b186ian) (no related file):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Revert `package-lock.json` too?
</blockquote></details>

Reconciled `package-lock.json` with `master`.

___
___
*[`src/components/GoalTimeline/Redux/GoalActions.ts` line 164 at r14](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbtQzc6EyRyIcvF9DQN:-NbtkpKy8L-bYNcPRWbb:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/5608a118ffc81b7889ce02474504d774c2ea4012/src/components/GoalTimeline/Redux/GoalActions.ts#L164)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Maybe `_` or `_dispatch` since the first argument is no longer used.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-15 18:29 UTC, imnasnainaec reviewed
> Reviewed 18 of 18 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 104 of 114 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

*[a discussion](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbtQfGL7g8Ncu4K1FWd:-NbuRS0YAM6fmhA3E4de:b-phuwco) (no related file):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Reconciled `package-lock.json` with `master`.
</blockquote></details>

It still shows a diff.

___
___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 323 at r18](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbuSF0wBbBiX3yjk1qw:-NbuSF0x0GLM9o2Zd_ZK:b-ru6vmu) ([raw file](https://github.com/sillsdev/TheCombine/blob/93517c2cf822242473c1b39dadccff77127832ce/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L323)):*
> ```XML
>     //   .changes as CharInvChanges;
>     // expect(changes!.charChanges).toEqual(mockCharInvChanges);
>     //  - backend is called to addGoalToUserEdit
> ```

Residual commented code?


<!-- Sent from Reviewable.io -->

2023-08-15 19:23 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 104 of 114 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec)

___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 323 at r18](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbuSF0wBbBiX3yjk1qw:-NbuczVs7HsUe1iRO-PD:b-a5z8pl) ([raw file](https://github.com/sillsdev/TheCombine/blob/93517c2cf822242473c1b39dadccff77127832ce/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L323)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Residual commented code?
</blockquote></details>

Done.
Yes, it is.


<!-- Sent from Reviewable.io -->

2023-08-15 20:36 UTC, imnasnainaec reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 104 of 114 files reviewed, 4 unresolved discussions (waiting on @jmgrady)

___
*[`src/store.ts` line 17 at r19](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nbut3hb1Aq1s8uhYv2c:-Nbut3hb1Aq1s8uhYv2d:b-ucbkrj) ([raw file](https://github.com/sillsdev/TheCombine/blob/233e882a62c467294000168b69cefd16a8b74985/src/store.ts#L17)):*
> ```XML
> const immutableCheckConfig =
>   process.env.NODE_ENV == "development" &&
>   process.env.REACT_APP_IMMUTABLE_CHECK == "1"
> ```

`===`?
___
*[`src/store.ts` line 35 at r19](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbussdY5e4XpwOW0gOq:-NbussdY5e4XpwOW0gOr:bqve7i2) ([raw file](https://github.com/sillsdev/TheCombine/blob/233e882a62c467294000168b69cefd16a8b74985/src/store.ts#L35)):*
> ```XML
>         serializableCheck: false,
>       }),
>     devTools: true,
> ```

Should we perhaps have `devTools: process.env.NODE_ENV === "development"`?
___
*[`src/components/GoalTimeline/Redux/GoalActions.ts` line 19 at r19](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbutfDi3XBK-6uR2vg5:-NbutfDi3XBK-6uR2vg6:bf91ldz) ([raw file](https://github.com/sillsdev/TheCombine/blob/233e882a62c467294000168b69cefd16a8b74985/src/components/GoalTimeline/Redux/GoalActions.ts#L19)):*
> ```XML
>   dispatchMergeStepData,
>   fetchMergeDupsData,
> } from "goals/MergeDuplicates/Redux/MergeDupsActions";
> ```

Since ` dispatchMergeStepData` and `fetchMergeDupsData` are both exported from `goals/MergeDuplicates/Redux/MergeDupsActions.ts` and only used here, perhaps their definitions should be moved here.


<!-- Sent from Reviewable.io -->

2023-08-15 20:47 UTC, imnasnainaec reviewed
> Reviewed 1 of 11 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 105 of 114 files reviewed, 5 unresolved discussions (waiting on @jmgrady)

*[a discussion](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbuuoE96ED67ELuirFR:-NbuuoE96ED67ELuirFS:b-dvpbg6) (no related file):*
`test-utils.tsx` -> `testUtilities.tsx`

___
___
*[`src/utilities/test-utils.tsx` line 19 at r19](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbuwHpi8tGf1MDB99yo:-NbuwHpi8tGf1MDB99yp:b-oe387q) ([raw file](https://github.com/sillsdev/TheCombine/blob/233e882a62c467294000168b69cefd16a8b74985/src/utilities/test-utils.tsx#L19)):*
> ```XML
> }
> 
> export function renderWithProviders(
> ```

It'd be nice to have a return type on this function, but I have no idea what that would be. :)


<!-- Sent from Reviewable.io -->

2023-08-16 14:56 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 105 of 114 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

*[a discussion](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbtQfGL7g8Ncu4K1FWd:-NbygMDb9YcSBnGzTUX2:b-896fix) (no related file):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

It still shows a diff.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbuuoE96ED67ELuirFR:-Nbyi2bJDBmAzzxfY9C0:bb6un1j) (no related file):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`test-utils.tsx` -> `testUtilities.tsx`
</blockquote></details>

Done

___
___
*[`src/store.ts` line 17 at r19](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nbut3hb1Aq1s8uhYv2c:-NbyjIqr7YMeb08oLKFI:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/233e882a62c467294000168b69cefd16a8b74985/src/store.ts#L17)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`===`?
</blockquote></details>

Done.
___
*[`src/store.ts` line 35 at r19](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbussdY5e4XpwOW0gOq:-NbyjxRGB_RmTcZq2ZQA:bcjrsgq) ([raw file](https://github.com/sillsdev/TheCombine/blob/233e882a62c467294000168b69cefd16a8b74985/src/store.ts#L35)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Should we perhaps have `devTools: process.env.NODE_ENV === "development"`?
</blockquote></details>

Done.
Short answer: Probably.
Long answer: While the default value for `immutableCheck` is only `true` for development builds (see this [doc](https://redux-toolkit.js.org/api/getDefaultMiddleware#included-default-middleware)), the default value for `devTools` is `true` for all builds (see this [other doc](https://redux-toolkit.js.org/api/configurestore/#devtools).  Enabling `devTools` adds support for the browser extension.  This is similar to the `React Dev Tools` that are available for development and production builds.  _However_ the Redux `devTools` allow you to reset the entire Redux state - even in production.  This can do a number on the UI (I just did it in the middle of a Merge Duplicates session). 
___
*[`src/components/GoalTimeline/Redux/GoalActions.ts` line 19 at r19](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbutfDi3XBK-6uR2vg5:-NbynT_VAWoytn7o17Of:b-5yqq56) ([raw file](https://github.com/sillsdev/TheCombine/blob/233e882a62c467294000168b69cefd16a8b74985/src/components/GoalTimeline/Redux/GoalActions.ts#L19)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Since ` dispatchMergeStepData` and `fetchMergeDupsData` are both exported from `goals/MergeDuplicates/Redux/MergeDupsActions.ts` and only used here, perhaps their definitions should be moved here.
</blockquote></details>

However, the data they operate on are more tightly associated with the MergeDups actions so I am in favor of leaving them here - at least for now.  Perhaps when I port the MergeDups actions, I will change my mind.
___
*[`src/components/GoalTimeline/Redux/GoalActions.ts` line 44 at r19](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nbv0SpWBsdmuLWIyejs:-NbyoLfa7keuhQgCOFaC:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/233e882a62c467294000168b69cefd16a8b74985/src/components/GoalTimeline/Redux/GoalActions.ts#L44)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`return setCurrentGoalAction(goal ? { ...goal } : new Goal());`
</blockquote></details>

Done.
___
*[`src/goals/CharacterInventory/Redux/CharacterInventoryActions.ts` line 137 at r19](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbuzNqy42zzGbc8kM64:-NbypIuxBnciXaxkoSc9:budqyom) ([raw file](https://github.com/sillsdev/TheCombine/blob/233e882a62c467294000168b69cefd16a8b74985/src/goals/CharacterInventory/Redux/CharacterInventoryActions.ts#L137)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Since the analogous `.changes` update for `MergeDups` was incorporated into the `goalSlice`, this probably should be too.
</blockquote></details>

Actually, I think the MergeDups change should be moved out of the general goal actions and into the more specific MergeDups actions.  Any objections?
___
*[`src/utilities/test-utils.tsx` line 19 at r19](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbuwHpi8tGf1MDB99yo:-Nbypq2vAlD9leAVoJGy:brhumzt) ([raw file](https://github.com/sillsdev/TheCombine/blob/233e882a62c467294000168b69cefd16a8b74985/src/utilities/test-utils.tsx#L19)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

It'd be nice to have a return type on this function, but I have no idea what that would be. :)
</blockquote></details>

Same here.


<!-- Sent from Reviewable.io -->

2023-08-16 15:13 UTC, imnasnainaec reviewed
> Reviewed 1 of 11 files at r11, 1 of 4 files at r20.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 107 of 114 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 19 at r20](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nbyu2tj-lazH0W91Qnv:-Nbyu2tj-lazH0W91Qnw:bayyeji) ([raw file](https://github.com/sillsdev/TheCombine/blob/3999043d77078e08811d50ca7105adc5bbf649de/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L19)):*
> ```XML
>   CharacterChange,
>   CharacterStatus,
>   // CharInvChanges,
> ```

Remove commented import
___
*[`src/goals/CharacterInventory/Redux/CharacterInventoryActions.ts` line 137 at r19](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbuzNqy42zzGbc8kM64:-NbytgS860DHecWtAkWO:b-oewjzq) ([raw file](https://github.com/sillsdev/TheCombine/blob/233e882a62c467294000168b69cefd16a8b74985/src/goals/CharacterInventory/Redux/CharacterInventoryActions.ts#L137)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Actually, I think the MergeDups change should be moved out of the general goal actions and into the more specific MergeDups actions.  Any objections?
</blockquote></details>

No objections.


<!-- Sent from Reviewable.io -->

2023-08-16 15:57 UTC, imnasnainaec reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 107 of 114 files reviewed, 4 unresolved discussions (waiting on @jmgrady)

___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 87 at r20](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nbz1Lsl1tW50ujBKbvz:-Nbz1Lsl1tW50ujBKbw-:b-rytnb5) ([raw file](https://github.com/sillsdev/TheCombine/blob/3999043d77078e08811d50ca7105adc5bbf649de/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L87)):*
> ```XML
>   childIds: ["3", "4"],
> };
> const mockCharInvChanges: CharacterChange[] = [
> ```

`mockCharInvChanges` is unused
___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 128 at r20](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nbz12wYDqaKBLRuYxZ-:-Nbz12wYDqaKBLRuYxZ0:bhg7c65) ([raw file](https://github.com/sillsdev/TheCombine/blob/3999043d77078e08811d50ca7105adc5bbf649de/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L128)):*
> ```XML
>     // Expect 1 button for each of the Goal Types + one for the
>     // "No History" element in the history list.
>     expect(goalButtonList.length).toBe(4);
> ```

`expect(goalButtonList).toHaveLength(4);`
___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 153 at r20](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nbz2Fso33hjxdCLSrFw:-Nbz2Fso33hjxdCLSrFx:bhzmby5) ([raw file](https://github.com/sillsdev/TheCombine/blob/3999043d77078e08811d50ca7105adc5bbf649de/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L153)):*
> ```XML
>     const convertGoalToEditSpy = jest.spyOn(goalUtilities, "convertEditToGoal");
>     LocalStorage.setCurrentUser(mockUser);
>     LocalStorage.setProjectId(mockProjectId);
> ```

Some tests have `LocalStorage.setProjectId(mockProjectId);` and others have `LocalStorage.setProjectId("123");` (even though `mockProjectId = 123`). Perhaps there should be a single function to setupLocalStorage and/or have that setup inside `beforeEach` (to be deleted/changed at the start of any specific test that needs something different).


<!-- Sent from Reviewable.io -->

2023-08-16 17:10 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 107 of 114 files reviewed, all discussions resolved (waiting on @imnasnainaec and @jmgrady)

___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 19 at r20](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nbyu2tj-lazH0W91Qnv:-NbzIUzF2-f2E3RDccYy:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/3999043d77078e08811d50ca7105adc5bbf649de/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L19)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Remove commented import
</blockquote></details>

Done.
___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 87 at r20](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nbz1Lsl1tW50ujBKbvz:-NbzIWoq0m3HUvzAaL1m:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/3999043d77078e08811d50ca7105adc5bbf649de/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L87)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`mockCharInvChanges` is unused
</blockquote></details>

Done.
___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 128 at r20](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nbz12wYDqaKBLRuYxZ-:-NbzITBiBaxAR1rmOSs2:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/3999043d77078e08811d50ca7105adc5bbf649de/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L128)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`expect(goalButtonList).toHaveLength(4);`
</blockquote></details>

Done.
___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 153 at r20](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nbz2Fso33hjxdCLSrFw:-NbzJMS8-W2EViyBNCGg:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/3999043d77078e08811d50ca7105adc5bbf649de/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L153)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Some tests have `LocalStorage.setProjectId(mockProjectId);` and others have `LocalStorage.setProjectId("123");` (even though `mockProjectId = 123`). Perhaps there should be a single function to setupLocalStorage and/or have that setup inside `beforeEach` (to be deleted/changed at the start of any specific test that needs something different).
</blockquote></details>

Done.
___
*[`src/goals/CharacterInventory/Redux/CharacterInventoryActions.ts` line 137 at r19](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbuzNqy42zzGbc8kM64:-NbzJQoNBvOseBn5ovSB:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/233e882a62c467294000168b69cefd16a8b74985/src/goals/CharacterInventory/Redux/CharacterInventoryActions.ts#L137)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

No objections.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-16 17:39 UTC, imnasnainaec reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 107 of 114 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

*[a discussion](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbtQfGL7g8Ncu4K1FWd:-NbzPXTl6UTkPlT4Cl1c:b-8rz7l3) (no related file):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Non-empty `package-lock.json` diff still/again. And the frontend licenses need to be reverted too.

___
___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 128 at r20](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nbz12wYDqaKBLRuYxZ-:-NbzPtVf9F3DVGm5AQM0:bknvoaz) ([raw file](https://github.com/sillsdev/TheCombine/blob/3999043d77078e08811d50ca7105adc5bbf649de/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L128)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

And elsewhere in this test file.
___
*[`src/goals/MergeDuplicates/Redux/MergeDupsActions.ts` line 268 at r21](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbzQOFODEAX_zEGNSwW:-NbzQOFODEAX_zEGNSwX:bkvuv60) ([raw file](https://github.com/sillsdev/TheCombine/blob/f2942f18e9e09d8babe29e6e870564acf7de53e9/src/goals/MergeDuplicates/Redux/MergeDupsActions.ts#L268)):*
> ```XML
>       const completedMerge = { childIds, parentIds };
>       if (getState().goalsState.currentGoal) {
>         //dispatch(addCompletedMergeToGoal(completedMerge));
> ```

Remove commented code.
___
*[`src/utilities/testUtilities.tsx` line 11 at r21](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbzQ9uX-ileW7g9lVx2:-NbzQ9uX-ileW7g9lVx3:b-xdgk9y) ([raw file](https://github.com/sillsdev/TheCombine/blob/f2942f18e9e09d8babe29e6e870564acf7de53e9/src/utilities/testUtilities.tsx#L11)):*
> ```XML
> import { persistor, setupStore } from "store";
> import type { AppStore, RootState } from "store";
> ```

Can the source of this file be added as a comment?


<!-- Sent from Reviewable.io -->

2023-08-16 17:40 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 107 of 114 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec)

___
*[`src/goals/CharacterInventory/Redux/CharacterInventoryActions.ts` line 137 at r19](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbuzNqy42zzGbc8kM64:-NbzPFqm20kUQxc-XkbH:boiwjml) ([raw file](https://github.com/sillsdev/TheCombine/blob/233e882a62c467294000168b69cefd16a8b74985/src/goals/CharacterInventory/Redux/CharacterInventoryActions.ts#L137)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I implemented the change I suggested and it is even uglier than I imagined.  I think that it will be better to do as you suggest and have an action for each goal type for adding its data to the current goal.  It all comes down to not mutating the state directly.


<!-- Sent from Reviewable.io -->

2023-08-16 17:44 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 107 of 114 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec)

___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 128 at r20](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nbz12wYDqaKBLRuYxZ-:-NbzRX1q1IuTim7PsYwg:b1hn9n8) ([raw file](https://github.com/sillsdev/TheCombine/blob/3999043d77078e08811d50ca7105adc5bbf649de/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L128)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

And elsewhere in this test file.
</blockquote></details>

Done.
(I meant to do that.) :-(


<!-- Sent from Reviewable.io -->

2023-08-16 18:59 UTC, imnasnainaec requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 107 of 114 files reviewed, 3 unresolved discussions (waiting on @jmgrady)



<!-- Sent from Reviewable.io -->

2023-08-16 19:21 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 106 of 114 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

*[a discussion](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbtQfGL7g8Ncu4K1FWd:-Nbzmh7_Esa3ABpTfL-j:b-896fix) (no related file):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Non-empty `package-lock.json` diff still/again. And the frontend licenses need to be reverted too.
</blockquote></details>

Done.

___
___
*[`src/goals/MergeDuplicates/Redux/MergeDupsActions.ts` line 268 at r21](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbzQOFODEAX_zEGNSwW:-NbzlPmQ01Ck_EyLODQs:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/f2942f18e9e09d8babe29e6e870564acf7de53e9/src/goals/MergeDuplicates/Redux/MergeDupsActions.ts#L268)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Remove commented code.
</blockquote></details>

Done.
___
*[`src/utilities/testUtilities.tsx` line 11 at r21](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-NbzQ9uX-ileW7g9lVx2:-NbzlkJr30Ppp79AN4cy:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/f2942f18e9e09d8babe29e6e870564acf7de53e9/src/utilities/testUtilities.tsx#L11)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Can the source of this file be added as a comment?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-16 21:12 UTC, imnasnainaec reviewed
> Reviewed 5 of 8 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 111 of 114 files reviewed, 4 unresolved discussions (waiting on @jmgrady)

___
*[`src/components/GoalTimeline/Redux/GoalActions.ts` line 28 at r23](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc-7Nn23lQcwkudDkdO:-Nc-7Nn23lQcwkudDkdP:bez1ztq) ([raw file](https://github.com/sillsdev/TheCombine/blob/9185a2064a77e826a0876f9eed45d68a6a40200c/src/components/GoalTimeline/Redux/GoalActions.ts#L28)):*
> ```XML
> import { convertEditToGoal } from "utilities/goalUtilities";
> 
> // Action Creators
> ```

There is sometimes an extra newline between consecutive action creators and sometimes not. These two roads diverged in a wood, and you...
___
*[`src/components/GoalTimeline/Redux/GoalReducer.ts` line 51 at r23](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc-94s66X984TGeRadW:-Nc-94s66X984TGeRadX:b-8nwdrw) ([raw file](https://github.com/sillsdev/TheCombine/blob/9185a2064a77e826a0876f9eed45d68a6a40200c/src/components/GoalTimeline/Redux/GoalReducer.ts#L51)):*
> ```XML
>           : state.previousGoalType;
>     },
>     setCurrentGoalsStateAction: (state, action) => {
> ```

`setCurrentGoalsStateAction` -> ` setGoalStatusAction` or `setCurrentGoalStatusAction`
___
*[`src/components/GoalTimeline/Redux/GoalReducer.ts` line 77 at r23](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc-AgzfBve5VFW7QoUg:-Nc-AgzfBve5VFW7QoUh:b-7k2zte) ([raw file](https://github.com/sillsdev/TheCombine/blob/9185a2064a77e826a0876f9eed45d68a6a40200c/src/components/GoalTimeline/Redux/GoalReducer.ts#L77)):*
> ```XML
> export const {
>   addCharInvChangesAction,
>   addCompletedMergeToGoalAction,
> ```

`addCharInvChangesToGoalAction,  addCompletedMergeToGoalAction,`
or
`addCharInvChangesAction, addCompletedMergeAction,`
___
*[`src/components/GoalTimeline/Redux/GoalReducer.ts` line 84 at r23](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc-A_gI8yZrl8j6iUtE:-Nc-A_gI8yZrl8j6iUtF:b-89i15y) ([raw file](https://github.com/sillsdev/TheCombine/blob/9185a2064a77e826a0876f9eed45d68a6a40200c/src/components/GoalTimeline/Redux/GoalReducer.ts#L84)):*
> ```XML
>   setGoalDataAction,
>   updateStepFromDataAction,
> } = goalSlice.actions;
> ```

Some of the names of actions that act on the current goal have "Current" and some don't.  These two roads...


<!-- Sent from Reviewable.io -->

2023-08-16 21:23 UTC, imnasnainaec reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 111 of 114 files reviewed, 6 unresolved discussions (waiting on @jmgrady)

___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 246 at r23](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc-CoOkEHFghuZE9SMs:-Nc-CoOkEHFghuZE9SMt:b-vje11q) ([raw file](https://github.com/sillsdev/TheCombine/blob/9185a2064a77e826a0876f9eed45d68a6a40200c/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L246)):*
> ```XML
>     // iterate over all but the last step
>     const numSteps = currentGoal.numSteps;
>     for (var i = 0; i < numSteps - 1; i++) {
> ```

`for (let i`
___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 322 at r23](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc-DIzrCuvVh_VFl9bU:-Nc-DIzrCuvVh_VFl9bV:bihh7c5) ([raw file](https://github.com/sillsdev/TheCombine/blob/9185a2064a77e826a0876f9eed45d68a6a40200c/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L322)):*
> ```XML
>       store.dispatch(asyncAddGoal(goal));
>     });
>     //   - dispatch asyncUpdateGoal()
> ```

The "   - " in this comment before the "dispatch" leads me to look for a "  verify:" that's not to be found in this test.
(Same of one of the comments in the previous test.)


<!-- Sent from Reviewable.io -->

2023-08-16 22:45 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 111 of 114 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[`src/components/GoalTimeline/Redux/GoalActions.ts` line 28 at r23](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc-7Nn23lQcwkudDkdO:-Nc-QKuT3hT_m-kBjpBs:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/9185a2064a77e826a0876f9eed45d68a6a40200c/src/components/GoalTimeline/Redux/GoalActions.ts#L28)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

There is sometimes an extra newline between consecutive action creators and sometimes not. These two roads diverged in a wood, and you...
</blockquote></details>

Done.
___
*[`src/components/GoalTimeline/Redux/GoalReducer.ts` line 51 at r23](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc-94s66X984TGeRadW:-Nc-QzOB4iFBeX-Inra4:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/9185a2064a77e826a0876f9eed45d68a6a40200c/src/components/GoalTimeline/Redux/GoalReducer.ts#L51)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`setCurrentGoalsStateAction` -> ` setGoalStatusAction` or `setCurrentGoalStatusAction`
</blockquote></details>

Done.
___
*[`src/components/GoalTimeline/Redux/GoalReducer.ts` line 77 at r23](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc-AgzfBve5VFW7QoUg:-Nc-TV2qA0miYRizRRiJ:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/9185a2064a77e826a0876f9eed45d68a6a40200c/src/components/GoalTimeline/Redux/GoalReducer.ts#L77)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`addCharInvChangesToGoalAction,  addCompletedMergeToGoalAction,`
or
`addCharInvChangesAction, addCompletedMergeAction,`
</blockquote></details>

Done.
___
*[`src/components/GoalTimeline/Redux/GoalReducer.ts` line 84 at r23](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc-A_gI8yZrl8j6iUtE:-Nc-VdaO-YsVSIhOK7zv:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/9185a2064a77e826a0876f9eed45d68a6a40200c/src/components/GoalTimeline/Redux/GoalReducer.ts#L84)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Some of the names of actions that act on the current goal have "Current" and some don't.  These two roads...
</blockquote></details>

Done.
___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 246 at r23](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc-CoOkEHFghuZE9SMs:-Nc-TxhHELH8fr_zWMhE:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/9185a2064a77e826a0876f9eed45d68a6a40200c/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L246)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`for (let i`
</blockquote></details>

Done.
___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 322 at r23](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc-DIzrCuvVh_VFl9bU:-Nc-UZih1-4wGLe5VCnn:br8im7b) ([raw file](https://github.com/sillsdev/TheCombine/blob/9185a2064a77e826a0876f9eed45d68a6a40200c/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L322)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

The "   - " in this comment before the "dispatch" leads me to look for a "  verify:" that's not to be found in this test.
(Same of one of the comments in the previous test.)
</blockquote></details>

Done.
'-' was removed.


<!-- Sent from Reviewable.io -->

2023-08-17 12:40 UTC, imnasnainaec reviewed
> Reviewed 2 of 5 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 111 of 114 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

___
*[`src/components/GoalTimeline/Redux/GoalActions.ts` line 34 at r24](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc2UbuH86tHha7jgBUK:-Nc2UbuH86tHha7jgBUL:b-iq0m5x) ([raw file](https://github.com/sillsdev/TheCombine/blob/5793437a0a948692b6158d2d949ce6fc3031a65c/src/components/GoalTimeline/Redux/GoalActions.ts#L34)):*
> ```XML
>   return addCharInvChangesToGoalAction(charChanges);
> }
> export function addCompletedMergeToGoal(changes: MergeUndoIds): PayloadAction {
> ```

extra newline between `addCharInvChangesToGoal` and `addCompletedMergeToGoal`
___
*[`src/components/GoalTimeline/Redux/GoalActions.ts` line 50 at r24](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc2USj-38jwW2WoEda-:-Nc2USj0AeGnd8gaMw8I:busvd23) ([raw file](https://github.com/sillsdev/TheCombine/blob/5793437a0a948692b6158d2d949ce6fc3031a65c/src/components/GoalTimeline/Redux/GoalActions.ts#L50)):*
> ```XML
> }
> 
> export function setCurrentGoalStatus(status: GoalStatus): PayloadAction {
> ```

This "Current" in `setCurrentGoalStatus` should be removed to match `setGoalStatusAction`, and moved below `setGoalData` to maintain alphabeticity.
___
*[`src/components/GoalTimeline/Redux/GoalReducer.ts` line 84 at r23](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc-A_gI8yZrl8j6iUtE:-Nc2UswB3kAufIOaKQlO:b-ef7i7w) ([raw file](https://github.com/sillsdev/TheCombine/blob/9185a2064a77e826a0876f9eed45d68a6a40200c/src/components/GoalTimeline/Redux/GoalReducer.ts#L84)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Now `  setGoalStatusAction` and  `setGoalDataAction` are un-alphabetical.
`
___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 322 at r23](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc-DIzrCuvVh_VFl9bU:-Nc2VIpB8C-m5KwZFMUs:b3yd7lj) ([raw file](https://github.com/sillsdev/TheCombine/blob/9185a2064a77e826a0876f9eed45d68a6a40200c/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L322)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Done.
'-' was removed.
</blockquote></details>

also the one 20 lines above


<!-- Sent from Reviewable.io -->

2023-08-17 13:14 UTC, imnasnainaec reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 111 of 114 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`src/components/GoalTimeline/Redux/GoalReducer.ts` line 84 at r23](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc-A_gI8yZrl8j6iUtE:-Nc2c30jBm7DEfZSvGxj:bx1gnit) ([raw file](https://github.com/sillsdev/TheCombine/blob/9185a2064a77e826a0876f9eed45d68a6a40200c/src/components/GoalTimeline/Redux/GoalReducer.ts#L84)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

still here and in the `GoalActions.ts` imports.
___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 19 at r25](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc2cRGGDTgFmC0Nw8N6:-Nc2cRGGDTgFmC0Nw8N7:b-fnuco2) ([raw file](https://github.com/sillsdev/TheCombine/blob/17de9eb219e049722b0ae1c648d33a46f9eab8c6/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L19)):*
> ```XML
> import {
>   CharacterStatus,
>   CharacterChange,
> ```

`CharacterStatus,` <-> `CharacterChange,`


<!-- Sent from Reviewable.io -->

2023-08-17 13:40 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 111 of 114 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[`src/components/GoalTimeline/Redux/GoalReducer.ts` line 84 at r23](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc-A_gI8yZrl8j6iUtE:-Nc2hkgv8eBYZpdBa_k_:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/9185a2064a77e826a0876f9eed45d68a6a40200c/src/components/GoalTimeline/Redux/GoalReducer.ts#L84)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

still here and in the `GoalActions.ts` imports.
</blockquote></details>

Done.
___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 19 at r25](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc2cRGGDTgFmC0Nw8N6:-Nc2iLt203ZgczAq8ds4:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/17de9eb219e049722b0ae1c648d33a46f9eab8c6/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L19)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`CharacterStatus,` <-> `CharacterChange,`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-17 18:57 UTC, imnasnainaec reviewed
> Reviewed 1 of 3 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 112 of 114 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`src/goals/MergeDuplicates/Redux/MergeDupsActions.ts` line 286 at r26](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc3q_up5IYmKnHSlxY2:-Nc3q_up5IYmKnHSlxY3:b5ogncx) ([raw file](https://github.com/sillsdev/TheCombine/blob/c7d99baa1bc47c94dffa4d20c6381437032d73cc/src/goals/MergeDuplicates/Redux/MergeDupsActions.ts#L286)):*
> ```XML
> 
> export async function fetchMergeDupsData(
>   goalType: GoalType
> ```

It feels a bit odd to have `goalType` the argument for a merge-specific function. How about instead having the argument be `numSteps` and then `maxNumSteps` can be imported and used in `GoalActions` instead of here.


<!-- Sent from Reviewable.io -->

2023-08-17 19:04 UTC, imnasnainaec reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 112 of 114 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 51 at r26](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc3rq5XE6PduHVdFgwr:-Nc3rq5XE6PduHVdFgws:b-az455e) ([raw file](https://github.com/sillsdev/TheCombine/blob/c7d99baa1bc47c94dffa4d20c6381437032d73cc/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L51)):*
> ```XML
>   getUser: (id: string) => mockGetUser(id),
>   getUserEditById: (id: string, index: string) =>
>     mockGetUserEditById(id, index),
> ```

```
  addGoalToUserEdit: (...args: any[]) => mockAddGoalToUserEdit(...args),
  addStepToGoal: (...args: any[]) => mockAddStepToGoal(...args),
...
  getUserEditById: (...args: any[]) => mockGetUserEditById(...args),
```
... saves a few lines, lightens maintenance, and removed the need to import `Goal`.


<!-- Sent from Reviewable.io -->

2023-08-17 19:20 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 112 of 114 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 51 at r26](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc3rq5XE6PduHVdFgwr:-Nc3u2JKB9X14EklBu8j:bxsj8yp) ([raw file](https://github.com/sillsdev/TheCombine/blob/c7d99baa1bc47c94dffa4d20c6381437032d73cc/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L51)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

```
  addGoalToUserEdit: (...args: any[]) => mockAddGoalToUserEdit(...args),
  addStepToGoal: (...args: any[]) => mockAddStepToGoal(...args),
...
  getUserEditById: (...args: any[]) => mockGetUserEditById(...args),
```
... saves a few lines, lightens maintenance, and removed the need to import `Goal`.
</blockquote></details>

Done.
Nice!
___
*[`src/goals/MergeDuplicates/Redux/MergeDupsActions.ts` line 286 at r26](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc3q_up5IYmKnHSlxY2:-Nc3vGvm1j0EDkNBwPgU:b-yn04z3) ([raw file](https://github.com/sillsdev/TheCombine/blob/c7d99baa1bc47c94dffa4d20c6381437032d73cc/src/goals/MergeDuplicates/Redux/MergeDupsActions.ts#L286)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

It feels a bit odd to have `goalType` the argument for a merge-specific function. How about instead having the argument be `numSteps` and then `maxNumSteps` can be imported and used in `GoalActions` instead of here.
</blockquote></details>

Done.
Good suggestion.
It also seems odd to call a function with some arguments which then calls another function with the same arguments (and in the same order).  That said, I think it is warranted because then the general Goal actions don't have any knowledge about the nature of the goal data. 


<!-- Sent from Reviewable.io -->

2023-08-17 20:46 UTC, imnasnainaec reviewed
> Reviewed 2 of 3 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 113 of 114 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 157 at r27](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc4EtVA81qnSUkcRTw9:-Nc4EtVA81qnSUkcRTwA:bne6gtt) ([raw file](https://github.com/sillsdev/TheCombine/blob/67731f828b777508286e13e2edf85892165cb9a9/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L157)):*
> ```XML
>     expect(convertGoalToEditSpy).toBeCalledTimes(1);
>   });
>   it("backend returns no user edits", async () => {
> ```

extra newline before this test for readability


<!-- Sent from Reviewable.io -->

2023-08-18 12:53 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 113 of 114 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 157 at r27](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc4EtVA81qnSUkcRTw9:-Nc7hJ3s6hWHr-oa9YPz:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/67731f828b777508286e13e2edf85892165cb9a9/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L157)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

extra newline before this test for readability
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-18 13:22 UTC, imnasnainaec reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 113 of 114 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 40 at r28](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc7myUMC55CHTlpW3XA:-Nc7myUMC55CHTlpW3XB:brakj83) ([raw file](https://github.com/sillsdev/TheCombine/blob/af67898a209eae1b2dc81ff1a2deeabfeca3929d/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L40)):*
> ```XML
>   addGoalToUserEdit: (...args: any[]) => mockAddGoalToUserEdit(...args),
>   addStepToGoal: (...args: any[]) => mockAddStepToGoal(...args),
>   createUserEdit: () => mockCreateUserEdit(),
> ```

`backend.createUserEdit` is mocked, but not yet used in these tests. Could we add a test for `asyncCreateUserEdits`? There are also no tests for `asyncLoadExistingUserEdits` or `asyncLoadNewGoal`.
___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 121 at r28](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc7mDoz8lQuJR-skIp7:-Nc7mDoz8lQuJR-skIp8:b-ejuzpx) ([raw file](https://github.com/sillsdev/TheCombine/blob/af67898a209eae1b2dc81ff1a2deeabfeca3929d/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L121)):*
> ```XML
> 
> describe("GoalTimeline", () => {
>   it("renders Goal screen", async () => {
> ```

This first test seems out of place, redundant with the first test in the GoalTimeline's test file. Is it just to guarantee the render method assumed in the rests of the tests in this document?
___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 133 at r28](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc7lNsvCTw5bgVKPgoi:-Nc7lNsvCTw5bgVKPgoj:bmmh8gf) ([raw file](https://github.com/sillsdev/TheCombine/blob/af67898a209eae1b2dc81ff1a2deeabfeca3929d/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L133)):*
> ```XML
> });
> 
> describe("Set empty goal", () => {
> ```

I think `describe("setCurrentGoal", ...` would be more inline with the general pattern of `describe` describing a function or component being tested.


<!-- Sent from Reviewable.io -->

2023-08-18 14:59 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 113 of 114 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 40 at r28](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc7myUMC55CHTlpW3XA:-Nc8-JftEjMYetVCVIzu:bxc414f) ([raw file](https://github.com/sillsdev/TheCombine/blob/af67898a209eae1b2dc81ff1a2deeabfeca3929d/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L40)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`backend.createUserEdit` is mocked, but not yet used in these tests. Could we add a test for `asyncCreateUserEdits`? There are also no tests for `asyncLoadExistingUserEdits` or `asyncLoadNewGoal`.
</blockquote></details>

Done.
`asyncLoadExistingUserEdits`, and `asyncLoadNewGoal` are already tested as part of "update MergeDups goal".
`asyncCreateUserEdits` is now tested with new test, `creates new user edits`.
___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 121 at r28](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc7mDoz8lQuJR-skIp7:-Nc87vMY-fSDrLfp6x5X:bjmvl4a) ([raw file](https://github.com/sillsdev/TheCombine/blob/af67898a209eae1b2dc81ff1a2deeabfeca3929d/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L121)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

This first test seems out of place, redundant with the first test in the GoalTimeline's test file. Is it just to guarantee the render method assumed in the rests of the tests in this document?
</blockquote></details>

Done.
I agree.  Removed.
___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 133 at r28](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc7lNsvCTw5bgVKPgoi:-Nc88Cvp20ek4KDVQmWx:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/af67898a209eae1b2dc81ff1a2deeabfeca3929d/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L133)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I think `describe("setCurrentGoal", ...` would be more inline with the general pattern of `describe` describing a function or component being tested.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-18 15:37 UTC, imnasnainaec reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 113 of 114 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 40 at r28](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc7myUMC55CHTlpW3XA:-Nc8Hj9A2q4UNnDd2CoZ:b-kpie15) ([raw file](https://github.com/sillsdev/TheCombine/blob/af67898a209eae1b2dc81ff1a2deeabfeca3929d/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L40)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Done.
`asyncLoadExistingUserEdits`, and `asyncLoadNewGoal` are already tested as part of "update MergeDups goal".
`asyncCreateUserEdits` is now tested with new test, `creates new user edits`.
</blockquote></details>

I don't understand the new test. It has the same `expect` statements at the test before it and doesn't check that `mockCreateUserEdit` was called.


<!-- Sent from Reviewable.io -->

2023-08-18 16:12 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: 113 of 114 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[`src/components/GoalTimeline/tests/GoalRedux.test.tsx` line 40 at r28](https://reviewable.io/reviews/sillsdev/TheCombine/2465#-Nc7myUMC55CHTlpW3XA:-Nc8M1YW-hfUmEDxY3S9:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/af67898a209eae1b2dc81ff1a2deeabfeca3929d/src/components/GoalTimeline/tests/GoalRedux.test.tsx#L40)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I don't understand the new test. It has the same `expect` statements at the test before it and doesn't check that `mockCreateUserEdit` was called.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-18 16:32 UTC, imnasnainaec approved these changes
> Reviewed 1 of 1 files at r30, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2465)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)



<!-- Sent from Reviewable.io -->

2023-08-18 17:18 UTC, merged