Port MergeDups goal to use redux-toolkit
sillsdev/TheCombine pull request #2704
Opened 2023-10-09 13:48 UTC by jmgrady

2023-10-31 15:33 UTC, imnasnainaec reviewed
> Reviewed 94 of 100 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2704)* status: 94 of 102 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx` line 312 at r6](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-Ni5M_Ib3EMOJmkQq3ft:-Ni5M_Ib3EMOJmkQq3fu:b-sarb33) ([raw file](https://github.com/sillsdev/TheCombine/blob/103edc97e35da3baa963bd74034c9e4ae437a904/src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx#L312)):*
> ```XML
>     });
>   });
>   // describe("mergeDefinitionIntoSense", () => {
> ```

There are a bunch of commented-out tests here.


<!-- Sent from Reviewable.io -->

2023-10-31 16:16 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2704)* status: 94 of 102 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[`src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx` line 312 at r6](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-Ni5M_Ib3EMOJmkQq3ft:-Ni5UpZo0XjZyDp4gvgi:b-y7guhj) ([raw file](https://github.com/sillsdev/TheCombine/blob/103edc97e35da3baa963bd74034c9e4ae437a904/src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx#L312)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

There are a bunch of commented-out tests here.
</blockquote></details>

Done.

I have removed these tests since the functionality they test has been moved to `MergeDupsReducer.ts`.  I have also created Issue #2571 to remove the `definitions` field in `Senses` or add tests to `MergeDupsReducer.test.tsx` to test the same logic that these tests were designed to test.


<!-- Sent from Reviewable.io -->

2023-10-31 19:07 UTC, imnasnainaec reviewed
> Reviewed 2 of 6 files at r1, 1 of 100 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2704)* status: 97 of 102 files reviewed, 6 unresolved discussions (waiting on @jmgrady)

___
*[`src/goals/MergeDuplicates/Redux/MergeDupsActions.ts` line 21 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-Ni67BUu0twqpk9gPIHJ:-Ni67BUu0twqpk9gPIHK:b-yf7lol) ([raw file](https://github.com/sillsdev/TheCombine/blob/1a500fac516b19f9ea8d72d08059430b7aa02153/src/goals/MergeDuplicates/Redux/MergeDupsActions.ts#L21)):*
> ```XML
> import {
>   clearTreeAction,
>   clearMergeWordsAction,
> ```

If we switch `clearTreeAction` and `clearMergeWordsAction`, the imports will be in alphabetical order.
___
*[`src/goals/MergeDuplicates/Redux/MergeDupsActions.ts` line 46 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-Ni63jp54yrGcs-jDW_n:-Ni63jp54yrGcs-jDW_o:bkffgy9) ([raw file](https://github.com/sillsdev/TheCombine/blob/1a500fac516b19f9ea8d72d08059430b7aa02153/src/goals/MergeDuplicates/Redux/MergeDupsActions.ts#L46)):*
> ```XML
> // Action Creation Functions
> 
> export function clearTree(): Action {
> ```

If we switch `clearTree` and `clearMergeWords`, the action creation functions will be in alphabetical order.
___
*[`src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts` line 28 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-Ni64dYQAvRKVzSqHP85:-Ni64dYQAvRKVzSqHP86:bcr57u1) ([raw file](https://github.com/sillsdev/TheCombine/blob/1a500fac516b19f9ea8d72d08059430b7aa02153/src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts#L28)):*
> ```XML
> 
> const mergeDupStepSlice = createSlice({
>   name: "mergeDupStepReducer",
> ```

Using "Step" in the naming here makes sense, since this part of the Redux state is for the `MergeDuplicates/MergeDupsStep/` component. To be consistent with this naming and usage, perhaps the `MergeDuplicates/Redux/` folder  (as well as the file `MergeDuplicates/MergeDupsTreeTypes.ts`) should be moved into `MergeDuplicates/MergeDupsStep/`.
___
*[`src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts` line 34 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-Ni644MqCS-61hKEpJVu:-Ni644MqCS-61hKEpJVv:b8wmvfs) ([raw file](https://github.com/sillsdev/TheCombine/blob/1a500fac516b19f9ea8d72d08059430b7aa02153/src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts#L34)):*
> ```XML
>       return defaultState;
>     },
>     clearMergeWordsAction: (state) => {
> ```

If we switch `clearTreeAction` and `clearMergeWordsAction`, the reducers will be in alphabetical order.
___
*[`src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts` line 422 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-Ni64B7A2092rK3E4vz2:-Ni64B7A2092rK3E4vz3:b-bexwfq) ([raw file](https://github.com/sillsdev/TheCombine/blob/1a500fac516b19f9ea8d72d08059430b7aa02153/src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts#L422)):*
> ```XML
> export const {
>   clearTreeAction,
>   clearMergeWordsAction,
> ```

If we switch `clearTreeAction` and `clearMergeWordsAction`, the exports will be in alphabetical order.
___
*[`src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx` line 105 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-Ni66eVuEhs7Coh4SmwD:-Ni66eVuEhs7Coh4SmwE:b-4h5quw) ([raw file](https://github.com/sillsdev/TheCombine/blob/1a500fac516b19f9ea8d72d08059430b7aa02153/src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx#L105)):*
> ```XML
>         mergeDuplicateGoal: { data, tree, mergeWords },
>       });
>       await store.dispatch<any>(mergeAll());
> ```

A wise man once told me that these `<any>`s are no longer necessary.


<!-- Sent from Reviewable.io -->

2023-11-01 12:39 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2704)* status: 97 of 102 files reviewed, 2 unresolved discussions (waiting on @imnasnainaec and @jmgrady)

___
*[`src/goals/MergeDuplicates/Redux/MergeDupsActions.ts` line 21 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-Ni67BUu0twqpk9gPIHJ:-Ni9bnNmBxBahmIDv3Tr:bb6un1j) ([raw file](https://github.com/sillsdev/TheCombine/blob/1a500fac516b19f9ea8d72d08059430b7aa02153/src/goals/MergeDuplicates/Redux/MergeDupsActions.ts#L21)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

If we switch `clearTreeAction` and `clearMergeWordsAction`, the imports will be in alphabetical order.
</blockquote></details>

Done
___
*[`src/goals/MergeDuplicates/Redux/MergeDupsActions.ts` line 46 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-Ni63jp54yrGcs-jDW_n:-Ni9bpDh-wJ-v-F_F3-n:bb6un1j) ([raw file](https://github.com/sillsdev/TheCombine/blob/1a500fac516b19f9ea8d72d08059430b7aa02153/src/goals/MergeDuplicates/Redux/MergeDupsActions.ts#L46)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

If we switch `clearTree` and `clearMergeWords`, the action creation functions will be in alphabetical order.
</blockquote></details>

Done
___
*[`src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts` line 28 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-Ni64dYQAvRKVzSqHP85:-Ni9eJ_3BJ-yjeZiw1kW:b6p4us2) ([raw file](https://github.com/sillsdev/TheCombine/blob/1a500fac516b19f9ea8d72d08059430b7aa02153/src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts#L28)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Using "Step" in the naming here makes sense, since this part of the Redux state is for the `MergeDuplicates/MergeDupsStep/` component. To be consistent with this naming and usage, perhaps the `MergeDuplicates/Redux/` folder  (as well as the file `MergeDuplicates/MergeDupsTreeTypes.ts`) should be moved into `MergeDuplicates/MergeDupsStep/`.
</blockquote></details>

Actually, I don't really see the point of the MergeDupsStep folder.  I would prefer to move those components up a level in a separate PR - it is not really part of the scope of this change.  I prefer to change the name of the Redux state to `mergeDuplicatesSlice`.
___
*[`src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts` line 34 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-Ni644MqCS-61hKEpJVu:-Ni9f2m19SG3sxvfh8hB:bb6un1j) ([raw file](https://github.com/sillsdev/TheCombine/blob/1a500fac516b19f9ea8d72d08059430b7aa02153/src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts#L34)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

If we switch `clearTreeAction` and `clearMergeWordsAction`, the reducers will be in alphabetical order.
</blockquote></details>

Done
___
*[`src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts` line 422 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-Ni64B7A2092rK3E4vz2:-Ni9f4FN7jOyEYXcj7Cs:bb6un1j) ([raw file](https://github.com/sillsdev/TheCombine/blob/1a500fac516b19f9ea8d72d08059430b7aa02153/src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts#L422)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

If we switch `clearTreeAction` and `clearMergeWordsAction`, the exports will be in alphabetical order.
</blockquote></details>

Done
___
*[`src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx` line 105 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-Ni66eVuEhs7Coh4SmwD:-Ni9f82AE3Wnq8LMnFU-:bor8xst) ([raw file](https://github.com/sillsdev/TheCombine/blob/1a500fac516b19f9ea8d72d08059430b7aa02153/src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx#L105)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

A wise man once told me that these `<any>`s are no longer necessary.
</blockquote></details>

:-) Done.


<!-- Sent from Reviewable.io -->

2023-11-01 20:02 UTC, imnasnainaec reviewed
> Reviewed 1 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2704)* status: 97 of 102 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts` line 28 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-Ni64dYQAvRKVzSqHP85:-Ni9zVWl068TmvHjQonc:btw5bt0) ([raw file](https://github.com/sillsdev/TheCombine/blob/1a500fac516b19f9ea8d72d08059430b7aa02153/src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts#L28)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Actually, I don't really see the point of the MergeDupsStep folder.  I would prefer to move those components up a level in a separate PR - it is not really part of the scope of this change.  I prefer to change the name of the Redux state to `mergeDuplicatesSlice`.
</blockquote></details>

The name change sounds good.


<!-- Sent from Reviewable.io -->

2023-11-02 09:53 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2704)* status: 97 of 102 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[`src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts` line 28 at r7](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-Ni64dYQAvRKVzSqHP85:-NiERtcW-2G6DF--J-bz:bb6un1j) ([raw file](https://github.com/sillsdev/TheCombine/blob/1a500fac516b19f9ea8d72d08059430b7aa02153/src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts#L28)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

The name change sounds good.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-02 13:26 UTC, imnasnainaec reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2704)* status: 97 of 102 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

___
*[`src/goals/MergeDuplicates/Redux/MergeDupsActions.ts` line 118 at r11](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-NiFBMmgAuVlh2HnMo7I:-NiFBMmgAuVlh2HnMo7J:b-rs7k1) ([raw file](https://github.com/sillsdev/TheCombine/blob/70572c941e0cff9939865e7e25eab355dbf8a713/src/goals/MergeDuplicates/Redux/MergeDupsActions.ts#L118)):*
> ```XML
> 
>     const mergeWordsArray = [...getState().mergeDuplicateGoal.mergeWords];
>     dispatch(clearMergeWords());
> ```

Since the only use of `getMergeWords()` or of `mergeDuplicateGoal.mergeWords` is here where that content is then immediately cleared from state, wouldn't the content of the `getMergeWordsAction` reducer be better suited as helper functions at the foot of this file?
___
*[`src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts` line 239 at r11](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-NiFAgWCD8JwYLntpOx-:-NiFAgWCD8JwYLntpOx0:bso5pif) ([raw file](https://github.com/sillsdev/TheCombine/blob/70572c941e0cff9939865e7e25eab355dbf8a713/src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts#L239)):*
> ```XML
>       // const word: MergeTreeWord = JSON.parse(
>       //   JSON.stringify(state.tree.words[action.payload.wordId])
>       // );
> ```

remove/restore commented code


<!-- Sent from Reviewable.io -->

2023-11-02 14:21 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2704)* status: 97 of 102 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[`src/goals/MergeDuplicates/Redux/MergeDupsActions.ts` line 118 at r11](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-NiFBMmgAuVlh2HnMo7I:-NiFKh463Bjhc2X1bY8a:b-2pyrnq) ([raw file](https://github.com/sillsdev/TheCombine/blob/70572c941e0cff9939865e7e25eab355dbf8a713/src/goals/MergeDuplicates/Redux/MergeDupsActions.ts#L118)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Since the only use of `getMergeWords()` or of `mergeDuplicateGoal.mergeWords` is here where that content is then immediately cleared from state, wouldn't the content of the `getMergeWordsAction` reducer be better suited as helper functions at the foot of this file?
</blockquote></details>

I considered that but I felt it would be harder to manage.  The issue is that any function that modifies the state, e.g. `combineIntoFirstSense`, now becomes an action.  Once any such action has been dispatched, the function would then have to re-create all of the structures created up to that point because any or all of the references in the structure will have changed.  There are lots of these structures in the `getMergeWords` functionality: `possibleWords`, `nonDeletedSenses`, `deletedWords`, `mergeWordsArray` (the return value of `getMergeWords` is pushed to this structure) and so on.  I think it would be hard to maintain because it adds a lot of bloat and it would be easy to miss a structure that references an old object.
___
*[`src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts` line 239 at r11](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-NiFAgWCD8JwYLntpOx-:-NiFOBjPD7e5TbdqW4xH:bf87i1q) ([raw file](https://github.com/sillsdev/TheCombine/blob/70572c941e0cff9939865e7e25eab355dbf8a713/src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts#L239)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

remove/restore commented code
</blockquote></details>

Done. 
However, I am curious as to why the `JSON.parse(JSON.stringify(x))` was used in the first place.  Is there a benefit to doing this of which I am unaware?  It seems to just be adding a non-specific delay to me.


<!-- Sent from Reviewable.io -->

2023-11-02 14:45 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2704)* status: 97 of 102 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`src/goals/MergeDuplicates/Redux/MergeDupsActions.ts` line 118 at r11](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-NiFBMmgAuVlh2HnMo7I:-NiFUCaaAa3VuyfkRCJK:bminm34) ([raw file](https://github.com/sillsdev/TheCombine/blob/70572c941e0cff9939865e7e25eab355dbf8a713/src/goals/MergeDuplicates/Redux/MergeDupsActions.ts#L118)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

I considered that but I felt it would be harder to manage.  The issue is that any function that modifies the state, e.g. `combineIntoFirstSense`, now becomes an action.  Once any such action has been dispatched, the function would then have to re-create all of the structures created up to that point because any or all of the references in the structure will have changed.  There are lots of these structures in the `getMergeWords` functionality: `possibleWords`, `nonDeletedSenses`, `deletedWords`, `mergeWordsArray` (the return value of `getMergeWords` is pushed to this structure) and so on.  I think it would be hard to maintain because it adds a lot of bloat and it would be easy to miss a structure that references an old object.
</blockquote></details>

I may have been a little hasty in my last reply.  I had considered having `getMergeWords` as a separate function as originally written.  I had not considered calling it from within the reducer action.  If that is done, the other structures (`possibleWords`, `nonDeletedSenses`, &c.) would have references to `WritableDrafts` of the state which, when dereferenced, should return `base_` or `copy_` as appropriate.  I'll look into it.  Good suggestion!


<!-- Sent from Reviewable.io -->

2023-11-02 15:06 UTC, imnasnainaec reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2704)* status: 97 of 102 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

___
*[`src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts` line 239 at r11](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-NiFAgWCD8JwYLntpOx-:-NiFYqs9BxUki8d36a_U:by392kr) ([raw file](https://github.com/sillsdev/TheCombine/blob/70572c941e0cff9939865e7e25eab355dbf8a713/src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts#L239)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Done. 
However, I am curious as to why the `JSON.parse(JSON.stringify(x))` was used in the first place.  Is there a benefit to doing this of which I am unaware?  It seems to just be adding a non-specific delay to me.
</blockquote></details>

It was probably a way to make a deep copy to avoid modifying the state.
___
*[`src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx` line 245 at r12](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-NiFZCQm-UzDYTgFKQ7t:-NiFZCQm-UzDYTgFKQ7u:bmk5std) ([raw file](https://github.com/sillsdev/TheCombine/blob/a50f8ab085f896489fe95c4aadff1f42762a1511/src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx#L245)):*
> ```XML
> 
>       const store = setupStore();
>       await store.dispatch(dispatchMergeStepData(goal));
> ```

The `async` and `await` in this test are unnecessary, since `dispatchMergeStepData` is syncronous.


<!-- Sent from Reviewable.io -->

2023-11-02 16:31 UTC, imnasnainaec reviewed
> Reviewed 1 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2704)* status: 98 of 102 files reviewed, 2 unresolved discussions (waiting on @jmgrady)



<!-- Sent from Reviewable.io -->

2023-11-02 18:19 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2704)* status: 98 of 102 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[`src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx` line 245 at r12](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-NiFZCQm-UzDYTgFKQ7t:-NiGFXIY9zEo1Gp-t6mO:bb6un1j) ([raw file](https://github.com/sillsdev/TheCombine/blob/a50f8ab085f896489fe95c4aadff1f42762a1511/src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx#L245)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

The `async` and `await` in this test are unnecessary, since `dispatchMergeStepData` is syncronous.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-02 18:26 UTC, imnasnainaec reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2704)* status: 98 of 102 files reviewed, 4 unresolved discussions (waiting on @jmgrady)

___
*[`src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx` line 45 at r12](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-NiGB7LgEIciOtxY6rdh:-NiGB7LgEIciOtxY6rdi:b-sbly2h) ([raw file](https://github.com/sillsdev/TheCombine/blob/a50f8ab085f896489fe95c4aadff1f42762a1511/src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx#L45)):*
> ```XML
> }));
> 
> const mockGraylistAdd = jest.fn();
> ```

`mockGraylistAdd` (here) and `mockMergeWords` (above) should be on the same side of the `jest.mock("backend",...`
___
*[`src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx` line 103 at r12](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-NiGBd6s2MNMMiSS2vZW:-NiGBd6s2MNMMiSS2vZX:b-5u30oz) ([raw file](https://github.com/sillsdev/TheCombine/blob/a50f8ab085f896489fe95c4aadff1f42762a1511/src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx#L103)):*
> ```XML
>       const store = setupStore({
>         ...preloadedState,
>         mergeDuplicateGoal: { data, tree, mergeWords },
> ```

Here are `const mergeWords: MergeWords[] = [];` and `mergeDuplicateGoal: { data, tree, mergeWords },` while all the other tests have simply `mergeDuplicateGoal: { data, tree, mergeWords: [] },`.
___
*[`src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx` line 245 at r12](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-NiFZCQm-UzDYTgFKQ7t:-NiGHISqEvhNuAlMwCpb:brqpukb) ([raw file](https://github.com/sillsdev/TheCombine/blob/a50f8ab085f896489fe95c4aadff1f42762a1511/src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx#L245)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Done
</blockquote></details>

There's still an `async` on the tests.
___
*[`src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx` line 251 at r12](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-NiGCE5R3NfIziqLKE_R:-NiGCE5R3NfIziqLKE_S:b-2qoq5c) ([raw file](https://github.com/sillsdev/TheCombine/blob/a50f8ab085f896489fe95c4aadff1f42762a1511/src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx#L251)):*
> ```XML
>   });
> 
>   describe("moveSense", () => {
> ```

These `moveSense` tests and the `orderSense` tests below now feel a bit superfluous or overly specific. Since these two functions are more completely covered in `MergeDupsReducer`, they can probably be deleted from here.
___
*[`src/goals/MergeDuplicates/Redux/tests/MergeDupsDataMock.ts` line 250 at r12](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-NiGGmZv88MFslWA9R9M:-NiGGmZv88MFslWA9R9N:b-zfp4aj) ([raw file](https://github.com/sillsdev/TheCombine/blob/a50f8ab085f896489fe95c4aadff1f42762a1511/src/goals/MergeDuplicates/Redux/tests/MergeDupsDataMock.ts#L250)):*
> ```XML
> //
> //  Sense "bah" is dragged to Word2 and merged with sense "bag"
> export const mergeTwoDefinitionsScenario: GetMergeWordsScenario = {
> ```

Since the scenario above tests merging a sense from one word into a sense from another, it might be nice for this scenario to merge a sense from a word into another in the same word.


<!-- Sent from Reviewable.io -->

2023-11-02 20:46 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2704)* status: 98 of 102 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[`src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx` line 45 at r12](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-NiGB7LgEIciOtxY6rdh:-NiGhCBKEYV3CYMEsxpT:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/a50f8ab085f896489fe95c4aadff1f42762a1511/src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx#L45)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

`mockGraylistAdd` (here) and `mockMergeWords` (above) should be on the same side of the `jest.mock("backend",...`
</blockquote></details>

Done.
___
*[`src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx` line 103 at r12](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-NiGBd6s2MNMMiSS2vZW:-NiGiJ-IBHyi7gncSYH3:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/a50f8ab085f896489fe95c4aadff1f42762a1511/src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx#L103)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Here are `const mergeWords: MergeWords[] = [];` and `mergeDuplicateGoal: { data, tree, mergeWords },` while all the other tests have simply `mergeDuplicateGoal: { data, tree, mergeWords: [] },`.
</blockquote></details>

Done.
___
*[`src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx` line 245 at r12](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-NiFZCQm-UzDYTgFKQ7t:-NiGi_vZB8uLIylVEyIx:bdqqofm) ([raw file](https://github.com/sillsdev/TheCombine/blob/a50f8ab085f896489fe95c4aadff1f42762a1511/src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx#L245)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

There's still an `async` on the tests.
</blockquote></details>

The only ones I saw are all:
```
await store.dispatch(mergeAll());
```

This is appropriate because `mergeAll` is asynchronous - it has a few asynchronous calls to the backend (e.g. `addBlacklist`).
___
*[`src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx` line 251 at r12](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-NiGCE5R3NfIziqLKE_R:-NiGk3671Q904uQtvmMn:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/a50f8ab085f896489fe95c4aadff1f42762a1511/src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx#L251)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

These `moveSense` tests and the `orderSense` tests below now feel a bit superfluous or overly specific. Since these two functions are more completely covered in `MergeDupsReducer`, they can probably be deleted from here.
</blockquote></details>

Done.
___
*[`src/goals/MergeDuplicates/Redux/tests/MergeDupsDataMock.ts` line 250 at r12](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-NiGGmZv88MFslWA9R9M:-NiGkFnA9mTIONkzNEsH:b1kr1pr) ([raw file](https://github.com/sillsdev/TheCombine/blob/a50f8ab085f896489fe95c4aadff1f42762a1511/src/goals/MergeDuplicates/Redux/tests/MergeDupsDataMock.ts#L250)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

Since the scenario above tests merging a sense from one word into a sense from another, it might be nice for this scenario to merge a sense from a word into another in the same word.
</blockquote></details>

The scenarios were created to provide the following code coverage:
- `mergeTwoWordsScenario` is to test the logic in `getMergeWordsAction`;
- `mergeTwoSensesScenario` adds coverage for `combineIntoFirstSense` where definitions are not combined;
- `mergeTwoDefinitionsScenario` adds coverage for the logic that combines any definitions in the senses.

Are there specific ways our coverage would be improved or is this logic already covered by the other tests in `MergeDupsActions.test.tsx` and `MergeDupsReducer.test.tsx`?


<!-- Sent from Reviewable.io -->

2023-11-02 21:29 UTC, imnasnainaec reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2704)* status: 98 of 102 files reviewed, 2 unresolved discussions (waiting on @jmgrady)

___
*[`src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts` line 138 at r14](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-NiGsyIg6Dc_iv3zY461:-NiGsyIg6Dc_iv3zY462:byemur2) ([raw file](https://github.com/sillsdev/TheCombine/blob/9e71bc8e236261da14770d0191a1b6590b635f51/src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts#L138)):*
> ```XML
>     moveSenseAction: (state, action) => {
>       if (action.payload.ref.order === undefined) {
>         // MOVE_SENSE,
> ```

It might be nice to remove
```
      if (action.payload.ref.order === undefined) {
        // MOVE_SENSE,
```
and have an inverted check (analogous to the one in ` moveDuplicateAction`):
```
      // Verify that the ref.order field is undefined
      if (action.payload.ref.order !== undefined) {
        return;
      }
```

___
*[`src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx` line 245 at r12](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-NiFZCQm-UzDYTgFKQ7t:-NiGrcp3ABqwcHOtuQQ7:btln0ud) ([raw file](https://github.com/sillsdev/TheCombine/blob/a50f8ab085f896489fe95c4aadff1f42762a1511/src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx#L245)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

The only ones I saw are all:
```
await store.dispatch(mergeAll());
```

This is appropriate because `mergeAll` is asynchronous - it has a few asynchronous calls to the backend (e.g. `addBlacklist`).
</blockquote></details>

I'm referring to the `async` a few lines up:
```it("creates an action to add MergeDups data", async () => {```
___
*[`src/goals/MergeDuplicates/Redux/tests/MergeDupsDataMock.ts` line 250 at r12](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-NiGGmZv88MFslWA9R9M:-NiGuS0Y7jGNCci4siTI:bmdwmj5) ([raw file](https://github.com/sillsdev/TheCombine/blob/a50f8ab085f896489fe95c4aadff1f42762a1511/src/goals/MergeDuplicates/Redux/tests/MergeDupsDataMock.ts#L250)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

The scenarios were created to provide the following code coverage:
- `mergeTwoWordsScenario` is to test the logic in `getMergeWordsAction`;
- `mergeTwoSensesScenario` adds coverage for `combineIntoFirstSense` where definitions are not combined;
- `mergeTwoDefinitionsScenario` adds coverage for the logic that combines any definitions in the senses.

Are there specific ways our coverage would be improved or is this logic already covered by the other tests in `MergeDupsActions.test.tsx` and `MergeDupsReducer.test.tsx`?
</blockquote></details>

The merge-two-words-in-the-same-word situation is partially covered by `it("combine sense into other sense in same word",` in `MergeDupsReducer.test.tsx`, and broadly covered by `it("merges senses within a word",` in `MergeDupsActions.test.tsx`, but I thought it would be beneficial for `mergeTwoDefinitionsScenario` to also cover that situation at the `getMergeWords` level with these scenarios rather than being mostly redundant with the `mergeTwoSensesScenario`.


<!-- Sent from Reviewable.io -->

2023-11-03 15:20 UTC, imnasnainaec reviewed
> Reviewed 1 of 3 files at r10, 1 of 2 files at r11, 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2704)* status: 101 of 102 files reviewed, 1 unresolved discussion (waiting on @jmgrady)



<!-- Sent from Reviewable.io -->

2023-11-03 15:47 UTC, jmgrady reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2704)* status: 100 of 102 files reviewed, 1 unresolved discussion (waiting on @imnasnainaec and @jmgrady)

___
*[`src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts` line 138 at r14](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-NiGsyIg6Dc_iv3zY461:-NiKeF5c751nPvVsk7XF:b92bfjs) ([raw file](https://github.com/sillsdev/TheCombine/blob/9e71bc8e236261da14770d0191a1b6590b635f51/src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts#L138)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

It might be nice to remove
```
      if (action.payload.ref.order === undefined) {
        // MOVE_SENSE,
```
and have an inverted check (analogous to the one in ` moveDuplicateAction`):
```
      // Verify that the ref.order field is undefined
      if (action.payload.ref.order !== undefined) {
        return;
      }
```

</blockquote></details>

In my limited experience, the first form is preferred.  The guidelines for modular software design highly recommend that functions have a single entry and exit point.  There is a summary at https://www.exida.com/Blog/software-metrics-iso-26262-iec-61508.

I have changed most of the inverted checks to use this form.  I left the one at the beginning of `createMergeWords` because in this case the logic seems simpler.  (The single exit point is _Highly Recommended_, not _Mandated_.)
___
*[`src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx` line 245 at r12](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-NiFZCQm-UzDYTgFKQ7t:-NiKidCaEfulr-AunI9c:b-896fix) ([raw file](https://github.com/sillsdev/TheCombine/blob/a50f8ab085f896489fe95c4aadff1f42762a1511/src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx#L245)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I'm referring to the `async` a few lines up:
```it("creates an action to add MergeDups data", async () => {```
</blockquote></details>

Done.
___
*[`src/goals/MergeDuplicates/Redux/tests/MergeDupsDataMock.ts` line 250 at r12](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-NiGGmZv88MFslWA9R9M:-NiKjJ-XEenvozK66ih2:b-9yj7ve) ([raw file](https://github.com/sillsdev/TheCombine/blob/a50f8ab085f896489fe95c4aadff1f42762a1511/src/goals/MergeDuplicates/Redux/tests/MergeDupsDataMock.ts#L250)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

The merge-two-words-in-the-same-word situation is partially covered by `it("combine sense into other sense in same word",` in `MergeDupsReducer.test.tsx`, and broadly covered by `it("merges senses within a word",` in `MergeDupsActions.test.tsx`, but I thought it would be beneficial for `mergeTwoDefinitionsScenario` to also cover that situation at the `getMergeWords` level with these scenarios rather than being mostly redundant with the `mergeTwoSensesScenario`.
</blockquote></details>

Let's keep it as it is for now.


<!-- Sent from Reviewable.io -->

2023-11-03 18:10 UTC, imnasnainaec reviewed
> Reviewed 1 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2704)* status: 101 of 102 files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[`src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts` line 138 at r14](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-NiGsyIg6Dc_iv3zY461:-NiLMhMr4ZkTgZqfcmGx:b-hodqmu) ([raw file](https://github.com/sillsdev/TheCombine/blob/9e71bc8e236261da14770d0191a1b6590b635f51/src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts#L138)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

In my limited experience, the first form is preferred.  The guidelines for modular software design highly recommend that functions have a single entry and exit point.  There is a summary at https://www.exida.com/Blog/software-metrics-iso-26262-iec-61508.

I have changed most of the inverted checks to use this form.  I left the one at the beginning of `createMergeWords` because in this case the logic seems simpler.  (The single exit point is _Highly Recommended_, not _Mandated_.)
</blockquote></details>

Interesting. I'm personally more of the mind of this person https://stackoverflow.com/a/4838892/10210583
I find it easier to have guard statements at the top that eliminate cases and allow a narrower context for the rest of the function (which then also doesn't have to be indented/embedded as much).


<!-- Sent from Reviewable.io -->

2023-11-03 18:17 UTC, imnasnainaec requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2704)* status: 101 of 102 files reviewed, 1 unresolved discussion (waiting on @jmgrady)

___
*[`src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts` line 140 at r15](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-NiLNb6C8lyfLdkAxBsA:-NiLNb6C8lyfLdkAxBsB:bx2h2hn) ([raw file](https://github.com/sillsdev/TheCombine/blob/4071b20a87834e3ef106429b8296ccc135a8ada1/src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts#L140)):*
> ```XML
>       const destWordId = action.payload.destWordId;
>       const srcOrder = action.payload.ref.order;
>       if (srcOrder === undefined && srcWordId === destWordId) {
> ```

`srcWordId === destWordId` was a condition for returning early, but now is a condition for continuing in the function.
___
*[`src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts` line 172 at r15](https://reviewable.io/reviews/sillsdev/TheCombine/2704#-NiLOFFM-cnPuO3PFQhO:-NiLOFFM-cnPuO3PFQhP:bxgt4vw) ([raw file](https://github.com/sillsdev/TheCombine/blob/4071b20a87834e3ef106429b8296ccc135a8ada1/src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts#L172)):*
> ```XML
>       const srcRef = action.payload.ref;
>       // Verify that the ref.order field is defined
>       if (srcRef.order !== undefined) {
> ```

I understand this switch to avoid extra exit points, but it seems less helpful when the code below
```
          if (srcWordId === destWordId) {
            return;
          }
```
prevents there being a single exit point. (Both here in `moveDuplicateAction` and above in `moveSenseAction`.)


<!-- Sent from Reviewable.io -->

2023-11-06 16:02 UTC, imnasnainaec approved these changes
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/2704)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)



<!-- Sent from Reviewable.io -->

2023-11-06 16:37 UTC, merged