Add aggregate operation for merging analysis glosses
sillsdev/TheCombine pull request #3174
Opened 2024-06-21 20:03 UTC by jasonleenaylor

- Only merges if a word has only two senses where one sense has one english gloss and the other has one tok pisin gloss and the english sense has either no semantic domains or where all the semantic domains in the english sense are also in the tok pisin sense

2024-06-24 19:56 UTC, jasonleenaylor commented
*[`database/util/twoAnalysisSenseCleanup.js` line 66 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/3174#-O0A6C2j-z2yyQ3xilPj:-O0A6C2j-z2yyQ3xilPk:bf5nw8k) ([raw file](https://github.com/sillsdev/TheCombine/blob/7e76a4f5b857b2cc430f32a8560d0f8a57a0f4b0/database/util/twoAnalysisSenseCleanup.js#L66)):*
> ```JavaScript
>     // Add fields to extract semantic domain GUIDs from both senses
>     $addFields: {
>       semDomGuidsA: "$senseA.SemanticDomains.guid",
> ```

I do prefer the 'to' and 'from' naming over 'a' and 'b' because it helps readability. The direction of the merge is clarified by those names (to me at least)



_Code quote:_
```JavaScript
semDomGuidsA: "$senseA
```


<!-- Sent from Reviewable.io -->

2024-06-24 21:40 UTC, imnasnainaec reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3174)* status: 0 of 2 files reviewed, all discussions resolved

___
*[`database/util/twoAnalysisSenseCleanup.js` line 66 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/3174#-O0A6C2j-z2yyQ3xilPj:-O0BBAThCYsayceh2mfa:b67l0zv) ([raw file](https://github.com/sillsdev/TheCombine/blob/7e76a4f5b857b2cc430f32a8560d0f8a57a0f4b0/database/util/twoAnalysisSenseCleanup.js#L66)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

I do prefer the 'to' and 'from' naming over 'a' and 'b' because it helps readability. The direction of the merge is clarified by those names (to me at least)
</blockquote></details>

I had made it closer to symmetric, but since something from the second sense is lost, it is alas still unsymmetric. Your "to" and "from" preference has been restored.


<!-- Sent from Reviewable.io -->

2024-06-24 21:50 UTC, jasonleenaylor commented
*[`database/util/twoAnalysisSenseCleanup.js` line 66 at r2](https://reviewable.io/reviews/sillsdev/TheCombine/3174#-O0A6C2j-z2yyQ3xilPj:-O0BDFHV1AFZAQSiVrdC:b-g28e0c) ([raw file](https://github.com/sillsdev/TheCombine/blob/7e76a4f5b857b2cc430f32a8560d0f8a57a0f4b0/database/util/twoAnalysisSenseCleanup.js#L66)):*
<details><summary><i>Previously, imnasnainaec (D. Ror.) wrote…</i></summary><blockquote>

I had made it closer to symmetric, but since something from the second sense is lost, it is alas still unsymmetric. Your "to" and "from" preference has been restored.
</blockquote></details>

Thanks, even if some of the merging is more symmetric the 'from' sense is still being removed, so I like keeping track of the 'to' and 'from' .


<!-- Sent from Reviewable.io -->

2024-06-25 14:51 UTC, jmgrady requested changes
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3174)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @imnasnainaec and @jasonleenaylor)

___
*[`database/util/twoAnalysisSenseCleanup.sh` line 1 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/3174#-O0Elav_CuY5hUSND6cr:-O0Elavb7eyqhAcHHNyl:bl0gbzt) ([raw file](https://github.com/sillsdev/TheCombine/blob/bc5cac4bdba65cbcfb7e5a5771fefee6e0a71735/database/util/twoAnalysisSenseCleanup.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

```
#!/usr/bin/env bash
```
is preferred.

In addition, the file needs to have execute permission.



_Code quote:_
```Shell
#!/bin/bash
```
___
*[`database/util/twoAnalysisSenseCleanup.sh` line 9 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/3174#-O0EpLai0gY0ns1WZX96:-O0EpLai0gY0ns1WZX97:b-xm8ss7) ([raw file](https://github.com/sillsdev/TheCombine/blob/bc5cac4bdba65cbcfb7e5a5771fefee6e0a71735/database/util/twoAnalysisSenseCleanup.sh#L9)):*
> ```Shell
> set -e
> 
> usage() {
> ```

Most examples have a space between the function name and the parentheses.  I believe this is the preferred syntax:
```
usage () {
...
```



_Code quote:_
```Shell
usage() {
```
___
*[`database/util/twoAnalysisSenseCleanup.sh` line 30 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/3174#-O0EnwJtDcEe_qyymYVL:-O0EnwJtDcEe_qyymYVM:bn6ukqn) ([raw file](https://github.com/sillsdev/TheCombine/blob/bc5cac4bdba65cbcfb7e5a5771fefee6e0a71735/database/util/twoAnalysisSenseCleanup.sh#L30)):*
> ```Shell
> 
>   Caveat:
>     This script assumes that the backups have been created by the combine-backup
> ```

While it prudent to do a backup or export the project first, the script does not make any assumptions about backups one way or another.  In fact, backups are not supported on the NUCs or the desktop environment.



_Code quote:_
```Shell
  Caveat:
    This script assumes that the backups have been created by the combine-backup
```
___
*[`database/util/twoAnalysisSenseCleanup.sh` line 73 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/3174#-O0EqvppCFDr0-sqBEuB:-O0Eqvpq9fQiUb22T4sE:b-9uhkei) ([raw file](https://github.com/sillsdev/TheCombine/blob/bc5cac4bdba65cbcfb7e5a5771fefee6e0a71735/database/util/twoAnalysisSenseCleanup.sh#L73)):*
> ```Shell
>       if [[ "${PROJ}" =~ [^0-9a-f] ]]; then
>         echo "The -p/--proj argument must be a hexidecimal id"
>         exit 1
> ```

Should also verify that it is 24 characters long.



_Code quote:_
```Shell
      if [[ "${PROJ}" =~ [^0-9a-f] ]]; then
        echo "The -p/--proj argument must be a hexidecimal id"
        exit 1
```
___
*[`database/util/twoAnalysisSenseCleanup.sh` line 91 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/3174#-O0Er10TB-Tl7aydZvpj:-O0Er10U195Yvw_dnWav:b-e3rmy) ([raw file](https://github.com/sillsdev/TheCombine/blob/bc5cac4bdba65cbcfb7e5a5771fefee6e0a71735/database/util/twoAnalysisSenseCleanup.sh#L91)):*
> ```Shell
> 
> if [[ -z "${LANGA}" ]]; then
>   echo "The -A/--langA argument is require"
> ```

-> required
(and others)



_Code quote:_
```Shell
require
```
___
*[`database/util/twoAnalysisSenseCleanup.sh` line 92 at r3](https://reviewable.io/reviews/sillsdev/TheCombine/3174#-O0Er8887rZtnJKX0x2v:-O0Er889A7EeWshSZ1mT:bato3ih) ([raw file](https://github.com/sillsdev/TheCombine/blob/bc5cac4bdba65cbcfb7e5a5771fefee6e0a71735/database/util/twoAnalysisSenseCleanup.sh#L92)):*
> ```Shell
> if [[ -z "${LANGA}" ]]; then
>   echo "The -A/--langA argument is require"
>   echo "Run this script with -h/--help for usage"
> ```

Rather than have the user run the script again with the `-h` option, call the usage function before exiting.



_Code quote:_
```Shell
  echo "Run this script with -h/--help for usage"
```


<!-- Sent from Reviewable.io -->

2025-04-02 18:17 UTC, jasonleenaylor commented
This one shot script was executed to clean up our database, but it does not need to be kept around.

2025-04-02 18:17 UTC, closed without merging